[project]
name = "apof-bioinformatics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Chris Mungall", email = "cjm@berkeleybop.org" }
]
requires-python = ">=3.12"
dependencies = [
    "biopython>=1.88",
]

[project.scripts]
apof-bioinformatics = "apof_bioinformatics:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
