default: compare control
compare:
    uv run --no-project --with biopython==1.85 python compare.py ../CG33453-uniprot-source.json ../CG33453-reference-A1ZBI2-uniprot.json results
control:
    uv run --no-project --with biopython==1.85 python compare.py ../CG33453-reference-A1ZBI2-uniprot.json ../CG33453-reference-A1ZBI2-uniprot.json control
