default: compare control
compare:
    uv run --no-project --with biopython==1.85 python compare.py ../awd-uniprot-source.json ../awd-reference-P08879-uniprot.json results
control:
    uv run --no-project --with biopython==1.85 python compare.py ../awd-reference-P08879-uniprot.json ../awd-reference-P08879-uniprot.json control
