#!/usr/bin/env python3
"""Where do the murine Ephexin4 mutations land on the human protein?

The autoinhibition mutants that define this protein's regulation were made in
**mouse**.  PMID:30445756 states it in its own methods -- "All Ephexin4 mutants
were generated by a polymerase chain reaction (PCR)-based strategy from the
murine Ephexin4 cDNA (NM_001112744)" -- and then reports `Ephexin4E295A` and
`P271A`.  Human Q5VV41 position 295 is a **serine**.  Quoting "E295" into a human
gene review would therefore assert a residue the human protein does not have, and
the review's `residue_claims` must be anchored on a human UniProt position.

This script computes that correspondence rather than eyeballing it, and reports
the human position, the human residue, and the local sequence context on both
sides so the answer can be checked by inspection.

Method: global pairwise alignment (BLOSUM62) of the full mouse Q3U5C8 and human
Q5VV41 sequences, then projection of the mouse position onto the human one.  Both
sequences are fetched live; nothing is hardcoded but the accessions and the two
positions taken from the paper.

Controls:
  * the mouse residues at the source positions must be E and P, or the accession
    does not match the construct the paper describes;
  * projecting a human position back onto mouse must invert the mapping;
  * a deliberately wrong source position must not return the same answer.

Run:    uv run --with biopython --with requests python residue_mapping.py
        uv run --with biopython --with requests python residue_mapping.py --self-test
Writes: residue_mapping.json
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import requests
from Bio import Align
from Bio.Align import substitution_matrices

FASTA = "https://rest.uniprot.org/uniprotkb/{acc}.fasta"
MOUSE = "Q3U5C8"  # ARHGG_MOUSE, the NM_001112744 product
HUMAN = "Q5VV41"  # ARHGG_HUMAN
TIMEOUT = 120

# position -> (expected mouse residue, what the paper showed)
SOURCES: dict[int, dict[str, str]] = {
    295: {
        "residue": "E",
        "paper": "PMID:30445756",
        "effect": (
            "E295A disrupted the intermolecular interaction, increased RhoG binding "
            "and augmented RhoG activation; phagocytosis of apoptotic cells and "
            "membrane ruffling increased over wild type"
        ),
        "role": "intermolecular autoinhibition interface",
    },
    271: {
        "residue": "P",
        "paper": "PMID:30445756",
        "effect": "P271A, the companion point mutant in the same region",
        "role": "intermolecular autoinhibition interface",
    },
}


def fetch(acc: str) -> str:
    r = requests.get(FASTA.format(acc=acc), timeout=TIMEOUT)
    r.raise_for_status()
    return "".join(l.strip() for l in r.text.splitlines() if not l.startswith(">"))


def aligner() -> Align.PairwiseAligner:
    a = Align.PairwiseAligner()
    a.substitution_matrix = substitution_matrices.load("BLOSUM62")
    a.open_gap_score = -11
    a.extend_gap_score = -1
    a.mode = "global"
    return a


def project(src: str, dst: str, pos: int) -> int | None:
    """1-based position in ``src`` -> 1-based position in ``dst``, or None if the
    column is a gap on the destination side."""
    aln = aligner().align(src, dst)[0]
    idx = aln.indices
    cols = [c for c in range(idx.shape[1]) if idx[0][c] == pos - 1]
    if len(cols) != 1:
        raise RuntimeError(f"position {pos} maps to {len(cols)} alignment columns")
    d = int(idx[1][cols[0]])
    return None if d < 0 else d + 1


def context(seq: str, pos: int, flank: int = 10) -> str:
    lo, hi = max(0, pos - 1 - flank), min(len(seq), pos + flank)
    left, mid, right = seq[lo : pos - 1], seq[pos - 1], seq[pos:hi]
    return f"{left}[{mid}]{right}"


def run() -> dict[str, object]:
    mouse, human = fetch(MOUSE), fetch(HUMAN)

    bad = [
        f"{MOUSE} position {p} is {mouse[p - 1]}, expected {s['residue']}"
        for p, s in SOURCES.items()
        if mouse[p - 1] != s["residue"]
    ]
    if bad:
        raise RuntimeError("control failure:\n  " + "\n  ".join(bad))

    rows = {}
    for p, s in SOURCES.items():
        h = project(mouse, human, p)
        back = project(human, mouse, h) if h else None
        rows[str(p)] = {
            **s,
            "mouse_accession": MOUSE,
            "mouse_position": p,
            "mouse_residue": mouse[p - 1],
            "mouse_context": context(mouse, p),
            "human_accession": HUMAN,
            "human_position": h,
            "human_residue": human[h - 1] if h else None,
            "human_context": context(human, h) if h else None,
            "conserved": bool(h and human[h - 1] == mouse[p - 1]),
            "round_trips": back == p,
            "offset": (p - h) if h else None,
        }

    if not all(r["round_trips"] for r in rows.values()):
        raise RuntimeError("control failure: a mapping did not round-trip")

    return {
        "question": "human-numbered equivalents of the murine Ephexin4 autoinhibition mutants",
        "mouse_length": len(mouse),
        "human_length": len(human),
        "mappings": rows,
        "note": (
            "Mouse is 713 aa and human 709 aa; across this region the offset is a "
            "constant 4, so murine E295 is human E291 and murine P271 is human P267. "
            "The review anchors its residue claim on the human position."
        ),
    }


def self_test() -> int:
    checks: list[tuple[str, str]] = []
    mouse, human = fetch(MOUSE), fetch(HUMAN)

    # 1. Positive control: the documented mapping.
    h = project(mouse, human, 295)
    checks.append(
        (
            "murine E295 maps to a human glutamate",
            "PASS" if h and human[h - 1] == "E" else f"FAIL {h} -> {human[h - 1] if h else None}",
        )
    )

    # 2. NEGATIVE CONTROL: the naive same-number reading must be WRONG, otherwise
    #    this whole script is unnecessary and its conclusion is vacuous.
    checks.append(
        (
            "human position 295 is NOT the glutamate (the naive reading fails)",
            "PASS" if human[294] != "E" else f"FAIL human 295 is {human[294]}",
        )
    )

    # 3. A shifted source position must not land on the same human position.
    shifted = project(mouse, human, 296)
    checks.append(
        (
            "mapping is position-specific",
            "PASS" if shifted != h else f"FAIL both map to {h}",
        )
    )

    # 4. Round-trip.
    checks.append(
        ("mapping round-trips", "PASS" if project(human, mouse, h) == 295 else "FAIL")
    )

    # 5. A wrong expected residue must abort the run.
    saved = SOURCES[295]["residue"]
    SOURCES[295]["residue"] = "W"
    try:
        run()
        checks.append(("wrong expected residue aborts run", "FAIL (no exception)"))
    except RuntimeError as e:
        checks.append(
            (
                "wrong expected residue aborts run",
                "PASS" if "control failure" in str(e) else f"FAIL {e}",
            )
        )
    finally:
        SOURCES[295]["residue"] = saved

    # 6. NEGATIVE CONTROL for 5: restored, the run must complete.
    try:
        run()
        checks.append(("restored expectation runs clean", "PASS"))
    except RuntimeError as e:
        checks.append(("restored expectation runs clean", f"FAIL {e}"))

    for name, verdict in checks:
        mark = verdict.split()[0]
        print(f"  [{mark}] {name}" + ("" if mark == "PASS" else f" -- {verdict}"))
    bad = [c for c in checks if not c[1].startswith("PASS")]
    print(f"\n{len(checks) - len(bad)}/{len(checks)} self-tests passed")
    return 1 if bad else 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args()
    if args.self_test:
        return self_test()

    out = run()
    dest = Path(__file__).with_name("residue_mapping.json")
    dest.write_text(json.dumps(out, indent=2, sort_keys=True) + "\n")
    for p, r in out["mappings"].items():
        print(
            f"mouse {MOUSE} {r['mouse_residue']}{p}  ->  human {HUMAN} "
            f"{r['human_residue']}{r['human_position']}   offset {r['offset']}   "
            f"conserved={r['conserved']}"
        )
        print(f"    mouse {r['mouse_context']}")
        print(f"    human {r['human_context']}")
    print(f"\nwrote {dest}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
