#!/usr/bin/env python3
"""Are AARD's 15 reported interactors a coherent partner set, or a Y2H artefact signature?

AARD's entire GO record is 15 `protein binding` annotations, all from one yeast two-hybrid
publication. Before dismissing or accepting them, this asks whether the partner set looks
like biology or like a known screening artefact.

The hypothesis being tested is specific and falsifiable: **coiled-coil bias**. Self-activating
or "sticky" preys in Y2H are enriched for coiled-coil proteins, which interact promiscuously
through their heptad-repeat surfaces. If AARD's partners are drawn from unrelated cellular
compartments but share a coiled-coil architecture, the set is better explained by the assay
than by a function.

Partner accessions and the subcellular/feature data are fetched from UniProt at run time; the
accession list itself is read from the gene's own GOA file, so it cannot drift from the record
being reviewed.

    uv run python analyze_partners.py          # writes RESULTS.md
"""
from __future__ import annotations

import csv
import json
import re
import sys
import urllib.error
import urllib.request
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent
GOA = HERE.parent / "AARD-goa.tsv"


def get(url: str):
    """GET JSON, returning None on failure so callers can tell failure from absence."""
    req = urllib.request.Request(url, headers={"Accept": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=120) as fh:
            return json.load(fh)
    except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as e:
        print(f"  ! fetch failed: {url} ({e})", file=sys.stderr)
        return None


def partners_from_goa(path: Path) -> list[str]:
    """Read the WITH/FROM accessions off the gene's own GOA file."""
    out: list[str] = []
    with open(path) as fh:
        for row in csv.DictReader(fh, delimiter="\t"):
            wf = (row.get("WITH/FROM") or "").strip()
            for token in wf.split("|"):
                if token.startswith("UniProtKB:"):
                    out.append(token.split(":", 1)[1])
    return out


def describe(acc: str) -> dict | None:
    base = acc.split("-")[0]
    d = get(f"https://rest.uniprot.org/uniprotkb/{base}.json"
            "?fields=id,gene_names,protein_name,cc_subcellular_location,ft_coiled,keyword")
    if d is None:
        return None
    genes = [g.get("geneName", {}).get("value") for g in d.get("genes", [])]
    coiled = [f for f in d.get("features", []) if f.get("type") == "Coiled coil"]
    kws = {k.get("name") for k in d.get("keywords", [])}
    locs: list[str] = []
    for c in d.get("comments", []):
        if c.get("commentType") == "SUBCELLULAR LOCATION":
            for loc in c.get("subcellularLocations", []):
                v = (loc.get("location") or {}).get("value")
                if v:
                    locs.append(v)
    return {
        "acc": acc,
        "id": d.get("uniProtkbId", ""),
        "gene": genes[0] if genes else "?",
        "n_coiled": len(coiled),
        "coiled_kw": "Coiled coil" in kws,
        "locations": locs,
    }


def main() -> None:
    if not GOA.exists():
        print(f"missing {GOA}; cannot proceed", file=sys.stderr)
        return
    accs = partners_from_goa(GOA)
    print(f"{len(accs)} partner accessions read from {GOA.name}")

    rows = [r for a in accs if (r := describe(a)) is not None]
    n_failed = len(accs) - len(rows)
    for r in rows:
        print(f"  {r['acc']:<10} {r['gene']:<10} coiled-coil segments: {r['n_coiled']}")

    n_coiled = sum(1 for r in rows if r["n_coiled"] > 0 or r["coiled_kw"])
    loc_counts: Counter[str] = Counter()
    for r in rows:
        for l in r["locations"]:
            loc_counts[l] += 1

    L: list[str] = []
    L.append("# Are AARD's reported interactors a coherent partner set?")
    L.append("")
    L.append("Generated by `analyze_partners.py`. Partner accessions are read from the gene's own")
    L.append("`AARD-goa.tsv`; all protein data is fetched from the UniProt REST API at run time.")
    L.append("")
    L.append("## Question")
    L.append("")
    L.append("AARD's entire GO record consists of `protein binding` annotations from a single")
    L.append("yeast two-hybrid publication. This tests one specific, falsifiable explanation for")
    L.append("that set: **coiled-coil bias**. Sticky or self-activating preys in Y2H are enriched")
    L.append("for coiled-coil proteins, which associate promiscuously via heptad-repeat surfaces.")
    L.append("If the partners come from unrelated compartments but share coiled-coil")
    L.append("architecture, the assay explains the set better than any function does.")
    L.append("")
    L.append("## Result")
    L.append("")
    L.append(f"| Partner accessions in the GOA file | {len(accs)} |")
    L.append("|---|---|")
    L.append(f"| Successfully retrieved from UniProt | {len(rows)} |")
    L.append(f"| **With an annotated coiled-coil region** | **{n_coiled}** |")
    if len(rows):
        L.append(f"| Proportion coiled-coil | **{100 * n_coiled / len(rows):.0f}%** |")
    L.append("")
    if n_failed:
        L.append(f"> WARNING: {n_failed} accession(s) failed to retrieve; counts understate the set.")
        L.append("")
    L.append("## Partners")
    L.append("")
    L.append("| Accession | Gene | Coiled-coil segments | Subcellular location |")
    L.append("|---|---|---|---|")
    for r in sorted(rows, key=lambda x: (-x["n_coiled"], x["gene"])):
        loc = "; ".join(r["locations"][:3]) or "—"
        cc = str(r["n_coiled"]) if r["n_coiled"] else ("keyword only" if r["coiled_kw"] else "0")
        L.append(f"| {r['acc']} | {r['gene']} | {cc} | {loc} |")
    L.append("")
    L.append("## Compartment spread")
    L.append("")
    L.append("A genuine partner set usually concentrates in one or two compartments. Observed:")
    L.append("")
    for loc, n in loc_counts.most_common():
        L.append(f"- {loc}: {n}")
    L.append("")
    with open(HERE / "RESULTS.md", "w") as fh:
        fh.write("\n".join(L) + "\n")
    print(f"\n{n_coiled}/{len(rows)} partners have a coiled-coil region")
    print("wrote RESULTS.md")


if __name__ == "__main__":
    main()
