default: compare control
compare:
    uv run --no-project --with biopython==1.85 python compare.py ../ttv-uniprot-source.json ../ttv-reference-Q9V730-uniprot.json results
control:
    uv run --no-project --with biopython==1.85 python compare.py ../ttv-reference-Q9V730-uniprot.json ../ttv-reference-Q9V730-uniprot.json control
