default: compare control
compare:
    uv run --no-project --with biopython==1.85 python compare.py ../loqs-uniprot-source.json ../loqs-reference-Q9VJY9-uniprot.json results
control:
    uv run --no-project --with biopython==1.85 python compare.py ../loqs-reference-Q9VJY9-uniprot.json ../loqs-reference-Q9VJY9-uniprot.json control
