"""Audit which UniProt accession each reviewed zebrafish gene should be reviewed on.

Zebrafish genes often have several UniProt entries (a Swiss-Prot or legacy
TrEMBL entry plus RefSeq-derived TrEMBL entries). ZFIN's experimental GO
annotations are mapped to only some of them, so the accession a review is seeded
from can miss experimental annotations that GOA holds for the same gene.

For each gene this script:
  * lists every UniProtKB accession for the gene symbol in taxon 7955;
  * counts GOA annotations on each (QuickGO), all and experimental;
  * lists the experimental annotations (term, evidence, reference) held on other
    accessions but absent from the accession the review uses, and whether the
    review already covers that term + reference (e.g. added as NEW).

Usage (from repo root):
    uv run python projects/DANRE_DUPLICATION/scripts/accession_audit.py GENE [GENE ...] \
        > projects/DANRE_DUPLICATION/accession_audit.md
"""

import json
import sys
import time
import urllib.parse
import urllib.request
from pathlib import Path

import yaml

EXPERIMENTAL = {"EXP", "IDA", "IPI", "IMP", "IGI", "IEP", "HTP", "HDA", "HMP", "HGI", "HEP"}
QUICKGO = "https://www.ebi.ac.uk/QuickGO/services/annotation/search"
UNIPROT = "https://rest.uniprot.org/uniprotkb/search"


def get_json(url: str) -> dict:
    for attempt in range(5):
        try:
            req = urllib.request.Request(url, headers={"Accept": "application/json"})
            with urllib.request.urlopen(req, timeout=60) as resp:
                return json.load(resp)
        except Exception:
            time.sleep(2**attempt)
    raise RuntimeError(f"failed: {url}")


def accessions(gene: str) -> list[tuple[str, str]]:
    q = urllib.parse.urlencode({"query": f'gene_exact:"{gene}" AND organism_id:7955',
                                "fields": "accession,reviewed", "format": "json", "size": 100})
    data = get_json(f"{UNIPROT}?{q}")
    return [(r["primaryAccession"], "reviewed" if "Swiss" in r["entryType"] else "unreviewed")
            for r in data.get("results", [])]


def annotations(acc: str) -> list[dict]:
    out, page = [], 1
    while True:
        q = urllib.parse.urlencode({"geneProductId": acc, "limit": 100, "page": page})
        data = get_json(f"{QUICKGO}?{q}")
        out.extend(data.get("results", []))
        if page >= data.get("pageInfo", {}).get("total", 1):
            return out
        page += 1


def key(a: dict) -> tuple[str, str, str, str]:
    return (a["goId"], a["goEvidence"], a["reference"], a.get("qualifier") or "")


def main(genes: list[str]) -> None:
    print("# Zebrafish accession audit\n")
    print("Generated by `projects/DANRE_DUPLICATION/scripts/accession_audit.py`; do not edit by hand.\n")
    print("Experimental = " + ", ".join(sorted(EXPERIMENTAL)) + ".\n")
    summary = []
    details = []
    for gene in genes:
        review_path = Path(f"genes/DANRE/{gene}/{gene}-ai-review.yaml")
        review = yaml.safe_load(review_path.open())
        used = review["id"]
        covered = {(a["term"]["id"], a.get("original_reference_id", ""))
                   for a in review.get("existing_annotations") or []}
        accs = accessions(gene)
        if used not in {a for a, _ in accs}:
            accs.append((used, "?"))
        per_acc = {}
        for acc, status in accs:
            anns = annotations(acc)
            per_acc[acc] = (status, anns)
        used_exp = {key(a) for a in per_acc[used][1] if a["goEvidence"] in EXPERIMENTAL}
        elsewhere: dict[tuple, set[str]] = {}
        for acc, (_, anns) in per_acc.items():
            if acc == used:
                continue
            for a in anns:
                if a["goEvidence"] in EXPERIMENTAL and key(a) not in used_exp:
                    elsewhere.setdefault(key(a), set()).add(acc)
        missing_uncovered = [k for k in elsewhere if (k[0], k[2]) not in covered]
        best = max(per_acc, key=lambda x: (sum(a["goEvidence"] in EXPERIMENTAL for a in per_acc[x][1]),
                                           len(per_acc[x][1])))
        summary.append((gene, used, per_acc[used][0], len(per_acc[used][1]), len(used_exp),
                        best, len(elsewhere), len(missing_uncovered)))
        rows = [f"### {gene}\n", "| Accession | UniProt status | GOA annotations | Experimental | Used in review |",
                "|---|---|---|---|---|"]
        for acc, (status, anns) in sorted(per_acc.items(), key=lambda kv: -len(kv[1][1])):
            if not anns and acc != used:
                continue
            n_exp = sum(a["goEvidence"] in EXPERIMENTAL for a in anns)
            rows.append(f"| {acc} | {status} | {len(anns)} | {n_exp} | {'**yes**' if acc == used else ''} |")
        if elsewhere:
            rows += ["", f"Experimental annotations on other accessions but not on {used}:", "",
                     "| GO term | Evidence | Reference | Qualifier | On accession(s) | Term + reference already in review? |",
                     "|---|---|---|---|---|---|"]
            for k in sorted(elsewhere):
                rows.append(f"| {k[0]} | {k[1]} | {k[2]} | {k[3]} | {', '.join(sorted(elsewhere[k]))} | "
                            f"{'yes' if (k[0], k[2]) in covered else '**no**'} |")
        details.append("\n".join(rows) + "\n")

    print("## Summary\n")
    print("| Gene | Reviewed accession | Status | GOA annotations | Experimental | Accession with most experimental | "
          "Experimental rows only on other accessions | ...of which not covered by the review |")
    print("|---|---|---|---|---|---|---|---|")
    for s in summary:
        print("| " + " | ".join(str(x) for x in s) + " |")
    print("\n## Per gene\n")
    print("\n".join(details))


if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    main(sys.argv[1:])
