"""Side-by-side comparison of two zebrafish paralog gene reviews.

Reports, as markdown:
  1. protein-level comparison: lengths and global pairwise identity/similarity
     (Biopython PairwiseAligner, BLOSUM62, gap open -10 / extend -0.5), computed
     from the cached UniProt records;
  2. existing GO annotations of each copy, grouped by term, with evidence codes
     and review actions, so asymmetries between the copies are visible;
  2b. terms missing from both GOA files (e.g. proposed NEW terms) get their
     aspect from the QuickGO API;
  3. the molecular functions each review lists under core_functions.

Usage (from repo root):
    uv run python projects/DANRE_DUPLICATION/scripts/compare_pair.py mitfa mitfb \
        > projects/DANRE_DUPLICATION/pairs/mitfa_mitfb/annotation-comparison.md
"""

import csv
import json
import sys
import urllib.request
from collections import defaultdict
from pathlib import Path

import yaml
from Bio import Align
from Bio.Align import substitution_matrices

GENES = Path("genes/DANRE")


def load_sequence(gene: str) -> str:
    seq, in_seq = [], False
    for line in (GENES / gene / f"{gene}-uniprot.txt").open():
        if line.startswith("SQ "):
            in_seq = True
        elif line.startswith("//"):
            break
        elif in_seq:
            seq.append(line.replace(" ", "").strip())
    return "".join(seq)


def identity(a: str, b: str) -> tuple[float, float, int]:
    aligner = Align.PairwiseAligner(mode="global")
    aligner.substitution_matrix = substitution_matrices.load("BLOSUM62")
    aligner.open_gap_score = -10
    aligner.extend_gap_score = -0.5
    aln = aligner.align(a, b)[0]
    matrix = aligner.substitution_matrix
    ident = sim = cols = 0
    for (s1, e1), (s2, e2) in zip(*aln.aligned):
        for x, y in zip(a[s1:e1], b[s2:e2]):
            cols += 1
            ident += x == y
            sim += matrix[x][y] > 0
    length = aln.shape[1]
    return 100 * ident / length, 100 * sim / length, length


def aspects(gene: str) -> dict[str, str]:
    out = {}
    path = GENES / gene / f"{gene}-goa.tsv"
    if path.exists():
        for row in csv.DictReader(path.open(), delimiter="\t"):
            out[row["GO TERM"]] = {"biological_process": "BP", "molecular_function": "MF",
                                   "cellular_component": "CC"}.get(row["GO ASPECT"], "?")
    return out


def quickgo_aspect(term_id: str) -> str:
    """Aspect for a term not in either GOA file (e.g. a proposed NEW term)."""
    url = f"https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/{term_id}"
    try:
        with urllib.request.urlopen(url, timeout=30) as resp:
            aspect = json.load(resp)["results"][0]["aspect"]
    except Exception:
        return "?"
    return {"biological_process": "BP", "molecular_function": "MF", "cellular_component": "CC"}.get(aspect, "?")


def load_review(gene: str) -> dict:
    return yaml.safe_load((GENES / gene / f"{gene}-ai-review.yaml").open())


def main(a: str, b: str) -> None:
    ra, rb = load_review(a), load_review(b)
    sa, sb = load_sequence(a), load_sequence(b)
    pid, psim, alen = identity(sa, sb)
    print(f"# {a} / {b}: annotation comparison\n")
    print("Generated by `projects/DANRE_DUPLICATION/scripts/compare_pair.py`; do not edit by hand.\n")
    print("## Proteins\n")
    print(f"| | {a} | {b} |\n|---|---|---|")
    print(f"| UniProt | {ra['id']} | {rb['id']} |")
    print(f"| Length (aa) | {len(sa)} | {len(sb)} |")
    print(f"\nGlobal alignment (BLOSUM62, gap -10/-0.5): **{pid:.1f}% identity**, "
          f"{psim:.1f}% similarity over {alen} alignment columns.\n")

    asp = {**aspects(a), **aspects(b)}
    table: dict[tuple[str, str], dict[str, list[str]]] = defaultdict(lambda: {a: [], b: []})
    for gene, review in ((a, ra), (b, rb)):
        for ann in review.get("existing_annotations") or []:
            term = ann["term"]
            neg = "NOT " if ann.get("negated") else ""
            action = (ann.get("review") or {}).get("action", "PENDING")
            table[(term["id"], term.get("label", ""))][gene].append(
                f"{neg}{ann.get('evidence_type', '?')}:{action}")
    for tid, _ in table:
        if tid not in asp:
            asp[tid] = quickgo_aspect(tid)
    print("## Existing annotations by term\n")
    print("Cells show `evidence:action`. `—` means the copy has no annotation to that exact term "
          "(it may still have a parent or child term).\n")
    for aspect in ("MF", "BP", "CC", "?"):
        rows = sorted((k, v) for k, v in table.items() if asp.get(k[0], "?") == aspect)
        if not rows:
            continue
        print(f"### {aspect}\n")
        print(f"| Term | {a} | {b} |\n|---|---|---|")
        for (tid, label), cells in rows:
            fa = "<br>".join(sorted(set(cells[a]))) or "—"
            fb = "<br>".join(sorted(set(cells[b]))) or "—"
            print(f"| {tid} {label} | {fa} | {fb} |")
        print()

    print("## Core molecular functions\n")
    for gene, review in ((a, ra), (b, rb)):
        mfs = [cf.get("molecular_function", {}) for cf in review.get("core_functions") or []]
        listed = "; ".join(f"{m.get('id')} {m.get('label')}" for m in mfs if m) or "none"
        print(f"- **{gene}**: {listed}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2])
