---
site_name: "ai-gene-review"
theme:
  name: material
  # palette:
  #  scheme: slate
  #  primary: cyan
  features:
    - content.tabs.link

# for adding extra css/js see https://www.mkdocs.org/user-guide/customizing-your-theme/

plugins:
  - search
  - mknotebooks:
      execute: false
  - mermaid2:
      version: 11.4.1
  
#watch:
#  - src/ai_gene_review/schema

nav:
  - Home: index.md
  
exclude_docs: |
  /templates-linkml/

site_url: https://ai4curation.github.io/ai-gene-review
repo_url: https://github.com/ai4curation/ai-gene-review
