set shell := ["bash", "-eu", "-o", "pipefail", "-c"]

analyze:
    uv run python analyze_mthfr.py \
      --local Q88E30=../PP_4638-uniprot.txt \
      --local Q88D51=../../metF/metF-uniprot.txt \
      --uniprot-reference P0AEZ1 \
      --ncbi-reference BAK65950.1 \
      --output-dir results

