all:
    uv run python scan_motif.py ../DpuGr29-uniprot.txt --pattern "TY.{5}QF" > target-motif.json
    uv run python scan_motif.py ../../../human/AKIRIN1/AKIRIN1-uniprot.txt --pattern "TY.{5}QF" > control-motif.json
