#!/usr/bin/env python3
"""Resolve ABHD8's IBA WITH/FROM sources, so the review's claims about them are checkable.

Two identifications in the ABHD8 review cannot be verified from inside the repository, and
both changed an action:

* **SGD:S000004089 is ICT1_YEAST, a genuine acyltransferase** rather than an artefact of one
  paralog. This is what downgraded two lipid-activity rows from REMOVE to
  MARK_AS_OVER_ANNOTATED.
* **UniProtKB:Q8WTS1 (ABHD5) has no annotated active site, while ABHD8 has a full triad.**
  This is what blocks the common "ABHD5 is a fold without a function, so ABHD8 is too"
  analogy. Note it does *not* make ABHD5 catalytically dead - UniProt records a demonstrated
  acyltransferase activity for it - so the analogy fails in both directions. The script
  prints the evidence for both halves.

Accessions are read from the gene's own GOA file so they cannot drift from the record under
review; everything else is fetched from the UniProt REST API at run time.

Fetches are deliberately *not* wrapped in try/except. A network failure must abort loudly and
leave RESULTS.md untouched, rather than quietly rewriting it with "lookup failed" placeholders
- which would silently break the supporting_text quotes the review draws from this file.

    uv run python resolve_iba_sources.py    # writes RESULTS.md
"""
from __future__ import annotations

import csv
import json
import sys
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
GOA = HERE.parent / "ABHD8-goa.tsv"


def get(url: str) -> dict:
    """GET JSON from the UniProt REST API."""
    req = urllib.request.Request(url, headers={"Accept": "application/json"})
    with urllib.request.urlopen(req, timeout=120) as fh:
        return json.load(fh)


def iba_sources(path: Path) -> dict[str, list[str]]:
    """Map each IBA row's GO id to its WITH/FROM tokens, straight from the GOA file."""
    out: dict[str, list[str]] = {}
    with open(path) as fh:
        for row in csv.DictReader(fh, delimiter="\t"):
            if row.get("GO EVIDENCE CODE") != "IBA":
                continue
            out[row["GO TERM"]] = [t for t in (row.get("WITH/FROM") or "").split("|") if t]
    return out


def describe_uniprot(acc: str) -> dict:
    """Fetch the name, organism, active-site count and FUNCTION text for one accession."""
    d = get(f"https://rest.uniprot.org/uniprotkb/{acc}.json"
            "?fields=id,protein_name,organism_name,gene_names,ft_act_site,cc_function")
    act = [f for f in d.get("features", []) if f.get("type") == "Active site"]
    fn = ""
    for c in d.get("comments", []):
        if c.get("commentType") == "FUNCTION":
            fn = " ".join(t.get("value", "") for t in c.get("texts", []))
    return {
        "acc": acc,
        "id": d.get("uniProtkbId", ""),
        "organism": d.get("organism", {}).get("scientificName", ""),
        "name": (d.get("proteinDescription", {}).get("recommendedName", {})
                 .get("fullName", {}).get("value", "")),
        "n_act_site": len(act),
        "function": fn,
    }


def resolve_sgd(sgd_id: str) -> dict:
    """Resolve an SGD locus id to its reviewed UniProt entry."""
    d = get("https://rest.uniprot.org/uniprotkb/search"
            f"?query=xref:sgd-{sgd_id}+AND+reviewed:true"
            "&fields=accession,id,protein_name,organism_name,gene_names&format=json&size=1")
    if not d.get("results"):
        raise LookupError(f"no reviewed UniProt entry cross-references SGD:{sgd_id}")
    r = d["results"][0]
    return {
        "sgd": sgd_id,
        "acc": r["primaryAccession"],
        "id": r.get("uniProtkbId", ""),
        "name": (r.get("proteinDescription", {}).get("recommendedName", {})
                 .get("fullName", {}).get("value", "")),
        "genes": [g.get("geneName", {}).get("value") for g in r.get("genes", [])],
    }


def main() -> None:
    if not GOA.exists():
        print(f"missing {GOA}", file=sys.stderr)
        raise SystemExit(1)
    srcs = iba_sources(GOA)
    print(f"{len(srcs)} IBA rows read from {GOA.name}")

    L: list[str] = []
    L.append("# What are ABHD8's IBA source proteins, and does any of them justify a lipid activity?")
    L.append("")
    L.append("Generated by `resolve_iba_sources.py`. Accessions are read from this gene's own")
    L.append("`ABHD8-goa.tsv`; all protein data is fetched from the UniProt REST API at run time.")
    L.append("")
    L.append("## WITH/FROM per IBA row")
    L.append("")
    L.append("The rows do not share a source set, which matters: a `propagation_review` copied from")
    L.append("one row to another will misstate what was inspected.")
    L.append("")
    L.append("| GO term | WITH/FROM sources |")
    L.append("|---|---|")
    for go, toks in sorted(srcs.items()):
        L.append(f"| {go} | {', '.join(f'`{t}`' for t in toks)} |")
    L.append("")

    L.append("## The two identifications the review depends on")
    L.append("")
    sgd = resolve_sgd("S000004089")
    genes = ", ".join(g for g in sgd["genes"] if g)
    L.append(f"SGD:S000004089 resolves to {sgd['id']} ({sgd['acc']}, gene {genes}), whose UniProt "
             f"recommended name is \"{sgd['name']}\".")
    L.append("")
    L.append("The acyltransferase activity therefore sits in a named, reviewed member of this family")
    L.append("in another organism, so the two acyltransferase-branch IBAs are propagating from a real")
    L.append("annotated activity. They are marked over-annotated rather than removed because what is")
    L.append("absent is a demonstration in ABHD8, not an activity in the family.")
    L.append("")

    for acc in ("Q8WTS1", "Q96I13"):
        d = describe_uniprot(acc)
        L.append(f"**{acc}** — {d['id']}, {d['organism']}: {d['name']}")
        L.append(f"- annotated active-site residues: **{d['n_act_site']}**")
        if d["function"]:
            L.append(f"- FUNCTION: {d['function'][:300]}")
        L.append("")

    L.append("Read those two blocks together, because they cut in opposite directions and both")
    L.append("matter to this review.")
    L.append("")
    L.append("**ABHD5 is not the pseudoenzyme it is usually invoked as.** It is routinely cited as the")
    L.append("family's fold-without-catalysis case - its nucleophilic serine is replaced, which is why")
    L.append("no active site is annotated - yet UniProt records a *demonstrated* CoA-dependent")
    L.append("lysophosphatidic acid acyltransferase activity for it, with substrate preferences and a")
    L.append("primary reference. So Q8WTS1, the source of ABHD8's `GO:0006654` and `GO:0042171` IBAs,")
    L.append("carries a measured acyl-transfer activity and not merely a fold.")
    L.append("")
    L.append("**The analogy cannot be run the other way either.** The active-site counts show ABHD8 has")
    L.append("a full annotated charge-relay triad where ABHD5 has none, so ABHD8 cannot be dismissed as")
    L.append("an ABHD5-type catalytically dead fold. Both the case for the lipid IBAs and the case")
    L.append("against them are weaker than the ABHD5 comparison is usually made to carry. The")
    L.append("defensible position is the narrow one: ABHD8's triad is intact and untested.")
    L.append("")

    (HERE / "RESULTS.md").write_text("\n".join(L) + "\n")
    print("wrote RESULTS.md")


if __name__ == "__main__":
    main()
