default: compare control
compare:
    uv run --no-project --with biopython==1.85 python compare.py ../CSN5-uniprot-source.json ../CSN5-reference-Q9XZ58-uniprot.json results
control:
    uv run --no-project --with biopython==1.85 python compare.py ../CSN5-reference-Q9XZ58-uniprot.json ../CSN5-reference-Q9XZ58-uniprot.json control
