#!/usr/bin/env python3
"""First-pass curation for ppu02040 flagellar motor/switch/stator genes."""

from __future__ import annotations

from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[2]
GENE_ROOT = ROOT / "genes/PSEPK"


class NoAliasDumper(yaml.SafeDumper):
    def ignore_aliases(self, data):
        return True


def term(term_id: str, label: str) -> dict[str, str]:
    return {"id": term_id, "label": label}


def ref(reference_id: str, text: str) -> dict[str, str]:
    return {"reference_id": reference_id, "supporting_text": text}


def review(
    summary: str,
    action: str,
    reason: str,
    supported_by: list[dict[str, str]] | None = None,
    proposed_replacement_terms: list[dict[str, str]] | None = None,
) -> dict:
    data: dict = {"summary": summary, "action": action, "reason": reason}
    if proposed_replacement_terms:
        data["proposed_replacement_terms"] = proposed_replacement_terms
    if supported_by:
        data["supported_by"] = supported_by
    return data


GO_REF_INTERPRO = {
    "id": "GO_REF:0000002",
    "title": "Gene Ontology annotation through association of InterPro records with GO terms",
    "findings": [],
}
GO_REF_SUBCELL = {
    "id": "GO_REF:0000044",
    "title": "Gene Ontology annotation based on UniProtKB/Swiss-Prot Subcellular Location vocabulary mapping, accompanied by conservative changes to GO terms applied by UniProt",
    "findings": [],
}
GO_REF_TRANSFER = {
    "id": "GO_REF:0000104",
    "title": "Electronic Gene Ontology annotations created by transferring manual GO annotations between related proteins based on shared sequence features",
    "findings": [],
}
GO_REF_TREEGRAFTER = {
    "id": "GO_REF:0000118",
    "title": "TreeGrafter-generated GO annotations",
    "findings": [],
}
GO_REF_COMBINED = {
    "id": "GO_REF:0000120",
    "title": "Combined Automated Annotation using Multiple IEA Methods",
    "findings": [],
}


PMID_SWITCH = {
    "id": "PMID:31452860",
    "title": "Directional Switching Mechanism of the Bacterial Flagellar Motor.",
    "findings": [
        {
            "statement": "FliG, FliM, and FliN form the C-ring rotor/switch complex.",
            "supporting_text": "FliG, FliM and FliN form the C ring on the cytoplasmic face of the basal body MS ring made of the transmembrane protein FliF and act as the rotor.",
        },
        {
            "statement": "CheY-P controls motor switching through FliM and FliN.",
            "supporting_text": "The phosphorylated form of CheY (CheY-P), which serves as a signaling molecule, binds to FliM and FliN in the C ring to switch the direction of flagellar motor rotation from CCW to CW.",
        },
    ],
}
PMID_STATOR = {
    "id": "PMID:35572622",
    "title": "The Periplasmic Domain of the Ion-Conducting Stator of Bacterial Flagella Regulates Force Generation.",
    "findings": [
        {
            "statement": "Flagellar stators couple ion influx to rotational force.",
            "supporting_text": "movement of the stator that is coupled to ion influx through the ion channel of the stator generates the rotational force (torque)",
        },
        {
            "statement": "FliL is a flagellar-base component near the stator.",
            "supporting_text": "FliL is located at the flagellar base close to the stator.",
        },
    ],
}
PMID_PUTIDA_STATORS = {
    "id": "PMID:36409076",
    "title": "Role of the Two Flagellar Stators in Swimming Motility of Pseudomonas putida.",
    "findings": [
        {
            "statement": "P. putida has MotAB and MotCD stators.",
            "supporting_text": "In the soil bacterium Pseudomonas putida, the motor torque for flagellar rotation is generated by the two stators MotAB and MotCD.",
        },
        {
            "statement": "PP_4336 and PP_4335 encode the MotCD stator in the main flagellar cluster.",
            "supporting_text": "P. putida has a large gene cluster for flagellar motility comprising the genes for the stator MotCD (PP4336 and PP4335).",
        },
    ],
}


def uniprot_ref(gene: str, accession: str, title: str, findings: list[dict]) -> dict:
    return {
        "id": f"file:PSEPK/{gene}/{gene}-uniprot.txt",
        "title": f"UniProtKB entry {accession} for Pseudomonas putida KT2440 {title}",
        "findings": findings,
    }


def goa_ref(gene: str) -> dict:
    return {
        "id": f"file:PSEPK/{gene}/{gene}-goa.tsv",
        "title": f"QuickGO GOA annotations for {gene}",
        "findings": [
            {
                "statement": f"The fetched GOA table contains the automated annotations reviewed for {gene}."
            }
        ],
    }


def asta_ref(gene: str) -> dict:
    return {
        "id": f"file:PSEPK/{gene}/{gene}-deep-research-asta.md",
        "title": f"Asta retrieval report for {gene} in Pseudomonas putida KT2440",
        "findings": [
            {
                "statement": "Asta retrieval was checked; it did not identify curation-changing organism-specific literature beyond the UniProt, GOA, and cached flagellar-motor literature used in this first pass."
            }
        ],
    }


def write_review(
    gene: str,
    description: str,
    references: list[dict],
    reviews: dict[str, dict],
    core_functions: list[dict],
    questions: list[str],
    experiments: list[str],
    aliases: list[str] | None = None,
) -> None:
    path = GENE_ROOT / gene / f"{gene}-ai-review.yaml"
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    data["status"] = "DRAFT"
    data["gene_symbol"] = gene
    if aliases:
        data["aliases"] = aliases
    data["description"] = description
    for annotation in data["existing_annotations"]:
        annotation["review"] = reviews[annotation["term"]["id"]]
    data["references"] = references
    data["core_functions"] = core_functions
    data["proposed_new_terms"] = []
    data["suggested_questions"] = [{"question": question} for question in questions]
    data["suggested_experiments"] = [{"description": experiment} for experiment in experiments]
    path.write_text(
        yaml.dump(data, Dumper=NoAliasDumper, sort_keys=False, allow_unicode=False, width=88),
        encoding="utf-8",
    )
    print(f"Curated {path.relative_to(ROOT)}")


def curate_pp4335() -> None:
    gene = "PP_4335"
    uni = f"file:PSEPK/{gene}/{gene}-uniprot.txt"
    goa = f"file:PSEPK/{gene}/{gene}-goa.tsv"
    references = [
        GO_REF_SUBCELL,
        GO_REF_TRANSFER,
        uniprot_ref(
            gene,
            "Q88EW7",
            "PP_4335",
            [
                {
                    "statement": "PP_4335 is a MotB-family, single-pass membrane flagellar motor protein.",
                    "supporting_text": "SubName: Full=Flagellar motor protein",
                },
                {
                    "statement": "The protein carries MotB-like and OmpA-like domain evidence.",
                    "supporting_text": "DR   Pfam; PF13677; MotB_plug; 1.",
                },
                {
                    "statement": "PANTHER classifies PP_4335 as a stator element of the flagellar motor complex.",
                    "supporting_text": "PANTHER; PTHR30329; STATOR ELEMENT OF FLAGELLAR MOTOR COMPLEX; 1.",
                },
            ],
        ),
        goa_ref(gene),
        asta_ref(gene),
        PMID_STATOR,
        PMID_PUTIDA_STATORS,
    ]
    reviews = {
        "GO:0005886": review(
            "Plasma membrane is correct for this single-pass MotB-like stator subunit, but the core biological context is the flagellar stator rather than generic membrane residence.",
            "KEEP_AS_NON_CORE",
            "PP_4335 is inferred to be the B-like subunit of the MotCD stator in the main P. putida flagellar cluster. Plasma membrane is accurate as a cellular location, while the more informative synthesis is stator-complex anchoring and flagellum-dependent motility.",
            [
                ref(uni, "CC   -!- SUBCELLULAR LOCATION: Cell membrane"),
                ref(uni, "CC       Single-pass membrane protein"),
                ref(uni, "PANTHER; PTHR30329; STATOR ELEMENT OF FLAGELLAR MOTOR COMPLEX; 1."),
                ref("PMID:36409076", "P. putida has a large gene cluster for flagellar motility comprising the genes for the stator MotCD (PP4336 and PP4335)."),
            ],
        ),
        "GO:0016020": review(
            "The broad membrane annotation is true but uninformative for a MotB-like flagellar stator subunit.",
            "REMOVE",
            "A generic membrane term is redundant with the more specific plasma-membrane and stator-complex interpretation. It should not be treated as a core annotation for a well-classified MotB-family protein.",
            [
                ref(goa, "GO:0016020\tmembrane"),
                ref(uni, "DR   Pfam; PF00691; OmpA; 1."),
                ref(uni, "PANTHER; PTHR30329; STATOR ELEMENT OF FLAGELLAR MOTOR COMPLEX; 1."),
            ],
        ),
    }
    core_functions = [
        {
            "description": "PP_4335 is the MotB-like B subunit candidate of the MotCD stator encoded in the main flagellar cluster. Its single transmembrane segment and periplasmic OmpA-like/MotB-plug region support a peptidoglycan-anchoring stator role coupled to ion-driven flagellar rotation.",
            "molecular_function": term("GO:0042834", "peptidoglycan binding"),
            "contributes_to_molecular_function": term(
                "GO:0015078", "proton transmembrane transporter activity"
            ),
            "directly_involved_in": [
                term("GO:0071973", "bacterial-type flagellum-dependent cell motility")
            ],
            "locations": [term("GO:0005886", "plasma membrane")],
            "in_complex": term("GO:0120101", "bacterial-type flagellum stator complex"),
            "supported_by": [
                ref("PMID:36409076", "P. putida has a large gene cluster for flagellar motility comprising the genes for the stator MotCD (PP4336 and PP4335)."),
                ref(uni, "CC   -!- SIMILARITY: Belongs to the MotB family."),
                ref(uni, "DR   Pfam; PF13677; MotB_plug; 1."),
                ref(uni, "DR   Pfam; PF00691; OmpA; 1."),
                ref("PMID:35572622", "The periplasmic region of MotB/PomB contains a structurally conserved OmpA-like domain that is known to bind to the PG layer"),
            ],
        }
    ]
    write_review(
        gene,
        "PP_4335 encodes the MotB-like B subunit candidate of the MotCD flagellar stator in Pseudomonas putida KT2440. The protein is a single-pass membrane protein with MotB-plug and OmpA-like periplasmic-domain signatures, consistent with a role in anchoring the MotCD stator to the cell wall while ion flow through the stator powers flagellar rotation. It is distinct from the second MotAB stator encoded by motA/motB outside the main flagellar cluster.",
        references,
        reviews,
        core_functions,
        [
            "Under which viscosity or agar conditions does PP_4335/MotD contribute most strongly to KT2440 motility relative to the MotAB stator?",
            "Does PP_4335 directly bind peptidoglycan and the PP_4336 MotA-like partner in the same manner as canonical MotB-family stator B subunits?",
        ],
        [
            "Construct PP_4335, PP_4336, motAB, and combined stator deletions with complementation, then quantify swimming, wrapped-mode formation, and agar spreading.",
            "Test the predicted OmpA-like periplasmic domain for peptidoglycan binding and stator anchoring by domain mutagenesis and localization assays.",
        ],
        aliases=["motD"],
    )


def curate_pp4336() -> None:
    gene = "PP_4336"
    uni = f"file:PSEPK/{gene}/{gene}-uniprot.txt"
    goa = f"file:PSEPK/{gene}/{gene}-goa.tsv"
    references = [
        GO_REF_INTERPRO,
        GO_REF_SUBCELL,
        GO_REF_COMBINED,
        uniprot_ref(
            gene,
            "Q88EW6",
            "PP_4336",
            [
                {
                    "statement": "PP_4336 is a MotA-like multi-pass flagellar motor rotation protein.",
                    "supporting_text": "SubName: Full=Flagellar motor rotation protein",
                },
                {
                    "statement": "The protein carries MotA/ExbB proton-channel domain evidence.",
                    "supporting_text": "FT                   /note=\"MotA/TolQ/ExbB proton channel\"",
                },
                {
                    "statement": "PANTHER classifies PP_4336 with MotA-like chemotaxis/motility proteins.",
                    "supporting_text": "PANTHER; PTHR30433; CHEMOTAXIS PROTEIN MOTA; 1.",
                },
            ],
        ),
        goa_ref(gene),
        asta_ref(gene),
        PMID_STATOR,
        PMID_PUTIDA_STATORS,
    ]
    reviews = {
        "GO:0005886": review(
            "Plasma membrane is the appropriate location for this MotA-like multi-pass stator A subunit candidate.",
            "ACCEPT",
            "PP_4336 is a multi-pass MotA-like component of the MotCD stator. The inner/plasma membrane is where the stator conducts ions and contacts the rotor.",
            [
                ref(uni, "CC   -!- SUBCELLULAR LOCATION: Cell membrane"),
                ref(uni, "CC       Multi-pass membrane protein"),
                ref(uni, "DR   InterPro; IPR047055; MotA-like."),
                ref("PMID:36409076", "P. putida has a large gene cluster for flagellar motility comprising the genes for the stator MotCD (PP4336 and PP4335)."),
            ],
        ),
        "GO:0006935": review(
            "Chemotaxis is biologically downstream of stator-dependent flagellar motility, but PP_4336 is not a chemotaxis signaling protein.",
            "MARK_AS_OVER_ANNOTATED",
            "The direct role is MotCD stator function in flagellar rotation and motility. Chemotaxis behavior depends on motor output, but the PP_4336 product is a motor/stator component rather than a receptor, Che protein, or adaptation enzyme.",
            [
                ref(uni, "SubName: Full=Flagellar motor rotation protein"),
                ref(goa, "GO:0006935\tchemotaxis"),
                ref("PMID:36409076", "In the soil bacterium Pseudomonas putida, the motor torque for flagellar rotation is generated by the two stators MotAB and MotCD."),
            ],
        ),
        "GO:0016020": review(
            "Membrane is true but too generic for a MotA-like stator protein.",
            "REMOVE",
            "The fetched plasma-membrane location and stator-complex synthesis are more informative; the generic membrane term is redundant and should not be treated as core.",
            [
                ref(goa, "GO:0016020\tmembrane"),
                ref(uni, "DR   InterPro; IPR002898; MotA_ExbB_proton_chnl."),
            ],
        ),
        "GO:0071978": review(
            "Swarming motility is too specific for the available PP_4336 evidence.",
            "MARK_AS_OVER_ANNOTATED",
            "PP_4336/MotC contributes to flagellar stator function and thus flagellum-dependent cell motility, but swarming is a specialized surface behavior. The P. putida stator study explicitly distinguishes liquid swimming and agar spreading and notes that P. putida does not swarm in a flagella-dependent manner.",
            [
                ref(goa, "GO:0071978\tbacterial-type flagellum-dependent swarming motility"),
                ref("PMID:36409076", "However, P. putida does not swarm in a flagella-dependent manner"),
                ref("PMID:36409076", "The MotAB stator is essential for swimming motility in liquids, while spreading in semisolid agar is not affected."),
            ],
        ),
    }
    core_functions = [
        {
            "description": "PP_4336 is the MotA-like A subunit candidate of the MotCD stator in the main flagellar cluster. As a multi-pass membrane protein with MotA/ExbB proton-channel domains, it is inferred to contribute to ion translocation and rotor-stator torque generation for bacterial-type flagellum-dependent motility.",
            "contributes_to_molecular_function": term(
                "GO:0015078", "proton transmembrane transporter activity"
            ),
            "directly_involved_in": [
                term("GO:0071973", "bacterial-type flagellum-dependent cell motility")
            ],
            "locations": [term("GO:0005886", "plasma membrane")],
            "in_complex": term("GO:0120101", "bacterial-type flagellum stator complex"),
            "supported_by": [
                ref("PMID:36409076", "P. putida has a large gene cluster for flagellar motility comprising the genes for the stator MotCD (PP4336 and PP4335)."),
                ref(uni, "DR   InterPro; IPR047055; MotA-like."),
                ref(uni, "FT                   /note=\"MotA/TolQ/ExbB proton channel\""),
                ref("PMID:35572622", "movement of the stator that is coupled to ion influx through the ion channel of the stator generates the rotational force (torque)"),
            ],
        }
    ]
    write_review(
        gene,
        "PP_4336 encodes the MotA-like A subunit candidate of the MotCD flagellar stator in Pseudomonas putida KT2440. It is a multi-pass inner-membrane protein with MotA/ExbB proton-channel domains and is paired in the main flagellar cluster with the MotB-like PP_4335 protein. The inferred role is ion-coupled stator function for flagellar rotation and motility, distinct from the MotAB stator encoded by motA/motB elsewhere in the genome.",
        references,
        reviews,
        core_functions,
        [
            "Does PP_4336/MotC assemble with PP_4335/MotD in the same motor as MotA/MotB, or are the two stators recruited under different load conditions?",
            "Which conserved charged residues in PP_4336 mediate rotor contact with FliG and ion-coupled torque generation?",
        ],
        [
            "Tag PP_4336 and MotA at native loci to measure stator recruitment during liquid swimming, high-viscosity swimming, and agar migration.",
            "Mutate conserved MotA/ExbB-channel residues in PP_4336 and test effects on motor rotation, motility, and complementation of a PP_4336 deletion.",
        ],
        aliases=["motC"],
    )


def switch_reviews(gene: str, accession: str, product: str, family_text: str) -> None:
    uni = f"file:PSEPK/{gene}/{gene}-uniprot.txt"
    goa = f"file:PSEPK/{gene}/{gene}-goa.tsv"
    references = [
        GO_REF_INTERPRO,
        GO_REF_SUBCELL,
        GO_REF_TRANSFER,
        GO_REF_TREEGRAFTER,
        GO_REF_COMBINED,
        uniprot_ref(
            gene,
            accession,
            gene,
            [
                {
                    "statement": f"UniProt identifies {gene} as a flagellar motor switch protein.",
                    "supporting_text": product,
                },
                {
                    "statement": "UniProt describes FliG/FliM/FliN as the rotor-mounted switch complex at the basal body.",
                    "supporting_text": "rotor-mounted switch complex (C ring), located at the base of the basal body",
                },
                {
                    "statement": f"The protein carries family/domain evidence consistent with {gene} switch-complex function.",
                    "supporting_text": family_text,
                },
            ],
        ),
        goa_ref(gene),
        asta_ref(gene),
        PMID_SWITCH,
    ]
    replacement_chemotaxis = [term("GO:0006935", "chemotaxis")]
    replacement_motility = [
        term("GO:0071973", "bacterial-type flagellum-dependent cell motility")
    ]
    reviews = {
        "GO:0003774": review(
            "The molecular-function call is appropriate as a motor-complex annotation for a C-ring switch/rotor component.",
            "ACCEPT",
            f"{gene} is part of the FliG/FliM/FliN C-ring rotor-mounted switch complex. It is not an independent motor enzyme, but the GOA/UniProt-family call is reasonable for the motor complex component that controls flagellar rotation.",
            [
                ref(uni, "DR   GO; GO:0003774; F:cytoskeletal motor activity"),
                ref(uni, "rotor-mounted switch complex (C ring), located at the base of the basal body"),
                ref("PMID:31452860", "FliG, FliM and FliN form the C ring on the cytoplasmic face of the basal body MS ring made of the transmembrane protein FliF and act as the rotor."),
            ],
        ),
        "GO:0005886": review(
            "Plasma membrane is accurate but generic for a peripheral C-ring/basal-body component.",
            "KEEP_AS_NON_CORE",
            "FliM/FliN-family switch proteins associate with the cytoplasmic side of the basal body at the inner membrane. The more specific core localization is bacterial-type flagellum basal body.",
            [
                ref(uni, "DR   GO; GO:0005886; C:plasma membrane; IEA:UniProtKB-SubCell."),
                ref(uni, "Bacterial flagellum basal body"),
            ],
        ),
        "GO:0009288": review(
            "Bacterial-type flagellum is correct for a C-ring switch component.",
            "ACCEPT",
            "The term is broader than basal body but still accurate because the C-ring is part of the bacterial flagellar motor apparatus.",
            [
                ref(goa, "GO:0009288\tbacterial-type flagellum"),
                ref("PMID:31452860", "The C ring is composed of FliG, FliM and FliN."),
            ],
        ),
        "GO:0009425": review(
            "Bacterial-type flagellum basal body is the most informative cellular-component annotation for this switch protein.",
            "ACCEPT",
            "The FliG/FliM/FliN C-ring is located at the base of the flagellar basal body, so this is a core localization.",
            [
                ref(uni, "DR   GO; GO:0009425; C:bacterial-type flagellum basal body"),
                ref(uni, "rotor-mounted switch complex (C ring), located at the base of the basal body"),
            ],
        ),
        "GO:0016020": review(
            "The generic membrane term is redundant and less informative than basal-body localization.",
            "REMOVE",
            "For a peripheral C-ring switch protein, the broad membrane annotation is an over-propagated location. Bacterial-type flagellum basal body is the relevant cellular component.",
            [
                ref(goa, "GO:0016020\tmembrane"),
                ref(uni, "Bacterial flagellum basal body"),
            ],
        ),
        "GO:0006935": review(
            "Chemotaxis is a valid higher-level process because CheY-P controls rotation direction through the C-ring switch.",
            "KEEP_AS_NON_CORE",
            "The direct role is flagellar motor switching and flagellum-dependent motility; chemotaxis is the upstream behavioral pathway served by this switch output.",
            [
                ref(uni, "This complex interacts with the CheY and CheZ chemotaxis proteins"),
                ref("PMID:31452860", "The phosphorylated form of CheY (CheY-P), which serves as a signaling molecule, binds to FliM and FliN in the C ring to switch the direction of flagellar motor rotation from CCW to CW."),
            ],
        ),
        "GO:0050918": review(
            "Positive chemotaxis is too direction-specific for this switch-complex subunit.",
            "MODIFY",
            "FliM-family switch proteins participate in chemotactic motor control, but this evidence does not establish a specific positive-chemotaxis role. Use chemotaxis for the behavioral process and flagellum-dependent cell motility for the direct motor process.",
            [
                ref(goa, "GO:0050918\tpositive chemotaxis"),
                ref("PMID:31452860", "The phosphorylated form of CheY (CheY-P), which serves as a signaling molecule, binds to FliM and FliN in the C ring to switch the direction of flagellar motor rotation from CCW to CW."),
            ],
            replacement_chemotaxis,
        ),
        "GO:0071973": review(
            "Flagellum-dependent cell motility is the direct biological process for a C-ring switch component.",
            "ACCEPT",
            "The FliG/FliM/FliN switch complex controls rotation direction of the flagellar motor and therefore directly contributes to bacterial-type flagellum-dependent motility.",
            [
                ref(uni, "determine the direction of flagellar rotation"),
                ref("PMID:31452860", "The C ring also serves as a switching device that enables the motor to spin in both counterclockwise (CCW) and clockwise (CW) directions."),
            ],
        ),
        "GO:0071978": review(
            "Swarming motility is too specific for the available switch-complex evidence.",
            "MARK_AS_OVER_ANNOTATED",
            "A switch protein is required for flagellum-dependent motility in general, but the GOA row does not supply gene-specific evidence for the specialized swarming behavior. The direct process term is bacterial-type flagellum-dependent cell motility.",
            [
                ref(goa, "GO:0071978\tbacterial-type flagellum-dependent swarming motility"),
                ref("PMID:31452860", "The C ring also serves as a switching device that enables the motor to spin in both counterclockwise (CCW) and clockwise (CW) directions."),
            ],
            replacement_motility,
        ),
    }
    data_reviews: dict[str, dict]
    if gene == "fliN":
        data_reviews = {
            "GO:0003774": reviews["GO:0003774"],
            "GO:0005886": reviews["GO:0005886"],
            "GO:0006935": reviews["GO:0006935"],
            "GO:0009288": reviews["GO:0009288"],
            "GO:0009425": reviews["GO:0009425"],
            "GO:0016020": reviews["GO:0016020"],
            "GO:0071973": reviews["GO:0071973"],
        }
    else:
        data_reviews = {
            "GO:0003774": reviews["GO:0003774"],
            "GO:0005886": reviews["GO:0005886"],
            "GO:0009288": reviews["GO:0009288"],
            "GO:0009425": reviews["GO:0009425"],
            "GO:0050918": reviews["GO:0050918"],
            "GO:0071973": reviews["GO:0071973"],
            "GO:0071978": reviews["GO:0071978"],
        }
    core_functions = [
        {
            "description": f"{gene} is a C-ring switch/rotor component of the bacterial flagellar motor. Together with the other FliG/FliM/FliN proteins it forms the rotor-mounted switch complex at the basal body, receives chemotaxis-output control through CheY-P-dependent C-ring remodeling, and controls flagellar rotation direction for motility.",
            "contributes_to_molecular_function": term("GO:0003774", "cytoskeletal motor activity"),
            "directly_involved_in": [
                term("GO:0071973", "bacterial-type flagellum-dependent cell motility"),
            ],
            "locations": [term("GO:0009425", "bacterial-type flagellum basal body")],
            "supported_by": [
                ref(uni, product),
                ref(uni, "rotor-mounted switch complex (C ring), located at the base of the basal body"),
                ref(uni, family_text),
                ref("PMID:31452860", "FliG, FliM and FliN form the C ring on the cytoplasmic face of the basal body MS ring made of the transmembrane protein FliF and act as the rotor."),
                ref("PMID:31452860", "The phosphorylated form of CheY (CheY-P), which serves as a signaling molecule, binds to FliM and FliN in the C ring to switch the direction of flagellar motor rotation from CCW to CW."),
            ],
        }
    ]
    write_review(
        gene,
        f"{gene} encodes a flagellar motor switch protein in Pseudomonas putida KT2440. The protein is part of the conserved FliG/FliM/FliN C-ring switch complex at the cytoplasmic face of the flagellar basal body. Its primary role is in flagellar motor switching and flagellum-dependent motility, with chemotaxis represented as the upstream behavioral signaling context rather than an independent enzymatic activity.",
        references,
        data_reviews,
        core_functions,
        [
            f"How does {gene} interact with the other KT2440 C-ring components and with CheY-P during switching?",
            f"Does {gene} contribute to differential MotAB versus MotCD stator usage under high-load or agar conditions?",
        ],
        [
            f"Construct a {gene} deletion and chromosomal complementation strain, then assay swimming trajectories, rotation-direction bias, and flagellation.",
            f"Use bacterial two-hybrid or pull-down assays to test {gene} interactions with FliG/FliM/FliN partners, CheY, and FliH where relevant.",
        ],
    )


def flil_reviews(gene: str, accession: str, named: bool) -> None:
    uni = f"file:PSEPK/{gene}/{gene}-uniprot.txt"
    goa = f"file:PSEPK/{gene}/{gene}-goa.tsv"
    references = [
        GO_REF_INTERPRO,
        GO_REF_SUBCELL,
        GO_REF_TREEGRAFTER,
        uniprot_ref(
            gene,
            accession,
            gene,
            [
                {
                    "statement": f"UniProt identifies {gene} as a FliL-family flagellar protein.",
                    "supporting_text": "RecName: Full=Flagellar protein FliL",
                },
                {
                    "statement": "The protein is predicted as a single-pass membrane protein.",
                    "supporting_text": "Single-pass membrane protein",
                },
                {
                    "statement": "The protein carries FliL-family domain evidence.",
                    "supporting_text": "DR   Pfam; PF03748; FliL; 1.",
                },
            ],
        ),
        goa_ref(gene),
        asta_ref(gene),
        PMID_STATOR,
    ]
    reviews = {
        "GO:0005886": review(
            "Plasma membrane is appropriate for this single-pass FliL-family protein.",
            "ACCEPT",
            "FliL proteins are membrane-associated flagellar-base components. The plasma/inner-membrane localization is a correct location for this gene product.",
            [
                ref(uni, "CC   -!- SUBCELLULAR LOCATION: Cell inner membrane"),
                ref(uni, "Single-pass membrane protein"),
                ref("PMID:35572622", "FliL is located at the flagellar base close to the stator."),
            ],
        ),
        "GO:0006935": review(
            "Chemotaxis is a plausible higher-level context but should not be treated as the primary function of FliL.",
            "KEEP_AS_NON_CORE",
            "The direct first-pass role is flagellar-base/stator-associated motor function for motility. Chemotaxis is retained as a downstream behavior affected by motor switching rather than as a Che-signaling activity.",
            [
                ref(uni, "Controls the rotational direction of flagella during"),
                ref(goa, "GO:0006935\tchemotaxis"),
            ],
        ),
        "GO:0009425": review(
            "Bacterial-type flagellum basal body is the most informative location for this FliL-family protein.",
            "ACCEPT",
            "FliL-family proteins localize at the flagellar base close to stator components, matching the basal-body annotation.",
            [
                ref(uni, "DR   GO; GO:0009425; C:bacterial-type flagellum basal body"),
                ref("PMID:35572622", "FliL is located at the flagellar base close to the stator."),
            ],
        ),
        "GO:0071973": review(
            "Flagellum-dependent cell motility is an appropriate process annotation for a FliL-family motor-associated protein.",
            "ACCEPT",
            "FliL is a flagellar-base protein implicated in stabilizing active stator function, so a role in flagellum-dependent motility is biologically appropriate even though the precise KT2440 paralog-specific contribution remains unresolved.",
            [
                ref(goa, "GO:0071973\tbacterial-type flagellum-dependent cell motility"),
                ref("PMID:35572622", "FliL is another component that stabilizes the active stator."),
                ref(uni, "DR   InterPro; IPR005503; FliL."),
            ],
        ),
        "GO:0071978": review(
            "Swarming motility is too specific for the current FliL-family evidence.",
            "MARK_AS_OVER_ANNOTATED",
            "The available evidence supports a flagellar motor/base role and general flagellum-dependent motility. It does not establish a paralog-specific swarming function in KT2440.",
            [
                ref(goa, "GO:0071978\tbacterial-type flagellum-dependent swarming motility"),
                ref("PMID:35572622", "When FliL is not present, motility is impaired when the cells swim or swarm in a highly viscous environment."),
            ],
            [term("GO:0071973", "bacterial-type flagellum-dependent cell motility")],
        ),
    }
    core_functions = [
        {
            "description": f"{gene} is a FliL-family single-pass membrane protein associated with the flagellar basal body. The first-pass interpretation is a motor-associated/stator-stabilizing role that supports bacterial-type flagellum-dependent motility, while exact paralog-specific requirements in KT2440 remain unresolved.",
            "directly_involved_in": [
                term("GO:0071973", "bacterial-type flagellum-dependent cell motility")
            ],
            "locations": [
                term("GO:0009425", "bacterial-type flagellum basal body"),
                term("GO:0005886", "plasma membrane"),
            ],
            "supported_by": [
                ref(uni, "RecName: Full=Flagellar protein FliL"),
                ref(uni, "DR   Pfam; PF03748; FliL; 1."),
                ref(uni, "Single-pass membrane protein"),
                ref("PMID:35572622", "FliL is located at the flagellar base close to the stator."),
                ref("PMID:35572622", "FliL is another component that stabilizes the active stator."),
            ],
        }
    ]
    display = "fliL" if named else "PP_5209"
    write_review(
        gene,
        f"{display} encodes a FliL-family flagellar motor-associated protein in Pseudomonas putida KT2440. The protein is predicted to be a small single-pass membrane protein at the flagellar basal body. Its most conservative first-pass role is support of flagellum-dependent motility, likely through a motor/base or stator-stabilizing function, while the specific division of labor between the two KT2440 FliL-family paralogs remains unresolved.",
        references,
        reviews,
        core_functions,
        [
            f"Does {display} act with MotAB, MotCD, or both stator systems in KT2440?",
            f"Is {display} required only under high-load or surface/agar conditions, or also during low-viscosity swimming?",
        ],
        [
            f"Delete {gene} alone and in combination with the other FliL-family paralog, then compare swimming, wrapped-mode formation, and agar migration.",
            f"Measure localization of tagged {display} relative to MotAB/MotCD stator markers and basal-body proteins under different mechanical loads.",
        ],
    )


def main() -> None:
    curate_pp4335()
    curate_pp4336()
    switch_reviews(
        "fliN",
        "Q88EU6",
        "RecName: Full=Flagellar motor switch protein FliN",
        "DR   InterPro; IPR051469; FliN/MopA/SpaO.",
    )
    switch_reviews(
        "fliM",
        "Q88EU5",
        "RecName: Full=Flagellar motor switch protein FliM",
        "DR   InterPro; IPR001689; Flag_FliM.",
    )
    flil_reviews("fliL", "Q88EU4", named=True)
    flil_reviews("PP_5209", "Q88CH2", named=False)


if __name__ == "__main__":
    main()
