all:
    uv run --script analyze.py --target ../CG34171-uniprot-source.json --references ../CG34171-reference-A8DZ15-uniprot.json ../CG34171-reference-P00760-uniprot.json ../CG34171-reference-Q66TN7-uniprot.json --output . > run.txt
