default: analyze control

analyze:
    python analyze.py --hmm inputs/PF00089.hmm --target inputs/A0A0B4K7P3.fasta --reference inputs/P00760.json --reference inputs/Q90WD8.json --output results

control:
    python analyze.py --hmm inputs/PF00089.hmm --target inputs/P00760.fasta --reference inputs/Q90WD8.json --output control-results

refresh:
    python fetch_inputs.py
