default: human archaeal control
human:
    uv run --no-project --with biopython==1.85 python compare.py ../CG5565-uniprot-source.json ../CG5565-donor-Q08623-uniprot.json human
archaeal:
    uv run --no-project --with biopython==1.85 python compare.py ../CG5565-uniprot-source.json ../CG5565-donor-Q9V1B3-uniprot.json archaeal
control:
    uv run --no-project --with biopython==1.85 python compare.py ../CG5565-donor-Q08623-uniprot.json ../CG5565-donor-Q08623-uniprot.json control
