"""Verify every locally-sourced quote in the ARHGAP23 review is really in the file it cites.

CI's reference validator checks ``supporting_text`` verbatim only for ``PMID:`` references.
Quotes attached to ``file:`` references - including quotes from this folder's own RESULTS.md
and from the deep-research record - and quotes attached to ``Reactome:`` references are not
checked by anything, which is exactly the surface on which fabricated quotes have survived
review elsewhere in this repo.

This script closes that hole for this gene. It collects every quote whose source is a local
file, in both of the places the schema puts them:

  * ``...supported_by[].{reference_id, supporting_text}`` - annotation and core-function support;
  * ``references[].findings[].supporting_text`` - where the id lives on the parent entry.

``file:`` ids resolve under ``genes/``; ``Reactome:`` ids resolve to ``reactome/<id>.md``. Each
quote must be a substring of its source after whitespace is collapsed - the same normalisation
the upstream validator applies - so a quote that has merely been rewrapped still passes while an
invented one does not.

It is committed rather than kept in a scratchpad because a check that does not re-run goes stale
silently: RESULTS.md is regenerated by analyze_arhgap23.py, so a wording change in the report can
orphan a quote in the review without any other signal.

``--self-test`` fabricates a quote and asserts the checker rejects it, and re-wraps a real quote
and asserts the checker still accepts it, so a pass here is evidence the check can fail.

Usage:
    uv run python check_file_quotes.py
    uv run python check_file_quotes.py --self-test
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys
from typing import Any

import yaml

SCRIPT_DIR = pathlib.Path(__file__).resolve().parent
REPO = SCRIPT_DIR.parents[3]
REVIEW = SCRIPT_DIR.parent / "ARHGAP23-ai-review.yaml"

LOCAL_PREFIXES = ("file:", "Reactome:")


def collapse(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def resolve(ref: str) -> pathlib.Path | None:
    if ref.startswith("file:"):
        return REPO / "genes" / ref[len("file:") :]
    if ref.startswith("Reactome:"):
        return REPO / "reactome" / f"{ref[len('Reactome:') :]}.md"
    return None


def collect(node: Any, path: str = "") -> list[tuple[str, str, str]]:
    """Every (yaml_path, reference_id, supporting_text) with a locally-resolvable source."""
    out: list[tuple[str, str, str]] = []
    if isinstance(node, dict):
        ref, txt = node.get("reference_id"), node.get("supporting_text")
        if isinstance(ref, str) and ref.startswith(LOCAL_PREFIXES) and isinstance(txt, str):
            out.append((path, ref, txt))
        # references[] entries carry the id on the parent and the quotes on findings[]
        rid = node.get("id")
        if isinstance(rid, str) and rid.startswith(LOCAL_PREFIXES):
            for i, finding in enumerate(node.get("findings") or []):
                ftxt = finding.get("supporting_text") if isinstance(finding, dict) else None
                if isinstance(ftxt, str):
                    out.append((f"{path}.findings[{i}]", rid, ftxt))
        for k, v in node.items():
            if k == "findings" and isinstance(rid, str) and rid.startswith(LOCAL_PREFIXES):
                continue  # already handled above, do not double-count
            out.extend(collect(v, f"{path}.{k}"))
    elif isinstance(node, list):
        for i, v in enumerate(node):
            out.extend(collect(v, f"{path}[{i}]"))
    return out


def check(citations: list[tuple[str, str, str]], verbose: bool = True) -> int:
    cache: dict[str, str | None] = {}
    failures = 0
    for where, ref, quote in citations:
        if ref not in cache:
            target = resolve(ref)
            if target is None or not target.exists():
                print(f"MISSING FILE  {where}\n    {ref} -> {target}")
                failures += 1
                cache[ref] = None
                continue
            cache[ref] = collapse(target.read_text())
        content = cache[ref]
        if content is None:
            failures += 1
            continue
        if collapse(quote) in content:
            if verbose:
                print(f"ok    {ref}  {collapse(quote)[:64]!r}")
        else:
            print(f"FAIL  {where}\n    source: {ref}\n    quote:  {collapse(quote)!r}")
            failures += 1
    return failures


def load() -> list[tuple[str, str, str]]:
    if not REVIEW.exists():
        raise SystemExit(f"ERROR: {REVIEW} not found")
    citations = collect(yaml.safe_load(REVIEW.read_text()))
    if not citations:
        raise SystemExit(
            "ERROR: no locally-sourced quotes found in the review. Either the review stopped "
            "citing local files, in which case delete this check, or the YAML structure changed "
            "and this check has gone blind."
        )
    return citations


def self_test() -> int:
    citations = load()
    baseline = check(citations, verbose=False)
    assert baseline == 0, f"baseline is not clean ({baseline} failures); fix those first"

    where, ref, quote = citations[0]
    fabricated = [(where, ref, quote + " and it also cures scurvy")]
    got = check(fabricated, verbose=False)
    assert got == 1, "a fabricated quote was accepted; this check is not checking anything"

    rewrapped = [(where, ref, re.sub(r" ", "\n   ", collapse(quote)))]
    got = check(rewrapped, verbose=False)
    assert got == 0, "a merely rewrapped real quote was rejected; the check is too strict"

    missing = [("test", "file:human/ARHGAP23/no-such-file.md", "anything")]
    got = check(missing, verbose=False)
    assert got == 1, "a citation to a non-existent file was accepted"

    print(
        f"self-test OK: {len(citations)} real quotes clean, fabrication rejected, "
        "rewrapping accepted, missing file rejected"
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args(argv)
    if args.self_test:
        return self_test()
    citations = load()
    failures = check(citations)
    print(f"\n{len(citations)} locally-sourced quote(s) checked, {failures} failure(s)")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
