"""Per-row manual decisions for the 163 membrane dossiers (index = position in dossiers.yaml).

Written by a reviewer after reading each dossier (UniProt location/function text, leads,
current review) and, where a lead was decisive, the cached source. This file is the
review record; make_decisions.py turns it into decisions.yaml. Nothing here is computed.

Decision basis, applied per protein (not mechanically):
  KEEP_AS_NON_CORE  the protein has documented, protein-specific membrane association
                    (an experimental UniProt membrane location, or an experimental
                    membrane annotation whose source supports it); `membrane` is true
                    but generic, and the specific membrane term carries the location.
  MARK_AS_OVER_ANNOTATED  no protein-specific evidence of stable membrane association;
                    a soluble cytosolic/nuclear/matrix/lumenal protein recovered from a
                    membrane preparation that its authors say was largely non-integral.
  ACCEPT            kept only where membrane association is itself the core of the
                    protein's activity and no more specific membrane term carries it.
  REMOVE            earlier REMOVE calls are confirmed where the protein has no credible
                    membrane association (they are defensible; not churned to OVER).
"""

D = {
    0: ("KEEP_AS_NON_CORE", "UniProt: cell inner membrane, peripheral membrane protein (ECO:0000269, PubMed:16079137)."),
    1: ("MARK_AS_OVER_ANNOTATED", "UniProt places GroEL in the cytoplasm only (ECO:0000269); no protein-specific evidence of membrane association was found. A soluble chaperonin recovered in a complexome membrane fraction."),
    2: ("MARK_AS_OVER_ANNOTATED", "UniProt: cytoplasm only; RidA is a small soluble enamine/imine deaminase with no reported membrane association."),
    3: ("KEEP_AS_NON_CORE", "UniProt: cell inner membrane, peripheral membrane protein (ECO:0000269, PubMed:16079137)."),
    4: ("KEEP_AS_NON_CORE", "Peripheral inner-membrane PTS component (UniProt ECO:0000269, PubMed:2999119); the location is carried by the IDA plasma membrane annotation, so the generic parent is not core."),
    5: ("KEEP_AS_NON_CORE", "ALADIN is a nuclear pore complex component at the nuclear envelope (UniProt ECO:0000269 nuclear pore complex and nuclear envelope; IDA nuclear membrane lead). Membrane association is real; the generic term adds nothing over the NPC/nuclear membrane annotations."),
    6: ("MARK_AS_OVER_ANNOTATED", "UniProt: cytoplasm and nucleus (ECO:0000269); a soluble cytosolic aminoacyl-tRNA synthetase with no membrane association on record."),
    7: ("REMOVE", "Confirmed: cytoplasmic/mitochondrial ribosome-recycling ATPase with no membrane association on record."),
    8: ("REMOVE", "Confirmed: no UniProt location; the only membrane lead is a Reactome TAS plasma membrane row, and the gene's other location is cytosol."),
    9: ("KEEP_AS_NON_CORE", "UniProt: cytoplasm, colocalizing with PAK2 at the leading edge (ECO:0000269); ABI3 is a WAVE regulatory complex subunit recruited to the leading-edge membrane. Plausible peripheral association, not a core location."),
    10: ("MARK_AS_OVER_ANNOTATED", "Confirmed: UniProt places ABR at dendritic spines, axon and synapse (by similarity); no protein-specific membrane evidence beyond an IBA plasma membrane lead."),
    11: ("MARK_AS_OVER_ANNOTATED", "Confirmed: peroxisomal matrix thiolase (UniProt ECO:0000269)."),
    12: ("KEEP_AS_NON_CORE", "UniProt: recycling endosome membrane, peripheral membrane protein (ECO:0000269, PubMed:16256741). Membrane is true; the specific term carries it."),
    13: ("KEEP_AS_NON_CORE", "UniProt: cell membrane (ECO:0000269, PubMed:30905672) and endosome membrane, peripheral; IDA plasma membrane lead."),
    14: ("KEEP_AS_NON_CORE", "UniProt: Golgi apparatus membrane, peripheral (ECO:0000269, four PubMed citations); EXP/IDA Golgi membrane leads."),
    15: ("MARK_AS_OVER_ANNOTATED", "Confirmed: cytosolic enzyme (UniProt ECO:0000269)."),
    16: ("MARK_AS_OVER_ANNOTATED", "UniProt: peroxisome (ECO:0000269); a peroxisomal matrix acyl-CoA oxidase with no membrane association on record."),
    17: ("MARK_AS_OVER_ANNOTATED", "Confirmed: peroxisomal matrix enzyme (UniProt by similarity)."),
    18: ("KEEP_AS_NON_CORE", "Cortical and junctional beta-actin is membrane-associated, but the generic term is not ACTB's core location (cytoskeleton)."),
    19: ("MARK_AS_OVER_ANNOTATED", "Confirmed: UniProt places ACTR1B on the cytoskeleton and centrosome; no protein-specific membrane evidence."),
    20: ("MARK_AS_OVER_ANNOTATED", "No UniProt location; leads are cytoplasm and cytoplasmic vesicle only. No protein-specific evidence of membrane association for AGFG2."),
    21: ("KEEP_AS_NON_CORE", "Confirmed: membrane association independently supported by membrane flotation (PMID:14749716, as recorded by the earlier review)."),
    22: ("MARK_AS_OVER_ANNOTATED", "UniProt: P-body (ECO:0000269); no membrane evidence for AGO3 (the flotation evidence cited for AGO2 does not transfer)."),
    23: ("MARK_AS_OVER_ANNOTATED", "UniProt: P-body (ECO:0000269); no membrane evidence for AGO4."),
    24: ("KEEP_AS_NON_CORE", "UniProt: peroxisome membrane (by similarity) with ISS peroxisomal membrane lead; the generic parent is not core."),
    25: ("KEEP_AS_NON_CORE", "Confirmed: plasma membrane by four IDA rows and sarcolemma IDA; peripheral, cytosol-facing protein."),
    26: ("MARK_AS_OVER_ANNOTATED", "UniProt: nucleus, cytosol, secreted (ECO:0000269); ER/Golgi by similarity only. No membrane association on record."),
    27: ("MARK_AS_OVER_ANNOTATED", "UniProt: cytosol (ECO:0000269) and nucleus; multisynthetase-complex scaffold with no membrane association on record."),
    28: ("MARK_AS_OVER_ANNOTATED", "Confirmed: centrosomal/nuclear protein."),
    29: ("MARK_AS_OVER_ANNOTATED", "Confirmed: no location data beyond this row."),
    30: ("MARK_AS_OVER_ANNOTATED", "Confirmed: cytosolic/sarcomeric glycolytic enzyme; no membrane location in UniProt."),
    31: ("MARK_AS_OVER_ANNOTATED", "UniProt: cytoplasm and nucleus (ECO:0000269); no membrane association on record."),
    32: ("MARK_AS_OVER_ANNOTATED", "Confirmed: cytoplasmic, with stress-induced mitochondrial translocation."),
    33: ("ACCEPT", "Confirmed: calcium-dependent phospholipid-binding annexin whose recruitment to plasma-membrane lesions is the basis of its function (earlier review); no experimentally supported specific membrane term carries this."),
    34: ("KEEP_AS_NON_CORE", "UniProt: clathrin-coated vesicle membrane, peripheral (ECO:0000269); specific membrane terms (Golgi, coated vesicle membrane) carry the location, so the generic parent is not core."),
    35: ("KEEP_AS_NON_CORE", "Confirmed: peripheral coated-vesicle membrane protein (UniProt ECO:0000269)."),
    36: ("KEEP_AS_NON_CORE", "UniProt: clathrin-coated vesicle membrane, peripheral; specific coat/vesicle membrane terms carry the location."),
    37: ("KEEP_AS_NON_CORE", "AP-3 coat subunit: UniProt Golgi membrane peripheral (by similarity) and IDA endosome membrane lead. Membrane is true; generic."),
    38: ("MARK_AS_OVER_ANNOTATED", "Confirmed: mainly nuclear (UniProt ECO:0000269)."),
    39: ("MARK_AS_OVER_ANNOTATED", "Secreted apolipoprotein on lipoprotein particles (UniProt ECO:0000269). The plasma membrane leads are Reactome TAS rows for APOE bound to its receptors, which does not make it a membrane constituent."),
    40: ("MODIFY", "Confirmed: peripheral COPI coat subunit (UniProt Golgi membrane); the earlier MODIFY to a specific membrane term stands."),
    41: ("KEEP_AS_NON_CORE", "Confirmed: peripheral membrane protein with IDA Golgi membrane leads."),
    42: ("REMOVE", "Confirmed: nuclear/cytosolic helicase (UniProt ECO:0000269)."),
    43: ("MARK_AS_OVER_ANNOTATED", "Confirmed: cytosolic enzyme."),
    44: ("KEEP_AS_NON_CORE", "Peripheral inner-membrane F1 subunit (UniProt), with IDA mitochondrial inner membrane; the specific term carries the location, so the generic parent is not core."),
    45: ("KEEP_AS_NON_CORE", "Peripheral inner-membrane F1 subunit (UniProt ECO:0000269 PubMed:25168243); the specific mitochondrial membrane terms carry the location."),
    46: ("KEEP_AS_NON_CORE", "Peripheral inner-membrane F1 subunit (UniProt ECO:0000269 PubMed:25168243); the specific mitochondrial membrane terms carry the location."),
    47: ("MARK_AS_OVER_ANNOTATED", "Confirmed: cytoplasmic/perinuclear and midbody protein."),
    48: ("KEEP_AS_NON_CORE", "Confirmed: ER/plasma-membrane association reported independently (PMID:18602463, as recorded by the earlier review)."),
    49: ("MARK_AS_OVER_ANNOTATED", "Confirmed: cytosolic/nuclear chaperone (UniProt ECO:0000269)."),
    50: ("MARK_AS_OVER_ANNOTATED", "Confirmed: Bcl-2 family member lacking the C-terminal membrane anchor; nuclear location only."),
    51: ("KEEP_AS_NON_CORE", "UniProt: trans-Golgi network membrane (ECO:0000269, PubMed:18329369). Membrane is true, but not BIRC6's core location."),
    52: ("MARK_AS_OVER_ANNOTATED", "UniProt: nucleus and cytoplasm (ECO:0000269); no membrane association on record."),
    53: ("MARK_AS_OVER_ANNOTATED", "UniProt: cytoplasm and nucleus (ECO:0000269); soluble pyrimidine-synthesis enzyme."),
    54: ("KEEP_AS_NON_CORE", "UniProt: autophagosome membrane (ECO:0000269, PubMed:25771791), peripheral. Membrane is true; generic."),
    55: ("MARK_AS_OVER_ANNOTATED", "Confirmed: ER-lumenal chaperone (UniProt ECO:0000269)."),
    56: ("MARK_AS_OVER_ANNOTATED", "Confirmed: cytoplasmic/nuclear (UniProt ECO:0000269)."),
    57: ("KEEP_AS_NON_CORE", "Plasma membrane by EXP and IDA leads; CARMIL2 is a membrane-cytoskeleton linker (UniProt function). Membrane is true; generic."),
    58: ("MARK_AS_OVER_ANNOTATED", "UniProt: nucleus; transcription-factor subunit with no membrane association."),
    59: ("MARK_AS_OVER_ANNOTATED", "UniProt: cytoplasm (ECO:0000269), nucleus, centrosome; no membrane association on record."),
    60: ("MARK_AS_OVER_ANNOTATED", "UniProt: nucleus, cytoplasm, mitochondrion, centrosome; the only membrane lead is a Reactome TAS ER-membrane row describing CDK1 acting on membrane substrates, not residing there."),
    61: ("KEEP_AS_NON_CORE", "UniProt: ER membrane (ECO:0000269, three studies) with IDA leads. Membrane is true; the specific ER membrane term carries it."),
    62: ("KEEP_AS_NON_CORE", "Peripheral ESCRT-III protein (UniProt ECO:0000269) with IDA endosomal/lysosomal membrane leads; the specific terms carry the location."),
    63: ("KEEP_AS_NON_CORE", "Peripheral coated-vesicle membrane protein (UniProt ECO:0000269); specific coat and vesicle membrane terms carry the location."),
    64: ("KEEP_AS_NON_CORE", "Peripheral coated-vesicle membrane protein (UniProt ECO:0000269); specific coat and vesicle membrane terms carry the location."),
    65: ("MARK_AS_OVER_ANNOTATED", "Confirmed: nuclear enzyme (UniProt ECO:0000269)."),
    66: ("MARK_AS_OVER_ANNOTATED", "Confirmed: ER-lumenal enzyme (UniProt ECO:0000269)."),
    67: ("MARK_AS_OVER_ANNOTATED", "Confirmed: cullin scaffold; nuclear/Golgi/cytoplasmic in UniProt."),
    68: ("KEEP_AS_NON_CORE", "Confirmed: IDA endosome membrane/retromer leads; dynactin recruited to membrane cargo."),
    69: ("MARK_AS_OVER_ANNOTATED", "Confirmed: mitochondrial matrix E2 (UniProt)."),
    70: ("MARK_AS_OVER_ANNOTATED", "UniProt: ER lumen (ECO:0000269, four studies). Its note that DNAJB11 is ER-membrane associated applies only to a C-terminally epitope-tagged construct, so it is not evidence for the native protein."),
    71: ("REMOVE", "Confirmed: cytoplasmic/nuclear/Z-line chaperone (UniProt ECO:0000269)."),
    72: ("MARK_AS_OVER_ANNOTATED", "Confirmed: ER-lumenal reductase (UniProt ECO:0000269)."),
    73: ("KEEP_AS_NON_CORE", "Confirmed: early endosome membrane, peripheral (UniProt ECO:0000269)."),
    74: ("KEEP_AS_NON_CORE", "Confirmed: early endosome membrane, peripheral (UniProt ECO:0000269)."),
    75: ("MARK_AS_OVER_ANNOTATED", "UniProt: endoplasmic reticulum (by similarity); GOA leads place it in the ER lumen and cytosol. No membrane association on record."),
    76: ("KEEP_AS_NON_CORE", "Confirmed: palmitoylated cysteine-string protein (UniProt lipid-anchor, by similarity; IDA plasma membrane)."),
    77: ("MARK_AS_OVER_ANNOTATED", "Confirmed: cytoplasmic/nuclear co-chaperone (UniProt ECO:0000269)."),
    78: ("KEEP_AS_NON_CORE", "Catalytic subunit of the ER-membrane DPM synthase complex, with IDA ER membrane leads. Membrane is true; the specific term carries it."),
    79: ("MARK_AS_OVER_ANNOTATED", "Confirmed: nuclear/cytoplasmic (UniProt ECO:0000269)."),
    80: ("MARK_AS_OVER_ANNOTATED", "UniProt: cytoskeleton (ECO:0000305); dynein is linked to membrane cargo through adaptors, but no protein-specific membrane location is on record."),
    81: ("MARK_AS_OVER_ANNOTATED", "UniProt: cytoplasm and PML body; translation-initiation factor with no membrane association on record."),
    82: ("MARK_AS_OVER_ANNOTATED", "Confirmed: cytoplasmic/nuclear translation factor (UniProt ECO:0000269). An EXP ER-membrane lead (PMID:8660923) could not be checked (no cached abstract); the cached localization study (PMID:12210765) reports nuclear and cytoplasmic distribution only."),
    83: ("MARK_AS_OVER_ANNOTATED", "Confirmed: nucleocytoplasmic RNA-binding protein."),
    84: ("KEEP_AS_NON_CORE", "Confirmed: ER membrane, peripheral (UniProt ECO:0000269)."),
    85: ("KEEP_AS_NON_CORE", "Confirmed: ER membrane, peripheral, lumenal side (UniProt ECO:0000269)."),
    86: ("MARK_AS_OVER_ANNOTATED", "UniProt: ER lumen (soluble); no membrane association on record."),
    87: ("MARK_AS_OVER_ANNOTATED", "Confirmed: cytoplasmic kinase."),
    88: ("REMOVE", "Confirmed: nuclear DNA-repair protein (UniProt ECO:0000269)."),
    89: ("MARK_AS_OVER_ANNOTATED", "Confirmed: cytoplasmic synthase (UniProt ECO:0000269)."),
    90: ("MARK_AS_OVER_ANNOTATED", "Confirmed: cytoplasmic synthase (UniProt ECO:0000269)."),
    91: ("REMOVE", "Confirmed: nuclear/mitochondrial nuclease."),
    92: ("MARK_AS_OVER_ANNOTATED", "UniProt: cytoplasm and nucleus (by similarity); a steroid-receptor co-chaperone with no membrane association on record."),
    93: ("KEEP_AS_NON_CORE", "UniProt: membrane, peripheral membrane protein (ECO:0000269, PubMed:743300), with IDA cytoplasmic side of plasma membrane lead. Membrane is true; not G6PD's core cytosolic location."),
    94: ("MARK_AS_OVER_ANNOTATED", "Confirmed: lysosomal lumenal enzyme; its UniProt lysosome-membrane entry comes from a lysosomal-membrane proteome (PubMed:17897319), not a GAA-specific study."),
    95: ("MARK_AS_OVER_ANNOTATED", "Confirmed: cytosolic kinase."),
    96: ("KEEP_AS_NON_CORE", "UniProt: membrane (ECO:0000269, PubMed:12829261), with IDA plasma membrane and nuclear membrane leads. Membrane association is documented; not GAPDH's core location."),
    97: ("MARK_AS_OVER_ANNOTATED", "Confirmed: cytoplasmic, ribosome-associated."),
    98: ("MARK_AS_OVER_ANNOTATED", "UniProt: nucleus, gems, cytoplasm (ECO:0000269); SMN-complex protein with no membrane association on record."),
    99: ("MARK_AS_OVER_ANNOTATED", "Confirmed: no UniProt location; membrane leads are IBA/IEA only."),
    100: ("KEEP_AS_NON_CORE", "Confirmed: peroxisome membrane, lumenal side (UniProt ECO:0000269)."),
    101: ("MARK_AS_OVER_ANNOTATED", "Confirmed: cytoplasmic/secreted (UniProt ECO:0000269)."),
    102: ("MARK_AS_OVER_ANNOTATED", "Confirmed: cytoplasmic GTPase."),
    103: ("MARK_AS_OVER_ANNOTATED", "Confirmed: lysosomal lumenal enzyme."),
    104: ("MARK_AS_OVER_ANNOTATED", "Confirmed: cytoplasmic glycogen-granule protein."),
    105: ("MARK_AS_OVER_ANNOTATED", "Confirmed: cytosolic glycogen synthase."),
    106: ("MARK_AS_OVER_ANNOTATED", "Confirmed: cytoplasmic GTPase."),
    107: ("MARK_AS_OVER_ANNOTATED", "Confirmed: lysosomal lumenal enzyme."),
    108: ("MARK_AS_OVER_ANNOTATED", "Confirmed: lysosomal lumenal enzyme (UniProt ECO:0000269)."),
    109: ("MARK_AS_OVER_ANNOTATED", "Confirmed: nucleocytoplasmic hnRNP (UniProt ECO:0000269)."),
    110: ("MARK_AS_OVER_ANNOTATED", "Confirmed: peroxisomal enzyme."),
    111: ("MARK_AS_OVER_ANNOTATED", "UniProt: cytosol (ECO:0000269); ribosome-associated chaperone. The only membrane lead is an IBA plasma membrane row."),
    112: ("MARK_AS_OVER_ANNOTATED", "UniProt: cytoskeleton/spindle (by similarity); membrane leads are IBA plasma membrane and a sperm CatSper ISS row, neither relevant to this cell type."),
    113: ("KEEP_AS_NON_CORE", "UniProt: lysosome membrane, peripheral (ECO:0000269) and cell membrane; IDA lysosomal membrane lead (chaperone-mediated autophagy). The specific terms carry the location, so the generic parent is not core."),
    114: ("KEEP_AS_NON_CORE", "Confirmed: IDA plasma membrane and clathrin-coated pit leads (cell-surface Hsp60 pool); matrix is the principal location."),
    115: ("MARK_AS_OVER_ANNOTATED", "UniProt: secreted (ECO:0000269); hydroxyapatite-binding matrix protein. No membrane association on record."),
    116: ("MARK_AS_OVER_ANNOTATED", "UniProt: nucleus and cytoplasm (ECO:0000269); no membrane association on record."),
    117: ("MARK_AS_OVER_ANNOTATED", "Confirmed: nuclear/cytoplasmic RNA-binding protein."),
    118: ("KEEP_AS_NON_CORE", "Confirmed: cell membrane, peripheral (UniProt ECO:0000269)."),
    119: ("MARK_AS_OVER_ANNOTATED", "Confirmed: cytosolic enzyme (UniProt ECO:0000269)."),
    120: ("MARK_AS_OVER_ANNOTATED", "Confirmed: nuclear transcription factor."),
    121: ("KEEP_AS_NON_CORE", "UniProt: cytolytic granule membrane (ECO:0000269, PubMed:24088571) and lysosome membrane, peripheral; EXP leads. Membrane association is documented, including in NK-cell granules."),
    122: ("MARK_AS_OVER_ANNOTATED", "Confirmed: cytoplasmic enzyme."),
    123: ("KEEP_AS_NON_CORE", "UniProt: mitochondrion inner membrane (ECO:0000269, PubMed:27618187), peripheral; IDA leads. Membrane association is documented; not LDHB's core cytoplasmic location."),
    124: ("KEEP_AS_NON_CORE", "UniProt: secreted and associates with the cell surface (ECO:0000269, PubMed:32272059); IDA immunological synapse lead. Membrane association is documented; generic."),
    125: ("REMOVE", "Confirmed: mitochondrial matrix protease (UniProt ECO:0000269)."),
    126: ("REMOVE", "Confirmed: peroxisomal matrix protease (UniProt ECO:0000269)."),
    127: ("KEEP_AS_NON_CORE", "Confirmed: cell membrane in UniProt; IDA plasma membrane lead."),
    128: ("MARK_AS_OVER_ANNOTATED", "UniProt: 'seems to be predominantly mitochondrial' (ECO:0000269); its nuclear inner/outer membrane entries carry no evidence code and the GOA rows are IEA. No protein-specific membrane evidence."),
    129: ("KEEP_AS_NON_CORE", "UniProt: ER membrane, peripheral (ECO:0000269, three studies). Membrane is true; the specific ER membrane term carries it."),
    130: ("MARK_AS_OVER_ANNOTATED", "UniProt: spindle/microtubules (ECO:0000269); no membrane association on record."),
    131: ("MARK_AS_OVER_ANNOTATED", "UniProt: nucleus, spindle, centrosome (ECO:0000269); no membrane association on record."),
    132: ("MARK_AS_OVER_ANNOTATED", "UniProt: cytoplasm; soluble one-carbon enzyme with no membrane association on record."),
    133: ("MARK_AS_OVER_ANNOTATED", "Confirmed: mitochondrial enzyme."),
    134: ("KEEP_AS_NON_CORE", "Confirmed: IDA plasma membrane, cytoplasmic side of plasma membrane and immunological synapse leads (cortical myosin)."),
    135: ("MARK_AS_OVER_ANNOTATED", "Confirmed: cytoplasmic/nuclear acetyltransferase."),
    136: ("MARK_AS_OVER_ANNOTATED", "Confirmed: UniProt explicitly reports NAA15 in free and cytoskeleton-bound but not membrane-bound polysomes."),
    137: ("MARK_AS_OVER_ANNOTATED", "Confirmed: nucleolar protein."),
    138: ("KEEP_AS_NON_CORE", "Confirmed: autophagy receptor on autophagosomes and lysosomes (UniProt ECO:0000269); Reactome places it on peroxisomal membranes in pexophagy. Generic."),
    139: ("KEEP_AS_NON_CORE", "UniProt: cell membrane (ECO:0000269, PubMed:34626534) with IDA plasma membrane lead; the specific term carries the location, so the generic parent is not core."),
    140: ("REMOVE", "Confirmed: nucleolar protein."),
    141: ("REMOVE", "Confirmed: cytoplasmic/nuclear ATPase."),
    142: ("MARK_AS_OVER_ANNOTATED", "Confirmed: ER-lumenal/secreted enzyme."),
    143: ("MARK_AS_OVER_ANNOTATED", "Confirmed: ER-lumenal enzyme."),
    144: ("MARK_AS_OVER_ANNOTATED", "Confirmed: cytosolic enzyme."),
    145: ("KEEP_AS_NON_CORE", "Confirmed: ESCRT-associated adaptor at the midbody ring and immunological synapse (IDA lead); membrane-associated in function, generic as a term."),
    146: ("MARK_AS_OVER_ANNOTATED", "Confirmed: cytosolic/matrix glycolytic enzyme; the IDA membrane-raft lead is itself a raft proteome."),
    147: ("KEEP_AS_NON_CORE", "UniProt: cell membrane and clathrin-coated pit (ECO:0000269) with IDA leads; the specific terms carry the location, so the generic parent is not core."),
    148: ("ACCEPT", "Confirmed: PIK3C3 makes PI3P on endosomal and autophagic membranes, so membrane association is part of its catalytic mechanism (earlier review). Its only experimental membrane lead is an IDA plasma membrane row, which is not where it acts, so no specific term carries this."),
    149: ("KEEP_AS_NON_CORE", "Confirmed: p85 recruited to phosphotyrosine receptors at the plasma membrane (Reactome TAS leads); generic."),
    150: ("KEEP_AS_NON_CORE", "Confirmed: ER and Golgi membrane, peripheral (UniProt ECO:0000269)."),
    151: ("MARK_AS_OVER_ANNOTATED", "Confirmed: cytosolic kinase (UniProt ECO:0000269)."),
    152: ("MARK_AS_OVER_ANNOTATED", "Confirmed: ER-lumenal fucosyltransferase (UniProt ER, by similarity)."),
    153: ("MARK_AS_OVER_ANNOTATED", "UniProt: ER lumen (ECO:0000269); soluble cyclophilin with no membrane association on record."),
    154: ("REMOVE", "Confirmed: nuclear cohesin subunit."),
    155: ("KEEP_AS_NON_CORE", "UniProt: cytoplasm and cell cortex (ECO:0000269) with IDA plasma membrane and cytoplasmic side of membrane leads; the specific terms carry the location, so the generic parent is not core."),
    156: ("MARK_AS_OVER_ANNOTATED", "Cytosolic ribosomal protein (UniProt ECO:0000269); ribosomes on the rough ER are attached via the translocon but are not membrane constituents. Same call as RPS3."),
    157: ("MARK_AS_OVER_ANNOTATED", "Confirmed: cytosolic ribosomal protein."),
    158: ("MARK_AS_OVER_ANNOTATED", "Confirmed: peroxisomal/cytoplasmic lipid-transfer protein."),
    159: ("MARK_AS_OVER_ANNOTATED", "UniProt: cytoplasm, nucleus, nucleolus, ER (no membrane entry); membrane leads are IBA/IEA only. RNP association with the ER does not make STAU2 a membrane protein."),
    160: ("MARK_AS_OVER_ANNOTATED", "Confirmed: kinetochore/spindle kinase."),
    161: ("KEEP_AS_NON_CORE", "Confirmed: ER membrane (UniProt ECO:0000269, six studies)."),
    162: ("KEEP_AS_NON_CORE", "Confirmed: Golgi membrane, peripheral (UniProt ECO:0000269)."),
}
