all:
    uv run python prepare.py --json ../CG8915-uniprot-source.json --swiss ../CG8915-reference-Q9H6S0-uniprot.txt ../CG8915-reference-Q9W1I2-uniprot.txt --output inputs/sequences.fasta
    mafft --globalpair --maxiterate 1000 inputs/sequences.fasta > outputs/global.fasta 2> outputs/global-stderr.txt
    mafft --localpair --maxiterate 1000 inputs/sequences.fasta > outputs/local.fasta 2> outputs/local-stderr.txt
    uv run python analyze.py outputs/global.fasta --reference Q9H6S0 --sites 216 217 218 219 220 221 222 223 224 316 317 318 319 --output outputs/global-sites.json
    uv run python analyze.py outputs/local.fasta --reference Q9H6S0 --sites 216 217 218 219 220 221 222 223 224 316 317 318 319 --output outputs/local-sites.json
