default: compare control
compare:
    uv run --no-project --with biopython==1.85 python compare.py ../CycA-uniprot-source.json ../CycA-reference-P14785-uniprot.json results
control:
    uv run --no-project --with biopython==1.85 python compare.py ../CycA-reference-P14785-uniprot.json ../CycA-reference-P14785-uniprot.json control
