"""Ensembl Compara check of the cryaba/cryabb duplication (orthologs + flanking ohnologs).

Run:  uv run python projects/DANRE_DUPLICATION/pairs/cryaba_cryabb/ensembl_check.py \
        > projects/DANRE_DUPLICATION/pairs/cryaba_cryabb/ensembl_check.md

Queries the public Ensembl REST API (https://rest.ensembl.org) live; nothing is
hard-coded except the two zebrafish gene ids and the species list. Output is a
Markdown report with:
  1. the Ensembl release and the taxonomy level Compara assigns to the
     cryaba-cryabb paralogy;
  2. per-species orthologs of each copy (which fish keep one vs two copies);
  3. a double-conserved-synteny check: protein-coding genes within +/- WINDOW of
     each copy that have a zebrafish paralog (at a teleost-level node) located
     within +/- WINDOW of the other copy.
"""

import json
import time
import urllib.request

SERVER = "https://rest.ensembl.org"
GENES = {"cryaba": "ENSDARG00000042621", "cryabb": "ENSDARG00000101380"}
WINDOW = 1_500_000
TELEOST_LEVELS = {"Teleostei", "Clupeocephala", "Otomorpha", "Otophysi", "Neopterygii",
                  "Osteoglossocephalai"}
SPECIES = [
    ("lepisosteus_oculatus", "spotted gar (Holostei, pre-TGD outgroup)"),
    ("scleropages_formosus", "Asian arowana (Osteoglossomorpha)"),
    ("paramormyrops_kingsleyae", "elephantfish (Osteoglossomorpha)"),
    ("clupea_harengus", "Atlantic herring (Clupeiformes)"),
    ("denticeps_clupeoides", "denticle herring (Clupeiformes)"),
    ("astyanax_mexicanus", "Mexican tetra (Characiformes)"),
    ("pygocentrus_nattereri", "red-bellied piranha (Characiformes)"),
    ("ictalurus_punctatus", "channel catfish (Siluriformes)"),
    ("electrophorus_electricus", "electric eel (Gymnotiformes)"),
    ("cyprinus_carpio_carpio", "common carp (Cypriniformes, extra WGD)"),
    ("oryzias_latipes", "medaka (Percomorpha)"),
    ("gasterosteus_aculeatus", "stickleback (Percomorpha)"),
    ("takifugu_rubripes", "fugu (Percomorpha)"),
    ("oreochromis_niloticus", "Nile tilapia (Percomorpha)"),
    ("homo_sapiens", "human"),
]


def get(path, tries=4):
    url = SERVER + path
    for i in range(tries):
        try:
            req = urllib.request.Request(url, headers={"Content-Type": "application/json"})
            with urllib.request.urlopen(req, timeout=120) as r:
                return json.load(r)
        except Exception as e:  # noqa: BLE001
            if i == tries - 1:
                raise
            time.sleep(2 + 3 * i)


def lookup(gid):
    return get(f"/lookup/id/{gid}?content-type=application/json")


def homologies(gid, htype):
    d = get(f"/homology/id/danio_rerio/{gid}?type={htype};format=condensed;"
            "content-type=application/json")
    return d["data"][0]["homologies"] if d.get("data") else []


def main():
    rel = get("/info/data/?content-type=application/json")
    print("# cryaba / cryabb: Ensembl Compara check\n")
    print("Generated by `ensembl_check.py` in this folder from the live Ensembl REST API; "
          "do not edit by hand.\n")
    print(f"Ensembl release(s): {rel.get('releases')}\n")

    loc = {n: lookup(g) for n, g in GENES.items()}
    print("## Gene locations\n")
    print("| gene | Ensembl id | chromosome | start |\n|---|---|---|---|")
    for n, g in GENES.items():
        print(f"| {n} | {g} | {loc[n]['seq_region_name']} | {loc[n]['start']} |")

    print("\n## Paralogy between the two copies\n")
    for h in homologies(GENES["cryaba"], "paralogues"):
        if h["id"] == GENES["cryabb"]:
            print(f"- cryaba-cryabb: type `{h['type']}`, duplication node taxonomy level "
                  f"**{h['taxonomy_level']}**")

    print("\n## Orthologs by species\n")
    orth = {n: homologies(g, "orthologues") for n, g in GENES.items()}
    print("| species | cryaba orthologs | cryabb orthologs |\n|---|---|---|")
    for sp, label in SPECIES:
        cells = []
        for n in GENES:
            hs = [f"{h['id']} ({h['type']})" for h in orth[n] if h["species"] == sp]
            cells.append("<br>".join(hs) if hs else "none")
        print(f"| {label} | {cells[0]} | {cells[1]} |")

    print(f"\n## Double-conserved synteny (+/- {WINDOW // 1000} kb)\n")
    region = {}
    for n in GENES:
        L = loc[n]
        s, e = max(1, L["start"] - WINDOW), L["end"] + WINDOW
        feats = get(f"/overlap/region/danio_rerio/{L['seq_region_name']}:{s}-{e}"
                    "?feature=gene;biotype=protein_coding;content-type=application/json")
        region[n] = {f["id"]: f for f in feats}
    other = {"cryaba": "cryabb", "cryabb": "cryaba"}
    pairs = set()
    ntested = 0
    for n in ["cryaba"]:
        for gid, f in region[n].items():
            if gid in GENES.values():
                continue
            ntested += 1
            for h in homologies(gid, "paralogues"):
                if h["id"] in region[other[n]] and h["taxonomy_level"] in TELEOST_LEVELS:
                    g2 = region[other[n]][h["id"]]
                    pairs.add((f.get("external_name") or gid, f["start"],
                               g2.get("external_name") or h["id"], g2["start"],
                               h["taxonomy_level"]))
    print(f"Protein-coding genes tested near cryaba: {ntested}; genes near cryabb: "
          f"{len(region['cryabb'])}.\n")
    print("| gene near cryaba (chr {}) | start | paralog near cryabb (chr {}) | start | "
          "Compara level |\n|---|---|---|---|---|".format(
              loc['cryaba']['seq_region_name'], loc['cryabb']['seq_region_name']))
    for p in sorted(pairs, key=lambda x: x[1]):
        print(f"| {p[0]} | {p[1]} | {p[2]} | {p[3]} | {p[4]} |")
    if not pairs:
        print("| (none found) | | | | |")


if __name__ == "__main__":
    main()
