#!/usr/bin/env python3
"""Is any molecular function assignable to AAMDC from its family?

The AAMDC review concludes that no molecular function is currently justifiable. That is a
negative claim, so it deserves evidence rather than an absence of evidence. This script asks
the question directly: take AAMDC's protein family, enumerate every characterised member, and
see whether any of them has an experimentally supported molecular function that could
legitimately transfer.

Everything is fetched live from InterPro, UniProt and QuickGO; nothing is hardcoded. Run:

    uv run python analyze_mth938.py            # writes RESULTS.md
"""
from __future__ import annotations

import json
import subprocess
import sys
from collections import Counter

AAMDC = "Q9H7C9"
PFAM = "PF04430"          # DUF498, the Pfam family AAMDC belongs to
INTERPRO = "IPR007523"    # NDUFAF3/AAMDC

# Evidence codes that reflect an actual experiment, as opposed to transfer or prediction.
EXPERIMENTAL = {"EXP", "IDA", "IPI", "IMP", "IGI", "IEP", "HTP", "HDA", "HMP", "HGI", "HEP"}


def get(url: str, accept: str = "application/json"):
    """GET a URL via curl and parse JSON. Returns None on failure rather than raising."""
    r = subprocess.run(
        ["curl", "-sS", "-L", "--max-time", "120", "-H", f"Accept: {accept}", url],
        capture_output=True, text=True,
    )
    if r.returncode != 0 or not r.stdout.strip():
        print(f"  ! fetch failed: {url}", file=sys.stderr)
        return None
    return json.loads(r.stdout)


def family_members(pfam: str) -> list[dict]:
    """Every reviewed (Swiss-Prot) protein carrying the given Pfam domain."""
    url = (
        "https://rest.uniprot.org/uniprotkb/search"
        f"?query=xref:pfam-{pfam}+AND+reviewed:true"
        "&fields=accession,id,protein_name,organism_name,length,cc_function,cc_catalytic_activity"
        "&format=json&size=500"
    )
    data = get(url)
    return data.get("results", []) if data else []


def go_annotations(acc: str) -> list[dict]:
    """All GO annotations for an accession, from QuickGO."""
    url = (
        "https://www.ebi.ac.uk/QuickGO/services/annotation/search"
        f"?geneProductId={acc}&limit=200"
    )
    data = get(url)
    return data.get("results", []) if data else []


def function_text(entry: dict) -> str:
    """Extract the UniProt FUNCTION comment, if any."""
    for c in entry.get("comments", []):
        if c.get("commentType") == "FUNCTION":
            return " ".join(t.get("value", "") for t in c.get("texts", []))
    return ""


def has_catalytic_activity(entry: dict) -> bool:
    return any(c.get("commentType") == "CATALYTIC ACTIVITY" for c in entry.get("comments", []))


def main() -> None:
    print(f"Fetching Swiss-Prot members of {PFAM} (DUF498)...")
    members = family_members(PFAM)
    print(f"  {len(members)} reviewed members")
    if not members:
        print("No members retrieved; aborting rather than reporting an empty result.")
        return

    rows = []
    mf_experimental: Counter[str] = Counter()
    for m in members:
        acc = m["primaryAccession"]
        anns = go_annotations(acc)
        mf_exp = {
            (a["goId"], a.get("goName", ""))
            for a in anns
            if a.get("goAspect") == "molecular_function"
            and a.get("goEvidence") in EXPERIMENTAL
            and a["goId"] != "GO:0005515"     # bare protein binding is uninformative
        }
        # GO:0003674 ND is an explicit curator statement that no function is known
        nd = any(a["goId"] == "GO:0003674" and a.get("goEvidence") == "ND" for a in anns)
        for go_id, go_name in mf_exp:
            mf_experimental[f"{go_id} {go_name}"] += 1
        rows.append({
            "acc": acc,
            "id": m.get("uniProtkbId", ""),
            "organism": m.get("organism", {}).get("scientificName", ""),
            "length": m.get("sequence", {}).get("length", ""),
            "function": function_text(m),
            "catalytic": has_catalytic_activity(m),
            "mf_experimental": sorted(mf_exp),
            "mf_nd": nd,
        })
        print(f"  {acc} {m.get('uniProtkbId','')}: "
              f"{len(mf_exp)} experimental MF term(s){' [MF=ND]' if nd else ''}")

    n_with_mf = sum(1 for r in rows if r["mf_experimental"])
    n_nd = sum(1 for r in rows if r["mf_nd"])
    n_catalytic = sum(1 for r in rows if r["catalytic"])

    L: list[str] = []
    L.append("# Is a molecular function assignable to AAMDC from its family?")
    L.append("")
    L.append("Generated by `analyze_mth938.py`. All data fetched live from UniProt, InterPro")
    L.append("and QuickGO; re-run to refresh.")
    L.append("")
    L.append("## Question")
    L.append("")
    L.append("The AAMDC review concludes that no molecular function is currently justifiable for")
    L.append("this protein. That is a negative claim. This analysis tests it the only way a")
    L.append("negative claim can be tested: enumerate the whole protein family and ask whether")
    L.append("*any* member has an experimentally supported molecular function that could transfer.")
    L.append("")
    L.append("## Family definition")
    L.append("")
    L.append(f"- Pfam **{PFAM}** — named **DUF498**, i.e. \"domain of unknown function\"")
    L.append(f"- InterPro **{INTERPRO}** — NDUFAF3/AAMDC")
    L.append("- SUPFAM SSF64076 / Gene3D 3.40.1230.10 — MTH938-like fold")
    L.append("- PANTHER PTHR15811 — MTH938 domain-containing protein")
    L.append("")
    L.append("## Result")
    L.append("")
    L.append(f"| Reviewed family members | {len(rows)} |")
    L.append("|---|---|")
    L.append(f"| With **any** experimental MF term (excluding bare protein binding) | **{n_with_mf}** |")
    L.append(f"| With an explicit `GO:0003674` **ND** (curator: no function known) | {n_nd} |")
    L.append(f"| With a UniProt CATALYTIC ACTIVITY block | {n_catalytic} |")
    L.append("")
    if mf_experimental:
        L.append("Experimental MF terms found anywhere in the family:")
        L.append("")
        for term, count in mf_experimental.most_common():
            L.append(f"- {term} ({count} member{'s' if count > 1 else ''})")
    else:
        L.append("**No member of this family carries any experimentally supported molecular")
        L.append("function term.** The absence of an MF annotation on AAMDC is therefore not an")
        L.append("oversight specific to this gene: it is a property of the entire family.")
    L.append("")
    L.append("## What the one characterised relative does")
    L.append("")
    L.append("The family is not entirely uncharacterised. Its other branch is **NDUFAF3**, and")
    L.append("that branch has a clear, consistent function across every organism in which it has")
    L.append("been studied: it is an **assembly factor for mitochondrial complex I**. See the")
    L.append("FUNCTION statements below - NDUF3 entries for human, mouse, rat, bovine, zebrafish,")
    L.append("Xenopus and Drosophila all say so, and the Drosophila entry is supported by")
    L.append("experimental evidence (PubMed:34386730).")
    L.append("")
    L.append("This is informative in a specific way. NDUFAF3 is an **assembly factor, not an")
    L.append("enzyme**: it has no catalytic activity, it binds subunits and helps build a complex,")
    L.append("and it is not part of the finished complex. Consistent with that, no member of this")
    L.append("family - including NDUFAF3 itself - carries a CATALYTIC ACTIVITY block or an")
    L.append("experimental molecular function term.")
    L.append("")
    L.append("So the family signal does *not* point toward a hidden enzymatic activity waiting to")
    L.append("be found for AAMDC. It points toward a protein-assembly / chaperone-like role, which")
    L.append("is a class of function GO struggles to express as a molecular function in any case")
    L.append("(there is no assembly-chaperone MF term; see the AAGAB review in this campaign).")
    L.append("That makes the AAMDC review's refusal to assign an MF the right call, and it also")
    L.append("suggests where to look experimentally: what complex, if any, does AAMDC help")
    L.append("assemble?")
    L.append("")
    L.append("## Members")
    L.append("")
    L.append("| Accession | Entry | Organism | Len | Catalytic block | Experimental MF |")
    L.append("|---|---|---|---|---|---|")
    for r in sorted(rows, key=lambda x: x["organism"]):
        mf = ", ".join(f"{g} {n}" for g, n in r["mf_experimental"]) or "—"
        nd = " *(MF=ND)*" if r["mf_nd"] else ""
        L.append(f"| {r['acc']} | {r['id']} | {r['organism']} | {r['length']} | "
                 f"{'yes' if r['catalytic'] else 'no'} | {mf}{nd} |")
    L.append("")
    L.append("## UniProt FUNCTION statements across the family")
    L.append("")
    for r in sorted(rows, key=lambda x: x["organism"]):
        if r["function"]:
            L.append(f"- **{r['id']}** ({r['organism']}): {r['function']}")
    L.append("")

    with open("RESULTS.md", "w") as fh:
        fh.write("\n".join(L) + "\n")
    print("\nwrote RESULTS.md")


if __name__ == "__main__":
    main()
