rna_url := "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/022/682/495/GCF_022682495.2_HLdesRot8A.1/GCF_022682495.2_HLdesRot8A.1_rna.fna.gz"
tsa_url := "https://sra-download.ncbi.nlm.nih.gov/traces/wgs03/wgs_aux/GA/BZ/GABZ01/GABZ01.1.fsa_nt.gz"

download:
	mkdir -p data results
	curl -L -o data/desro_rna.fna.gz {{rna_url}}

download-tsa:
	mkdir -p data results
	curl -L -o data/GABZ01.1.fsa_nt.gz {{tsa_url}}

search: download
	python scripts/search_peptide_in_transcripts.py \
		--rna-fasta data/desro_rna.fna.gz \
		--peptide-fasta data/vcgrp_peptide.faa \
		--max-mismatch 1 \
		--out-tsv results/vcgrp_hits.tsv

search-tsa: download-tsa
	python scripts/search_peptide_in_transcripts.py \
		--rna-fasta data/GABZ01.1.fsa_nt.gz \
		--peptide-fasta data/vcgrp_peptide.faa \
		--max-mismatch 1 \
		--out-tsv results/vcgrp_hits_tsa.tsv

test:
	python scripts/search_peptide_in_transcripts.py \
		--rna-fasta data/test_transcripts.fna \
		--peptide ACDE \
		--max-mismatch 0 \
		--out-tsv results/test_hits.tsv
