#!/usr/bin/env python3
"""Consolidate the ASSAY_TO_FUNCTION readout catalog into a single summary.

Reads the catalog (for proximity/convergence/state) and the mined aligned matches
(for the empirical GO-aspect split), then writes:

  reports/catalog_summary.tsv     one row per readout class (machine-readable)
  reports/catalog_table.md        a Markdown quick-reference table (all classes)
  reports/proximity_axis.png      the money figure: aligned-aspect composition
                                  per class, grouped molecular vs phenotypic

Nothing is hard-coded; if a class has no aligned annotations it is reported with
N=0. Run after mine_papers.py.

Usage:
    uv run --with matplotlib python projects/ASSAY_TO_FUNCTION/consolidate.py
"""
from __future__ import annotations

import csv
from collections import Counter, defaultdict
from pathlib import Path

import yaml

ROOT = Path("projects/ASSAY_TO_FUNCTION")
CATALOG = ROOT / "readout_catalog.yaml"
MATCHES = ROOT / "reports" / "paper_readout_matches.tsv"
OUT_TSV = ROOT / "reports" / "catalog_summary.tsv"
OUT_MD = ROOT / "reports" / "catalog_table.md"
OUT_PNG = ROOT / "reports" / "proximity_axis.png"


def short(s: str, n: int = 48) -> str:
    s = " ".join((s or "").split())
    return s if len(s) <= n else s[: n - 1] + "…"


def main() -> None:
    catalog = yaml.safe_load(CATALOG.read_text())["readouts"]

    # Empirical aligned aspect counts per class (from the canonical join).
    aspect: dict[str, Counter] = defaultdict(Counter)
    with MATCHES.open(newline="") as fh:
        for r in csv.DictReader(fh, delimiter="\t"):
            if r["aligned"] == "True":
                aspect[r["readout_class"]][r["aspect"]] += 1

    rows = []
    for name, spec in catalog.items():
        prox = spec.get("proximity", "")
        conv = spec.get("convergence", "")
        c = aspect.get(name, Counter())
        mf, bp, cc = c.get("MF", 0), c.get("BP", 0), c.get("CC", 0)
        n = mf + bp + cc + sum(v for k, v in c.items() if k not in ("MF", "BP", "CC"))
        pct_mf = round(100 * mf / n) if n else 0
        dominant = c.most_common(1)[0][0] if n else "-"
        # Licensing summary keyed off proximity (the project's central rule).
        if prox == "molecular":
            licenses, default = "MF (direct activity)", "core-capable"
        else:
            licenses = "BP" + ("/CC" if cc and cc >= max(1, n // 5) else "")
            default = "non-core (context)"
        rows.append({
            "readout_class": name, "reports_state_of": spec.get("reports_state_of", ""),
            "proximity": prox, "convergence": conv,
            "aligned_n": n, "MF": mf, "BP": bp, "CC": cc, "pct_MF": pct_mf,
            "dominant_aspect": dominant, "licenses": licenses, "default_core": default,
        })

    # order: molecular first, then phenotypic; within group by aligned_n desc
    rows.sort(key=lambda r: (r["proximity"] != "molecular", -r["aligned_n"], r["readout_class"]))

    # ---- TSV ----
    fields = ["readout_class", "reports_state_of", "proximity", "convergence",
              "aligned_n", "MF", "BP", "CC", "pct_MF", "dominant_aspect",
              "licenses", "default_core"]
    with OUT_TSV.open("w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=fields, delimiter="\t", lineterminator="\n")
        w.writeheader()
        w.writerows(rows)

    # ---- Markdown table ----
    lines = ["# ASSAY_TO_FUNCTION — consolidated readout catalog",
             "",
             f"Auto-generated by `consolidate.py` from `readout_catalog.yaml` "
             f"({len(rows)} classes) and the canonical aligned matches "
             f"(`paper_readout_matches.tsv`). `aligned_n` / MF·BP·CC are the GO "
             "aspects of thematically-aligned annotations; %MF is the headline "
             "proximity signal.",
             ""]
    for group, title in (("molecular", "Molecular / low-convergence (MF-licensing controls)"),
                         ("phenotypic", "Phenotypic / high-convergence (over-annotation hubs)")):
        lines += [f"## {title}", "",
                  "| readout_class | reports state of | N | MF | BP | CC | %MF | licenses / default |",
                  "|---|---|--:|--:|--:|--:|--:|---|"]
        for r in rows:
            if r["proximity"] != group:
                continue
            lines.append(
                f"| {r['readout_class']} | {short(r['reports_state_of'],40)} | "
                f"{r['aligned_n']} | {r['MF']} | {r['BP']} | {r['CC']} | "
                f"{r['pct_MF']}% | {r['licenses']}; {r['default_core']} |")
        lines.append("")
    OUT_MD.write_text("\n".join(lines))

    # ---- Figure ----
    make_figure(rows)

    n_mol = sum(1 for r in rows if r["proximity"] == "molecular")
    n_phe = sum(1 for r in rows if r["proximity"] == "phenotypic")
    mol_mf = sum(r["MF"] for r in rows if r["proximity"] == "molecular")
    mol_tot = sum(r["aligned_n"] for r in rows if r["proximity"] == "molecular") or 1
    phe_mf = sum(r["MF"] for r in rows if r["proximity"] == "phenotypic")
    phe_tot = sum(r["aligned_n"] for r in rows if r["proximity"] == "phenotypic") or 1
    print(f"Consolidated {len(rows)} classes ({n_mol} molecular, {n_phe} phenotypic).")
    print(f"Aligned MF fraction: molecular {100*mol_mf/mol_tot:.0f}% "
          f"({mol_mf}/{mol_tot}) vs phenotypic {100*phe_mf/phe_tot:.0f}% "
          f"({phe_mf}/{phe_tot}).")
    print(f"Wrote:\n  {OUT_TSV}\n  {OUT_MD}\n  {OUT_PNG}")


def make_figure(rows: list[dict]) -> None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.patches import Patch

    MIN_N = 5  # don't plot near-empty classes (noisy %)
    plotted = [r for r in rows if r["aligned_n"] >= MIN_N]
    # molecular at top, phenotypic below; within group by %MF desc
    plotted.sort(key=lambda r: (r["proximity"] != "molecular", -r["pct_MF"], -r["aligned_n"]))
    plotted.reverse()  # so molecular ends up at top in barh

    labels = [f"{r['readout_class']}  (n={r['aligned_n']})" for r in plotted]
    mf = [r["MF"] / r["aligned_n"] * 100 for r in plotted]
    bp = [r["BP"] / r["aligned_n"] * 100 for r in plotted]
    cc = [r["CC"] / r["aligned_n"] * 100 for r in plotted]
    other = [100 - a - b - c for a, b, c in zip(mf, bp, cc)]
    ytick_colors = ["#1f6f3f" if r["proximity"] == "molecular" else "#8a1f1f"
                    for r in plotted]

    fig, ax = plt.subplots(figsize=(11, max(6, 0.34 * len(plotted))))
    ypos = range(len(plotted))
    ax.barh(ypos, mf, color="#2c7fb8", label="MF (molecular function)")
    ax.barh(ypos, bp, left=mf, color="#f0a202", label="BP (biological process)")
    ax.barh(ypos, cc, left=[a + b for a, b in zip(mf, bp)], color="#7fbf7b",
            label="CC (cellular component)")
    ax.barh(ypos, other, left=[a + b + c for a, b, c in zip(mf, bp, cc)],
            color="#cccccc", label="other/unknown")
    ax.set_yticks(list(ypos))
    ax.set_yticklabels(labels, fontsize=8)
    for tick, col in zip(ax.get_yticklabels(), ytick_colors):
        tick.set_color(col)
    ax.set_xlabel("% of thematically-aligned annotations by GO aspect")
    ax.set_xlim(0, 100)
    ax.set_title("ASSAY_TO_FUNCTION: GO aspect licensed by readout class\n"
                 "molecular readouts (green labels) → MF; "
                 "phenotypic hubs (red labels) → BP/CC", fontsize=11)
    handles = [Patch(color="#2c7fb8", label="MF"), Patch(color="#f0a202", label="BP"),
               Patch(color="#7fbf7b", label="CC"), Patch(color="#cccccc", label="other")]
    ax.legend(handles=handles, loc="lower right", fontsize=8, framealpha=0.9)
    fig.tight_layout()
    fig.savefig(OUT_PNG, dpi=150)
    plt.close(fig)


if __name__ == "__main__":
    main()
