all:
    uv run python check_hydropathy.py ../A1BG-uniprot.txt --region-start 22 > a1bg-hydropathy.json
    uv run python check_hydropathy.py ../../AKIRIN1/AKIRIN1-uniprot.txt > akirin1-control-hydropathy.json
