all:
    python3 compare.py ../Lcp3-uniprot.txt ../Lcp3-reference-P07188-uniprot.txt > results.json
    python3 compare.py ../Lcp3-uniprot.txt ../Lcp3-reference-P07189-uniprot.txt > lcp4-control.json
