default: compare control human
compare:
    uv run --no-project --with biopython==1.85 python compare.py ../Hn-uniprot-source.json ../Hn-reference-P17276-uniprot.json results
control:
    uv run --no-project --with biopython==1.85 python compare.py ../Hn-reference-P17276-uniprot.json ../Hn-reference-P17276-uniprot.json control

human:
    uv run --no-project --with biopython==1.85 python compare.py ../Hn-uniprot-source.json ../Hn-human-P00439-uniprot.json human-target --sites human-literature-sites.json
    uv run --no-project --with biopython==1.85 python compare.py ../Hn-reference-P17276-uniprot.json ../Hn-human-P00439-uniprot.json human-full-length-control --sites human-literature-sites.json
