#!/usr/bin/env python3
"""Test the sigma2 dileucine-pocket residue claims for human AP2S1.

Kelly et al. 2008 (PMID:19140243) identified, in the AP2-core/CD4-dileucine-peptide
co-crystal, the sigma2 residues that build the two hydrophobic [DE]xxxL[LI] pockets
and the basic L-4 patch (the sigma2 chain in that structure is the mouse orthologue
P62743 -- see Q2, which is why the numbering has to be checked before it is used):

  * pocket-lining / pocket-filling residues mutated to abolish dileucine binding:
    sigma2 A63, L65, V88, N92, V98, L103
  * sigma2 N97, which contacts the L-1 position of the motif
  * sigma2 R15, which with alpha R21 forms the basic patch binding the L-4 residue
    and which is the FHH3 mutational hotspot (PMID:23222959)

This script asks three questions, all against live data, and hardcodes no result:

  Q1 Does human AP2S1 (P53680) actually carry those residues at those positions?
     (a RETAINED residue claim needs the identity checked, not assumed)
  Q2 Does the paper's numbering transfer to the human protein? Kelly's AP2 core is
     species-mixed and its sigma2 chain is mouse, so we check that mouse P62743 (and
     rat P62744) are identical in length and sequence to human P53680.
  Q3 How specific are these residues to sigma2? Kelly says most are "conserved in all
     sigma subunits from APs 1-4"; Nesbit et al. (PMID:23222959) say R15 is conserved
     in "all AP2sigma2 subunit orthologues and human AP sigma subunit paralogues".
     We test both statements on a MAFFT alignment of the eight human AP-complex sigma
     subunits, reporting what the alignment shows rather than what was expected.

Usage:  uv run python check_sigma2_pockets.py            (writes RESULTS.md)
"""
from __future__ import annotations

import json
import subprocess
import sys
import urllib.request
from pathlib import Path

from Bio import AlignIO

HERE = Path(__file__).resolve().parent

TARGET = "P53680"  # human AP2S1, sigma2

ORTHOLOGS = {
    "P53680": "AP2S1_HUMAN",
    "P62744": "AP2S1_RAT",
    "P62743": "AP2S1_MOUSE",
}

# The eight human AP-complex small (sigma) subunits, PANTHER family PTHR11753.
PARALOGS = {
    "P53680": "AP2S1",
    "P61966": "AP1S1",
    "P56377": "AP1S2",
    "Q96PC3": "AP1S3",
    "Q92572": "AP3S1",
    "P59780": "AP3S2",
    "Q9Y587": "AP4S1",
    "Q9NUS5": "AP5S1",
}

# position -> (expected residue, role as stated in the cited paper)
CLAIMS = {
    15: ("R", "basic L-4 patch with alpha R21; FHH3 mutational hotspot"),
    63: ("A", "pocket floor; A63W fills the pocket and blocks binding"),
    65: ("L", "pocket lining; L65S abolishes dileucine binding"),
    88: ("V", "pocket lining; V88D reduced binding below detection"),
    92: ("N", "pocket lining; N92W fills the pocket and blocks binding"),
    97: ("N", "contacts the L-1 position of the motif"),
    98: ("V", "pocket lining; V98S abolishes dileucine binding"),
    103: ("L", "pocket lining; L103S reduced binding below detection"),
}


def fetch_fasta(acc: str) -> tuple[str, str]:
    """Return (header, sequence) for a UniProt accession, fetched live."""
    url = f"https://rest.uniprot.org/uniprotkb/{acc}.fasta"
    with urllib.request.urlopen(url, timeout=90) as fh:
        text = fh.read().decode()
    lines = text.strip().splitlines()
    header = lines[0]
    seq = "".join(lines[1:])
    if not seq:
        raise RuntimeError(f"empty sequence returned for {acc}")
    return header, seq


def main() -> int:
    out: list[str] = []
    w = out.append

    seqs: dict[str, str] = {}
    headers: dict[str, str] = {}
    for acc in sorted(set(list(ORTHOLOGS) + list(PARALOGS))):
        headers[acc], seqs[acc] = fetch_fasta(acc)

    target = seqs[TARGET]
    w("# AP2S1 (sigma2) dileucine-pocket residues: are they there, and how specific are they?")
    w("")
    w("Generated by `check_sigma2_pockets.py`; every sequence is fetched live from the")
    w("UniProt REST API at run time and no result is hardcoded.")
    w("")
    w(f"Target: {TARGET} ({headers[TARGET].split('|')[2].split(' ')[0]}), "
      f"length {len(target)} aa.")
    w("")

    # ---- Q1: do the claimed residues exist at the claimed positions? -------------
    w("## Q1. Residue identity at the claimed positions in human AP2S1")
    w("")
    w("| position | expected | observed in P53680 | match | role (Kelly et al. 2008, PMID:19140243) |")
    w("|---|---|---|---|---|")
    all_match = True
    observed: dict[int, str] = {}
    for pos in sorted(CLAIMS):
        exp, role = CLAIMS[pos]
        if pos > len(target):
            raise RuntimeError(f"position {pos} beyond sequence length {len(target)}")
        obs = target[pos - 1]
        observed[pos] = obs
        ok = obs == exp
        all_match &= ok
        w(f"| {pos} | {exp} | {obs} | {'yes' if ok else 'NO'} | {role} |")
    w("")
    w(f"All eight positions match the literature: **{all_match}**")
    w("")

    # ---- Q2: does the structure's numbering transfer to human? ------------------
    w("## Q2. Does the crystal structure's numbering transfer to the human protein?")
    w("")
    w("Kelly et al. solved a species-mixed AP2 core; their Methods give the construct as")
    w("`1-621 mouse alpha-adaptin; 1-591 human beta2-adaptin; 1-435 rat mu2-adaptin,")
    w("1-143 mouse sigma2-adaptin`, so the sigma2 chain is the mouse protein (P62743).")
    w("The residue numbers therefore transfer to human AP2S1 only if the orthologues are")
    w("identical over these sites.")
    w("")
    w("| accession | entry | length | identical to P53680 over full length | residues at the 8 claimed positions |")
    w("|---|---|---|---|---|")
    ortholog_identical = True
    for acc, name in ORTHOLOGS.items():
        s = seqs[acc]
        same = s == target
        ortholog_identical &= same
        at = "".join(s[p - 1] for p in sorted(CLAIMS)) if len(s) >= max(CLAIMS) else "(too short)"
        w(f"| {acc} | {name} | {len(s)} | {same} | {at} |")
    w("")
    w(f"Human, rat and mouse sigma2 identical over the full chain: "
      f"**{ortholog_identical}** — so the numbering transfers without an alignment step.")
    w("")

    # ---- Q3: how sigma2-specific are these residues? ----------------------------
    w("## Q3. Conservation across the eight human AP-complex sigma subunits")
    w("")
    fa = HERE / "human_sigma_paralogs.fasta"
    with fa.open("w") as fh:
        for acc, sym in PARALOGS.items():
            fh.write(f">{sym}|{acc}\n{seqs[acc]}\n")
    aln_path = HERE / "human_sigma_paralogs.aln.fasta"
    proc = subprocess.run(
        ["mafft", "--maxiterate", "1000", "--localpair", "--quiet", str(fa)],
        capture_output=True, text=True, check=True,
    )
    aln_path.write_text(proc.stdout)
    aln = AlignIO.read(str(aln_path), "fasta")
    rec = {r.id.split("|")[0]: str(r.seq) for r in aln}
    ap2 = rec["AP2S1"]

    # map AP2S1 ungapped position -> alignment column
    col_of: dict[int, int] = {}
    n = 0
    for i, ch in enumerate(ap2):
        if ch != "-":
            n += 1
            col_of[n] = i
    if n != len(target):
        raise RuntimeError(f"alignment lost residues: {n} vs {len(target)}")

    order = ["AP2S1", "AP1S1", "AP1S2", "AP1S3", "AP3S1", "AP3S2", "AP4S1", "AP5S1"]
    w("MAFFT L-INS-i alignment of the eight human sigma subunits "
      f"(alignment length {aln.get_alignment_length()} columns).")
    w("")
    w("| AP2S1 pos | " + " | ".join(order) + " | identical to AP2S1 |")
    w("|---" * (len(order) + 2) + "|")
    for pos in sorted(CLAIMS):
        c = col_of[pos]
        row = [rec[k][c] for k in order]
        same = sum(1 for k, v in zip(order, row) if k != "AP2S1" and v == row[0])
        w(f"| {pos}{observed[pos]} | " + " | ".join(row) + f" | {same}/{len(order) - 1} |")
    w("")

    strict = [p for p in sorted(CLAIMS)
              if all(rec[k][col_of[p]] == observed[p] for k in order)]
    w(f"Positions identical in all eight paralogues: "
      f"{', '.join(f'{p}{observed[p]}' for p in strict) if strict else '(none)'}")
    w("")

    # Kelly's own statement is scoped to "all sigma subunits from APs 1-4", so score
    # that subset separately rather than letting the divergent AP5S1 mask it.
    ap14 = ["AP2S1", "AP1S1", "AP1S2", "AP1S3", "AP3S1", "AP3S2", "AP4S1"]
    strict14 = [p for p in sorted(CLAIMS)
                if all(rec[k][col_of[p]] == observed[p] for k in ap14)]
    ap2_specific = [p for p in sorted(CLAIMS)
                    if all(rec[k][col_of[p]] != observed[p] for k in ap14 if k != "AP2S1")]
    w(f"Restricted to the AP-1 to AP-4 sigma subunits (Kelly's stated scope), the "
      f"positions invariant across all seven are: "
      f"{', '.join(f'{p}{observed[p]}' for p in strict14) if strict14 else '(none)'}")
    w("")
    w(f"Positions where AP2S1 differs from every other AP-1 to AP-4 sigma subunit "
      f"(i.e. AP2-specific): "
      f"{', '.join(f'{p}{observed[p]}' for p in ap2_specific) if ap2_specific else '(none)'}")
    w("")
    r15_col = col_of[15]
    r15_row = {k: rec[k][r15_col] for k in order}
    w(f"R15 column across paralogues: {r15_row}")
    w("")

    summary = {
        "target": TARGET,
        "target_length": len(target),
        "all_claimed_residues_match": all_match,
        "human_rat_mouse_identical": ortholog_identical,
        "positions_identical_in_all_8_paralogs": strict,
        "positions_identical_across_AP1_to_AP4_sigmas": strict14,
        "positions_specific_to_AP2S1_among_AP1_to_AP4_sigmas": ap2_specific,
        "r15_column": r15_row,
    }
    (HERE / "results.json").write_text(json.dumps(summary, indent=2) + "\n")
    w("## Machine-readable summary")
    w("")
    w("```json")
    w(json.dumps(summary, indent=2))
    w("```")
    w("")

    (HERE / "RESULTS.md").write_text("\n".join(out) + "\n")
    print("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
