[project]
name = "agt-bioinformatics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Chris Mungall", email = "cjm@berkeleybop.org" }
]
requires-python = ">=3.12"
dependencies = [
    "biopython>=1.88",
    "pyyaml>=6.0.3",
    "requests>=2.34.2",
]

[project.scripts]
agt-bioinformatics = "agt_bioinformatics:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
