#!/usr/bin/env python3
"""Invariants for ADPRHL1-ai-review.yaml that no repo gate covers.

Why this exists, check by check:

A. **Duplicate YAML keys silently delete data.** PyYAML keeps the last occurrence of a
   repeated mapping key and discards the earlier one without warning. Every gate in this
   repo -- the schema validator, the reference validator, ``checkquotes.py`` -- walks the
   *parsed* document, so a quote that parsing has already removed cannot fail any of them.
   Detection requires reading the raw text.

B. **YAML anchors multiply data.** The mirror of (A): if the document were generated by
   reusing one Python object across N rows, N annotations would share one quote and every
   parsed-tree checker would verify it N times and report N successes.

C. **``checkquotes.py`` does not walk ``provenance`` or ``knowledge_gaps[].provenance``.**
   Those quotes are unchecked locally, and this brief's own advice is to populate
   ``knowledge_gaps``. So this script checks *every* quote-bearing key, and reconciles the
   raw count against the parsed count so that a key it does not know about shows up as an
   arithmetic mismatch rather than as silence.

D. **The GOA row set must reconcile with the reviewed row set**, because the ``fetch-gene``
   stub is known to collapse rows that differ only in WITH/FROM. Any extra entry must be an
   explicit ``NEW`` proposal, and any GOA row without an entry is missing coverage.

E. **``supporting_entities`` must be derived from GOA, not maintained by hand.** Hand-kept
   source lists have drifted on every gene in this campaign that tried it. Same for
   ``propagation_review.source_entities``.

F. **Both directions between ``core_functions`` and the kept rows.** Every
   ``core_functions`` term must be backed by an ACCEPT or NEW row, *and* every ACCEPT/NEW
   term must either appear in ``core_functions`` or be listed in ``CORE_FUNCTION_EXEMPT``
   with a written reason. The second direction is the one that otherwise goes unwritten,
   and silence there would be the check's absence rather than its passing. Stale
   exemptions are reported too, so the dict cannot quietly accumulate.

G. **Prose must not contradict its own action** -- the recurring "summary still says
   Accepted after the action became REMOVE" defect. Checked per ``review`` block, keyed on
   the block's own ``action`` so a new row inherits the check automatically. An *attributed*
   mention of another row's action is legitimate cross-referencing and must not fire.

Run:  python audit_adprhl1_review.py [--self-test]
Exit non-zero on any problem, so it can gate a commit.
"""

from __future__ import annotations

import csv
import re
import sys
from pathlib import Path
from typing import Any

import yaml

HERE = Path(__file__).resolve().parent
GENE_DIR = HERE.parent
REVIEW = GENE_DIR / "ADPRHL1-ai-review.yaml"
GOA = GENE_DIR / "ADPRHL1-goa.tsv"
REPO = GENE_DIR.parents[2]

# Terms proposed by this review rather than present in GOA. Anything in
# existing_annotations that is not a GOA row must be listed here AND be action NEW.
DECLARED_NEW = {
    ("GO:0055005", "ISS", "GO_REF:0000024", "involved_in"),
    ("GO:0051894", "IMP", "PMID:37880701", "involved_in"),
}

# ACCEPT/NEW terms that are deliberately absent from core_functions, each with the reason.
# Check F asserts BOTH directions, so anything kept but not core must be listed here or the
# check fires. Removing an entry from this dict must make the check fire - break-tested.
CORE_FUNCTION_EXEMPT = {
    "GO:0055003": (
        "Its child GO:0055005 carries it in core_functions; listing the parent as well "
        "would be redundant there. Both remain in existing_annotations because they have "
        "different donors and different references."
    ),
}


# --------------------------------------------------------------------------- #
class StrictLoader(yaml.SafeLoader):
    """SafeLoader that refuses duplicate mapping keys instead of silently dropping."""


def _no_duplicates(loader: StrictLoader, node: yaml.MappingNode, deep: bool = False) -> dict:
    mapping: dict = {}
    for key_node, value_node in node.value:
        key = loader.construct_object(key_node, deep=deep)
        if key in mapping:
            raise ValueError(f"duplicate YAML key {key!r} at line {key_node.start_mark.line + 1}")
        mapping[key] = loader.construct_object(value_node, deep=deep)
    return mapping


StrictLoader.add_constructor(yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG, _no_duplicates)


def norm(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip().lower()


def walk_quotes(node: Any, path: str = "", ref: str | None = None):
    """Yield (path, reference_id, supporting_text) for EVERY quote-bearing dict.

    Deliberately structure-agnostic: it fires on any mapping that carries a
    ``supporting_text``, so ``supported_by``, ``findings`` and ``provenance`` are all
    covered, and so is any future key nobody has thought of yet.
    """
    if isinstance(node, dict):
        if "supporting_text" in node:
            yield path, node.get("reference_id", ref), node["supporting_text"]
        nxt = node.get("id", ref) if "findings" in node else ref
        for k, v in node.items():
            yield from walk_quotes(v, f"{path}.{k}", nxt)
    elif isinstance(node, list):
        for i, e in enumerate(node):
            yield from walk_quotes(e, f"{path}[{i}]", ref)


def source_text(ref_id: str) -> str | None:
    if ref_id.startswith("PMID:"):
        p = REPO / "publications" / f"PMID_{ref_id.split(':', 1)[1]}.md"
    elif ref_id.startswith("file:"):
        rel = ref_id.split(":", 1)[1]
        p = REPO / "genes" / rel
        if not p.exists():
            p = REPO / rel
    else:
        return None
    return p.read_text() if p.exists() else ""


def read_goa() -> list[dict[str, str]]:
    with GOA.open() as fh:
        return list(csv.DictReader(fh, delimiter="\t"))


def goa_key(row: dict[str, str]) -> tuple[str, str, str, str]:
    return (row["GO TERM"], row["GO EVIDENCE CODE"], row["REFERENCE"], row["QUALIFIER"])


def ann_key(ann: dict) -> tuple[str, str, str, str]:
    return (
        ann["term"]["id"],
        ann.get("evidence_type", ""),
        ann.get("original_reference_id", ""),
        ann.get("qualifier", ""),
    )


# --------------------------------------------------------------------------- #
def audit(review_text: str | None = None, goa_rows: list[dict] | None = None) -> list[str]:
    problems: list[str] = []
    raw = review_text if review_text is not None else REVIEW.read_text()

    # -- A: duplicate keys -------------------------------------------------- #
    try:
        doc = yaml.load(raw, Loader=StrictLoader)
    except ValueError as exc:
        return [f"A: {exc}"]

    # -- B: anchors / aliases ----------------------------------------------- #
    anchors = re.findall(r"&id\d+", raw)
    aliases = re.findall(r"\*id\d+", raw)
    if anchors or aliases:
        problems.append(
            f"B: YAML anchors/aliases present ({len(anchors)} anchors, {len(aliases)} aliases) - "
            f"raw-vs-parsed counting is unreliable and quotes may be shared between rows"
        )

    # -- C: every quote checked, and raw vs parsed reconciled ---------------- #
    parsed = list(walk_quotes(doc))
    raw_count = len(re.findall(r"^\s*(?:-\s*)?supporting_text:", raw, flags=re.M))
    if raw_count != len(parsed):
        problems.append(
            f"C: raw supporting_text count {raw_count} != parsed {len(parsed)}. Do not "
            f"rationalise this difference - derive the expected number independently."
        )
    unchecked = 0
    for path, ref, quote in parsed:
        if not ref:
            problems.append(f"C: quote with no reference_id at {path}")
            continue
        src = source_text(ref)
        if src is None:
            unchecked += 1  # GO_REF etc: not text-checkable
            continue
        if src == "":
            problems.append(f"C: missing source file for {ref} at {path}")
            continue
        if norm(quote) not in norm(src):
            problems.append(f"C: NOT VERBATIM in {ref} at {path}: {quote[:90]!r}")

    # -- D: GOA reconciliation ---------------------------------------------- #
    rows = goa_rows if goa_rows is not None else read_goa()
    goa_keys = [goa_key(r) for r in rows]
    anns = doc["existing_annotations"]
    ann_keys = [ann_key(a) for a in anns]
    for k in goa_keys:
        if k not in ann_keys:
            problems.append(f"D: GOA row {k} has no entry in existing_annotations")
    for a, k in zip(anns, ann_keys, strict=True):
        if k in goa_keys:
            continue
        if k not in DECLARED_NEW:
            problems.append(f"D: entry {k} is not a GOA row and is not a declared NEW proposal")
        elif a["review"].get("action") != "NEW":
            problems.append(f"D: {k} is a declared NEW proposal but its action is {a['review'].get('action')}")
    n_goa, n_new = len(goa_keys), len(DECLARED_NEW)
    if len(anns) != n_goa + n_new:
        problems.append(f"D: {len(anns)} entries != {n_goa} GOA rows + {n_new} declared NEW")

    # -- E: supporting_entities derived from GOA ---------------------------- #
    withfrom: dict[tuple, list[str]] = {}
    for r in rows:
        withfrom.setdefault(goa_key(r), []).extend(t for t in r["WITH/FROM"].split("|") if t)
    for a, k in zip(anns, ann_keys, strict=True):
        if k not in withfrom:
            continue  # a NEW proposal: its supporting_entities are this review's own
        expected = sorted(set(withfrom[k]))
        got = sorted(set(a.get("supporting_entities") or []))
        if expected != got:
            problems.append(f"E: {k} supporting_entities {got} != GOA WITH/FROM {expected}")
        pr = a["review"].get("propagation_review")
        if pr:
            src_ids = sorted({s["source_id"] for s in pr.get("source_entities", [])})
            if src_ids != expected:
                problems.append(f"E: {k} propagation source_entities {src_ids} != GOA WITH/FROM {expected}")

    # -- F: core_functions <-> ACCEPT/NEW, both directions ------------------- #
    # .get() rather than [] throughout: a malformed block must be REPORTED by check G,
    # not crash check F. A check that raises from inside the collector aborts every later
    # check while the harness still prints as though it ran.
    kept = {a["term"]["id"] for a in anns if a["review"].get("action") in ("ACCEPT", "NEW")}
    cf_terms: set[str] = set()
    for cf in doc.get("core_functions") or []:
        for slot in ("molecular_function", "contributes_to_molecular_function", "in_complex"):
            if cf.get(slot):
                cf_terms.add(cf[slot]["id"])
        for slot in ("directly_involved_in", "locations", "substrates", "anatomical_locations"):
            for t in cf.get(slot) or []:
                cf_terms.add(t["id"])
    if not doc.get("core_functions"):
        problems.append("F: no core_functions defined - state explicitly if the gene is dark")
    for t in sorted(cf_terms - kept):
        problems.append(f"F: core_functions cites {t} but no ACCEPT/NEW annotation carries it")
    # The direction that would otherwise go unwritten: every kept term must either appear in
    # core_functions or be explicitly exempted with a reason. "Unwritten" is not "passing" -
    # and this file created exactly that case by dropping GO:0055003 from core_functions.
    for t in sorted(kept - cf_terms):
        if t not in CORE_FUNCTION_EXEMPT:
            problems.append(
                f"F: {t} is ACCEPT/NEW but appears in neither core_functions nor "
                f"CORE_FUNCTION_EXEMPT - state which, do not leave it silent"
            )
    for t in sorted(set(CORE_FUNCTION_EXEMPT) - kept):
        problems.append(f"F: {t} is exempted from core_functions but is not an ACCEPT/NEW term")
    removed = {a["term"]["id"] for a in anns if a["review"].get("action") == "REMOVE"}
    for t in sorted(cf_terms & removed):
        problems.append(f"F: core_functions cites {t} which this review REMOVEs")

    # -- G: prose must not contradict its own action ------------------------- #
    #     Selects on review.action (a stable field), not on wording, so a reworded
    #     summary cannot skip the check. Attributed cross-references are exempted
    #     deliberately: a guard that forbids legitimate practice gets worked around.
    contradictions = {
        "ACCEPT": (r"\bthis row is removed\b", r"\bremoved here\b"),
        "REMOVE": (r"^\s*Accept(ed)?\b", r"\bkept as\b", r"\bretained here\b"),
        "NEW": (r"^\s*Accept(ed)?\b", r"\bremoved\b"),
        "KEEP_AS_NON_CORE": (r"^\s*Accept(ed)?\b",),
        "MODIFY": (r"^\s*Accept(ed)?\b",),
    }
    attributed = re.compile(
        r"(unlike|whereas|the other|as on the|same as|rows? above|rows? below|by contrast)",
        re.I,
    )
    for a in anns:
        rev = a["review"]
        action = rev.get("action")
        if action is None:
            problems.append(f"G: {a['term']['id']} has no action - refusing to pass vacuously")
            continue
        if action not in contradictions:
            problems.append(f"G: unhandled action {action!r} on {a['term']['id']} - extend the table")
            continue
        for field in ("summary", "reason"):
            text = rev.get(field) or ""
            for sentence in re.split(r"(?<=[.;])\s+", text):
                if attributed.search(sentence):
                    continue
                for pat in contradictions[action]:
                    if re.search(pat, sentence, flags=re.I):
                        problems.append(
                            f"G: {a['term']['id']} action={action} but {field} says: {sentence[:110]!r}"
                        )
    return problems


# --------------------------------------------------------------------------- #
def self_test() -> list[str]:
    """Break-test every check in the direction it exists to catch.

    Each mutation is as fine as the claim it certifies: a mutation that destroys a whole
    section would also be caught by a much weaker implementation and therefore proves
    nothing about what this script actually distinguishes.
    """
    fails: list[str] = []
    raw = REVIEW.read_text()
    rows = read_goa()

    def expect(label: str, text: str, rows_: list[dict], needle: str) -> None:
        got = audit(text, rows_)
        if not any(needle in p for p in got):
            fails.append(f"self-test {label}: expected a problem matching {needle!r}, got {got[:3]}")

    # A: a duplicate key must be rejected, not silently absorbed.
    dup = raw.replace("gene_symbol: ADPRHL1", "gene_symbol: ADPRHL1\ngene_symbol: ADPRHL1", 1)
    assert dup != raw, "self-test A: anchor string absent, mutation was a no-op"
    expect("A", dup, rows, "duplicate YAML key")

    # B: an anchor must be reported.
    anch = raw.replace("existing_annotations:\n- term:", "existing_annotations:\n- &id001\n  term:", 1)
    assert anch != raw, "self-test B: anchor string absent, mutation was a no-op"
    expect("B", anch, rows, "anchors/aliases present")

    # C: a quote altered in ONE character must fail. Not a blanked quote - that would
    #    also be caught by an implementation that merely checked for emptiness.
    q = "Recombinant Adprhl1 can localize to stripes adjacent to the Z-disc"
    assert q in raw, "self-test C: quote target has drifted"
    expect("C", raw.replace(q, q.replace("Z-disc", "M-line"), 1), rows, "NOT VERBATIM")

    # C2: a quote inside knowledge_gaps[].provenance must be checked too. This is the
    #     surface checkquotes.py does not walk, so it is the one worth break-testing.
    pq = "Function of ARH2 would be an interesting area of future study."
    assert pq in raw, "self-test C2: provenance quote target has drifted"
    expect("C2", raw.replace(pq, pq.replace("interesting", "fascinating"), 1), rows, "NOT VERBATIM")

    # D: dropping one GOA row's entry must be detected. Removing a whole annotation block
    #    is coarse, so instead flip only its evidence code, which changes its key while
    #    leaving the document otherwise intact.
    bad = raw.replace(
        "    id: GO:0003242\n    label: cardiac chamber ballooning\n  evidence_type: ISS",
        "    id: GO:0003242\n    label: cardiac chamber ballooning\n  evidence_type: IEA",
        1,
    )
    assert bad != raw, "self-test D: anchor string absent, mutation was a no-op"
    expect("D", bad, rows, "has no entry in existing_annotations")

    # E: drifted supporting_entities must be detected. Change one token, not the list.
    drift = raw.replace("  - InterPro:IPR012108\n", "  - InterPro:IPR050792\n", 1)
    assert drift != raw, "self-test E: anchor string absent, mutation was a no-op"
    expect("E", drift, rows, "supporting_entities")

    # E2: the same invariant must hold for propagation_review.source_entities, which is a
    #     separate list that could drift independently.
    drift2 = raw.replace(
        "      - source_id: InterPro:IPR012108\n", "      - source_id: InterPro:IPR005502\n", 1
    )
    assert drift2 != raw, "self-test E2: anchor string absent, mutation was a no-op"
    expect("E2", drift2, rows, "propagation source_entities")

    # F: a core_functions term with no ACCEPT/NEW row behind it must be caught, AND the
    #    happy path must pass - a check that fails on perfect agreement is a real,
    #    observed failure mode.
    orphan = raw.replace(
        "  - id: GO:0003242\n    label: cardiac chamber ballooning\n  locations:",
        "  - id: GO:0016787\n    label: hydrolase activity\n  locations:",
        1,
    )
    assert orphan != raw, "self-test F: anchor string absent, mutation was a no-op"
    expect("F", orphan, rows, "no ACCEPT/NEW annotation carries it")

    # F2: the reverse direction. Dropping the exemption for a kept-but-not-core term must
    #     fire; a mutation that emptied core_functions entirely would be caught by a much
    #     weaker implementation, so mutate only the exemption dict.
    #     NB: mutate THIS module's global in place. `import audit_adprhl1_review` from
    #     inside the script creates a SECOND module object with its own globals when the
    #     file is run as __main__, so patching that copy leaves audit() reading the
    #     original and the break-test silently reports nothing. (Found by running it.)
    saved = dict(CORE_FUNCTION_EXEMPT)
    assert "GO:0055003" in saved, "self-test F2: exemption target has drifted"
    try:
        CORE_FUNCTION_EXEMPT.pop("GO:0055003")
        expect("F2", raw, rows, "appears in neither core_functions nor CORE_FUNCTION_EXEMPT")
        # ...and an exemption for a term that is NOT kept must also be reported, so the
        # dict cannot silently accumulate stale entries.
        CORE_FUNCTION_EXEMPT["GO:0016787"] = "not a kept term"
        expect("F3", raw, rows, "is exempted from core_functions but is not an ACCEPT/NEW term")
    finally:
        CORE_FUNCTION_EXEMPT.clear()
        CORE_FUNCTION_EXEMPT.update(saved)

    # G: prose contradicting its own action must fire...
    contra = raw.replace(
        "    reason: >-\n      Removed on the term's own provenance",
        "    reason: >-\n      Accepted. Removed on the term's own provenance",
        1,
    )
    assert contra != raw, "self-test G: anchor string absent, mutation was a no-op"
    expect("G", contra, rows, "action=REMOVE but reason says")

    # G2: ...but an ATTRIBUTED cross-reference must NOT fire. A guard that forbids
    #     legitimate practice gets circumvented rather than obeyed.
    ok = raw.replace(
        "    reason: >-\n      Removed on the term's own provenance",
        "    reason: >-\n      Unlike the sarcomere rows, which are accepted, this row is "
        "removed on the term's own provenance",
        1,
    )
    assert ok != raw, "self-test G2: anchor string absent, mutation was a no-op"
    if any(p.startswith("G:") for p in audit(ok, rows)):
        fails.append("self-test G2: an attributed cross-reference wrongly fired the prose check")

    # G3: a block with no action must fail loudly rather than pass vacuously. This is the
    #     single most common way a guard reports coverage it does not have.
    noaction = raw.replace("    action: ACCEPT\n", "", 1)
    assert noaction != raw, "self-test G3: anchor string absent, mutation was a no-op"
    expect("G3", noaction, rows, "has no action")

    # Happy path: the real file must be clean, or every result above is meaningless.
    live = audit(raw, rows)
    if live:
        fails.append(f"self-test: the committed file itself has {len(live)} problem(s): {live}")
    return fails


def main() -> int:
    if "--self-test" in sys.argv:
        fails = self_test()
        for f in fails:
            print("SELF-TEST FAIL:", f)
        print(f"self-test: {'PASSED' if not fails else str(len(fails)) + ' FAILURE(S)'}")
        return 1 if fails else 0
    problems = audit()
    for p in problems:
        print("PROBLEM:", p)
    print(f"audit_adprhl1_review: {len(problems)} problem(s)")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
