#!/usr/bin/env python3
"""Annotate cilium life-cycle module candidate members with review status and
HPA subcellular / cilium-atlas evidence.

Input:  projects/HUMAN_PROTEIN_ATLAS/cilium_life_cycle/candidate_members.tsv
        (stage, gene, uniprot, protein_name, role; accessions fetched from the
        UniProt REST API, reviewed human entries)
        projects/HUMAN_PROTEIN_ATLAS/data/subcellular_location.tsv (HPA v25)
Output: projects/HUMAN_PROTEIN_ATLAS/cilium_life_cycle/member_evidence.tsv
        projects/HUMAN_PROTEIN_ATLAS/cilium_life_cycle/member_evidence.md

Usage (from repo root):
    uv run python projects/HUMAN_PROTEIN_ATLAS/scripts/cilium_members.py
"""

import csv
from pathlib import Path

import yaml

PROJECT = Path("projects/HUMAN_PROTEIN_ATLAS")
WORK = PROJECT / "cilium_life_cycle"
GRADES = ["Enhanced", "Supported", "Approved", "Uncertain"]
CILIA_LOCS = ["Primary cilium", "Primary cilium tip", "Primary cilium transition zone",
              "Basal body", "Centrosome", "Centriolar satellite"]
ABBR = {"Enhanced": "E", "Supported": "S", "Approved": "A", "Uncertain": "U"}


def load_hpa():
    hpa = {}
    for r in csv.DictReader((PROJECT / "data/subcellular_location.tsv").open(), delimiter="\t"):
        grade = {}
        for g in GRADES:
            for loc in filter(None, (r.get(g) or "").split(";")):
                grade[loc] = g
        hpa[r["Gene name"]] = {"reliability": r["Reliability"], "grade": grade,
                               "main": r["Main location"]}
    return hpa


def review_status(gene):
    f = Path("genes/human") / gene / f"{gene}-ai-review.yaml"
    if not f.exists():
        return "none", ""
    doc = yaml.safe_load(f.read_text()) or {}
    actions = [(a.get("review") or {}).get("action") for a in doc.get("existing_annotations") or []]
    pending = sum(1 for a in actions if a in (None, "PENDING"))
    status = "complete" if pending == 0 else f"{pending} pending"
    return status, str(f)


def main():
    hpa = load_hpa()
    rows = []
    for m in csv.DictReader((WORK / "candidate_members.tsv").open(), delimiter="\t"):
        h = hpa.get(m["gene"])
        if h:
            calls = [f"{loc} ({ABBR[h['grade'][loc]]})" for loc in CILIA_LOCS if loc in h["grade"]]
            hpa_rel, hpa_main = h["reliability"], h["main"]
        else:
            calls, hpa_rel, hpa_main = [], "not in HPA", ""
        status, path = review_status(m["gene"])
        rows.append({**m, "review": status, "hpa_reliability": hpa_rel,
                     "hpa_cilia_calls": "; ".join(calls), "hpa_main": hpa_main,
                     "review_file": path})

    fields = list(rows[0])
    with (WORK / "member_evidence.tsv").open("w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=fields, delimiter="\t")
        w.writeheader()
        w.writerows(rows)

    reviewed = sum(1 for r in rows if r["review"] != "none")
    with_cilia = sum(1 for r in rows if r["hpa_cilia_calls"])
    lines = [
        "# Cilium life-cycle candidate members (generated by scripts/cilium_members.py)\n",
        f"{len(rows)} candidates; {reviewed} have a gene review; "
        f"{with_cilia} have an HPA call at a cilium, basal body, centrosome or "
        "centriolar satellite.\n",
        "HPA grades: E = Enhanced, S = Supported, A = Approved, U = Uncertain.\n",
        "| stage | gene | UniProt | role | review | HPA cilia/centrosome calls | HPA main location |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(f"| {r['stage']} | {r['gene']} | {r['uniprot']} | {r['role']} | "
                     f"{r['review']} | {r['hpa_cilia_calls'] or '-'} | {r['hpa_main'] or r['hpa_reliability']} |")
    (WORK / "member_evidence.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines[:3]))


if __name__ == "__main__":
    main()
