#!/usr/bin/env python3
"""
Compare GO term sets for a set of genes across three sources:

  G1  = direct local GO-GPT inference (from {gene}-gogpt-predictions.yaml,
        generated by scripts/gogpt_predict.py)
  G2  = the structured GO panel at the end of the BioReason-Pro web export
        (from {gene}-deep-research-bioreason.md, the "**Molecular Function:** ..."
        paragraphs — this is believed to be GO-GPT output plus its ancestor closure)
  G3  = GO term IDs cited inline in the narrative / thinking trace portion of the
        same web-export file (everything BEFORE the structured panel)

The central question: is G3 (what the SFT/RL narrative actually uses) a faithful
readout of the model's upstream GO-GPT prediction, or does it diverge? If the
narrative cites terms that are in neither G1 nor G2, the LLM is confabulating GO
IDs on top of what the model actually predicts.

If a gene's -gogpt-predictions.yaml does not exist, this script will run the
GO-GPT model via scripts.gogpt_predict.load_predictor and populate it. Running
GO-GPT is slow; the model is loaded once and reused across genes.

Usage:
    python scripts/compare_gogpt_vs_narrative.py \
        --genes human/TP53 ECOLI/DnaK SCHPO/Epe1 worm/daf-2 yeast/TOR1 \
                BACSU/sigF AGKCO/fibrolase BACSU/spo0A human/EGFR DROME/Hsp83 \
        --out-tsv projects/BIOREASON_COMPARISON/article/gogpt_vs_narrative_results.tsv \
        --out-md  projects/BIOREASON_COMPARISON/article/gogpt_vs_narrative_results.md
"""
from __future__ import annotations

import argparse
import os
import re
import sys
import yaml
from dataclasses import dataclass, field
from pathlib import Path

REPO = Path(os.environ.get("AIGR_DIR", os.path.expanduser("~/repos/ai-gene-review")))
MODEL_DIR = Path(os.path.expanduser("~/repos/BioReason-Pro/models/gogpt"))

# Terms excluded by scripts/gogpt_predict.py's GENERIC_TERMS filter. Kept here
# only for reference; we do not re-apply the filter because the YAML is already
# post-filter.
GENERIC_TERMS = {
    "GO:0003674", "GO:0008150", "GO:0005575",
    "GO:0005488", "GO:0009987", "GO:0008152",
    "GO:0044237", "GO:0071704", "GO:0044238",
    "GO:0006807", "GO:0044260", "GO:0043170",
    "GO:0097159", "GO:1901363",
}

ORG_NAME = {
    "human":  "Homo sapiens",
    "mouse":  "Mus musculus",
    "rat":    "Rattus norvegicus",
    "yeast":  "Saccharomyces cerevisiae (strain ATCC 204508 / S288c)",
    "worm":   "Caenorhabditis elegans",
    "DROME":  "Drosophila melanogaster",
    "ARATH":  "Arabidopsis thaliana",
    "PSEPK":  "Pseudomonas putida (strain ATCC 47054 / DSM 6125 / CFBP 8728 / NCIMB 11950 / KT2440)",
    "ECOLI":  "Escherichia coli (strain K12)",
    "SCHPO":  "Schizosaccharomyces pombe (strain 972 / ATCC 24843)",
    "BACSU":  "Bacillus subtilis (strain 168)",
    "AGKCO":  "Agkistrodon contortrix contortrix (Southern copperhead)",
    "ANOGA":  "Anopheles gambiae (African malaria mosquito)",
}

GO_ID_RE = re.compile(r"GO:\d{7}")


@dataclass
class GeneResult:
    organism: str
    gene: str
    uniprot_id: str | None = None
    g1: set[str] = field(default_factory=set)  # direct GO-GPT
    g2: set[str] = field(default_factory=set)  # web-export structured panel
    g3: set[str] = field(default_factory=set)  # narrative citations
    g1_source: str = ""
    has_g2: bool = False
    has_g3: bool = False


def extract_g1(predictions_yaml: Path) -> set[str]:
    """Parse {gene}-gogpt-predictions.yaml and return the set of predicted GO IDs."""
    with open(predictions_yaml) as f:
        doc = yaml.safe_load(f)
    ids: set[str] = set()
    for p in doc.get("predictions", []):
        gid = (p.get("predicted_term") or {}).get("id", "")
        if GO_ID_RE.fullmatch(gid):
            ids.add(gid)
    return ids


def extract_g2_g3(bioreason_md: Path) -> tuple[set[str], set[str]]:
    """
    Parse {gene}-deep-research-bioreason.md (or -rl.md) and return two sets:
      - G2: GO IDs under the "**Molecular Function:** ... **Biological Process:** ...
            **Cellular Component:** ..." structured panel at the end of the file.
      - G3: GO IDs cited anywhere BEFORE that panel (thinking trace, functional
            summary, interpro table descriptions).

    If the file has no structured panel, G2 is empty and G3 covers the whole file.
    """
    text = bioreason_md.read_text()
    m = re.search(r"^\*\*Molecular Function", text, re.MULTILINE)
    if m:
        narrative = text[: m.start()]
        panel = text[m.start() :]
    else:
        narrative = text
        panel = ""
    g3 = set(GO_ID_RE.findall(narrative))
    g2 = set(GO_ID_RE.findall(panel))
    return g2, g3


def extract_sequence(uniprot_file: Path) -> str:
    lines = uniprot_file.read_text().splitlines()
    in_seq = False
    seq: list[str] = []
    for line in lines:
        if line.startswith("SQ"):
            in_seq = True
            continue
        if in_seq:
            if line.startswith("//"):
                break
            seq.append(line.strip().replace(" ", ""))
    return "".join(seq).upper()


def extract_accession(uniprot_file: Path) -> str | None:
    for line in uniprot_file.read_text().splitlines():
        if line.startswith("AC"):
            return line[5:].strip().split(";")[0]
    return None


def load_predictor():
    """Load the GO-GPT predictor. Cached across invocations."""
    import json
    import torch
    sys.path.insert(0, str(Path.home() / "repos/BioReason-Pro/gogpt/src"))
    from gogpt.inference import GOGPTPredictor, GOTokenizerJSON, OrganismMapperJSON
    from transformers import AutoTokenizer

    print(f"[GO-GPT] loading model from {MODEL_DIR} ...", flush=True)
    predictor = object.__new__(GOGPTPredictor)
    predictor.device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
    predictor.verbose = False
    predictor.config_path = str(MODEL_DIR / "config.yaml")
    predictor._embed_model_path = "facebook/esm2_t36_3B_UR50D"
    with open(MODEL_DIR / "tokenizer_info.json") as f:
        predictor.tokenizer_info = json.load(f)
    predictor.go_tokenizer = GOTokenizerJSON.from_json(MODEL_DIR / "go_tokenizer.json")
    predictor.organism_mapper = OrganismMapperJSON.from_json(MODEL_DIR / "organism_mapper.json")
    predictor.protein_tokenizer = AutoTokenizer.from_pretrained("facebook/esm2_t36_3B_UR50D")
    predictor._load_model(str(MODEL_DIR / "model.ckpt"))
    print(f"[GO-GPT] loaded on {predictor.device}", flush=True)
    return predictor


def run_gogpt(predictor, organism: str, uniprot_file: Path) -> set[str]:
    import torch
    seq = extract_sequence(uniprot_file)
    if not seq or len(seq) < 10:
        return set()
    if len(seq) > 2000:
        seq = seq[:2000]
    org_name = ORG_NAME.get(organism, organism)
    if org_name == organism:
        for name in predictor.organism_mapper.organism_to_idx:
            if organism.lower() in name.lower():
                org_name = name
                break
    with torch.no_grad():
        preds = predictor.predict(sequence=seq, organism=org_name)
    ids: set[str] = set()
    for aspect in ("MF", "BP", "CC"):
        for gid in preds.get(aspect, []):
            if GO_ID_RE.fullmatch(gid) and gid not in GENERIC_TERMS:
                ids.add(gid)
    return ids


def load_or_run(
    result: GeneResult,
    predictor_lazy,
) -> GeneResult:
    gene_dir = REPO / "genes" / result.organism / result.gene
    pred_yaml = gene_dir / f"{result.gene}-gogpt-predictions.yaml"
    bioreason_md = gene_dir / f"{result.gene}-deep-research-bioreason.md"
    bioreason_rl_md = gene_dir / f"{result.gene}-deep-research-bioreason-rl.md"
    uniprot_file = gene_dir / f"{result.gene}-uniprot.txt"

    if uniprot_file.exists():
        result.uniprot_id = extract_accession(uniprot_file)

    # G1: direct GO-GPT
    if pred_yaml.exists():
        result.g1 = extract_g1(pred_yaml)
        result.g1_source = "cached"
    elif uniprot_file.exists():
        predictor = predictor_lazy()
        print(f"[{result.organism}/{result.gene}] running GO-GPT inference ...", flush=True)
        result.g1 = run_gogpt(predictor, result.organism, uniprot_file)
        result.g1_source = "fresh"
    else:
        print(f"[{result.organism}/{result.gene}] no UniProt file, skipping G1", flush=True)

    # G2 and G3 from the web-export file (prefer SFT scrape, fall back to RL)
    source_md = None
    if bioreason_md.exists():
        source_md = bioreason_md
    elif bioreason_rl_md.exists():
        source_md = bioreason_rl_md
    if source_md is not None:
        g2, g3 = extract_g2_g3(source_md)
        result.g2 = g2
        result.g3 = g3
        result.has_g2 = bool(g2)
        result.has_g3 = bool(g3)

    return result


def summarize(results: list[GeneResult]) -> tuple[str, str]:
    """Return (tsv_text, md_text) summarising the per-gene comparisons."""
    header = [
        "organism", "gene", "uniprot", "|G1|", "|G2|", "|G3|",
        "|G3 in G1|", "|G3 in G2|", "|G3 in G2 not G1|", "|G3 not in G2|",
        "g1_source",
    ]
    tsv_lines = ["\t".join(header)]
    md_lines = [
        "# GO-GPT vs narrative GO citations",
        "",
        "**G1** = direct local GO-GPT inference (`{gene}-gogpt-predictions.yaml`).  ",
        "**G2** = structured GO panel at the end of the BioReason-Pro web export "
        "(`**Molecular Function:** ...` paragraphs — believed to be the GO-GPT "
        "prediction closed under ancestors).  ",
        "**G3** = GO IDs cited inline in the narrative / thinking trace portion of "
        "the same web export (everything BEFORE the structured panel).",
        "",
        "For each gene we compute:",
        "",
        "- `|G3 in G1|` — narrative citations that match the actual most-specific GO-GPT prediction.",
        "- `|G3 in G2|` — narrative citations that are somewhere in the ancestor closure shown in the structured panel.",
        "- `|G3 in G2 not G1|` — narrative citations that are in the ancestor closure but *not* in the direct prediction (i.e., the LLM is retrieving ancestors of the prediction).",
        "- `|G3 not in G2|` — narrative citations that are not in the structured panel at all. If this is nonzero, the LLM is confabulating GO IDs on top of what the model predicts.",
        "",
        "| Organism | Gene | UniProt | \\|G1\\| | \\|G2\\| | \\|G3\\| | G3∩G1 | G3∩G2 | G3∩(G2−G1) | G3−G2 | Source of G1 |",
        "|---|---|---|---:|---:|---:|---:|---:|---:|---:|---|",
    ]

    agg = {k: 0 for k in ("|G1|", "|G2|", "|G3|", "g3_in_g1", "g3_in_g2", "g3_in_g2_not_g1", "g3_not_in_g2")}
    n = 0

    for r in results:
        g3_in_g1 = r.g3 & r.g1
        g3_in_g2 = r.g3 & r.g2
        g3_in_g2_not_g1 = (r.g3 & r.g2) - r.g1
        g3_not_in_g2 = r.g3 - r.g2
        row = [
            r.organism, r.gene, r.uniprot_id or "",
            str(len(r.g1)), str(len(r.g2)), str(len(r.g3)),
            str(len(g3_in_g1)), str(len(g3_in_g2)),
            str(len(g3_in_g2_not_g1)), str(len(g3_not_in_g2)),
            r.g1_source,
        ]
        tsv_lines.append("\t".join(row))
        md_lines.append(
            f"| {r.organism} | {r.gene} | {r.uniprot_id or ''} | "
            f"{len(r.g1)} | {len(r.g2)} | {len(r.g3)} | "
            f"{len(g3_in_g1)} | {len(g3_in_g2)} | "
            f"{len(g3_in_g2_not_g1)} | {len(g3_not_in_g2)} | {r.g1_source} |"
        )
        agg["|G1|"] += len(r.g1)
        agg["|G2|"] += len(r.g2)
        agg["|G3|"] += len(r.g3)
        agg["g3_in_g1"] += len(g3_in_g1)
        agg["g3_in_g2"] += len(g3_in_g2)
        agg["g3_in_g2_not_g1"] += len(g3_in_g2_not_g1)
        agg["g3_not_in_g2"] += len(g3_not_in_g2)
        n += 1

    if n:
        md_lines.extend([
            "",
            f"**Aggregate (n={n}):** "
            f"ΣG1={agg['|G1|']}, ΣG2={agg['|G2|']}, ΣG3={agg['|G3|']}. "
            f"G3∩G1={agg['g3_in_g1']} "
            f"({agg['g3_in_g1']/max(agg['|G3|'],1):.1%} of narrative citations), "
            f"G3∩G2={agg['g3_in_g2']} "
            f"({agg['g3_in_g2']/max(agg['|G3|'],1):.1%}), "
            f"G3 in G2 but not G1 = {agg['g3_in_g2_not_g1']} "
            f"(ancestor-only retrievals), "
            f"G3 not in G2 = {agg['g3_not_in_g2']} "
            f"({agg['g3_not_in_g2']/max(agg['|G3|'],1):.1%} potentially confabulated).",
        ])

    tsv_lines.append("")  # trailing newline
    return "\n".join(tsv_lines), "\n".join(md_lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--genes",
        nargs="+",
        required=True,
        help="Gene specs as ORG/GENE (e.g., human/TP53 ECOLI/DnaK).",
    )
    ap.add_argument("--out-tsv", required=True, type=Path)
    ap.add_argument("--out-md", required=True, type=Path)
    args = ap.parse_args()

    # Lazy loader — only load the (slow) GO-GPT model if at least one gene needs it.
    _predictor_cache = [None]
    def predictor_lazy():
        if _predictor_cache[0] is None:
            _predictor_cache[0] = load_predictor()
        return _predictor_cache[0]

    results: list[GeneResult] = []
    for spec in args.genes:
        org, gene = spec.split("/", 1)
        r = GeneResult(organism=org, gene=gene)
        load_or_run(r, predictor_lazy)
        results.append(r)
        print(
            f"[{org}/{gene}] G1={len(r.g1)} G2={len(r.g2)} G3={len(r.g3)} "
            f"g3∩g1={len(r.g3 & r.g1)} g3∩g2={len(r.g3 & r.g2)} "
            f"g3-g2={len(r.g3 - r.g2)} source={r.g1_source or 'none'}",
            flush=True,
        )

    tsv, md = summarize(results)
    args.out_tsv.parent.mkdir(parents=True, exist_ok=True)
    args.out_tsv.write_text(tsv)
    args.out_md.write_text(md)
    print(f"\nWrote {args.out_tsv}")
    print(f"Wrote {args.out_md}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
