#!/usr/bin/env python
"""Measure and maintain conf/local_quote_baseline.yaml.

The baseline lists the ``file:`` / ``Reactome:`` supporting_text quotes that
already failed the verbatim check when it was introduced (see
``ai_gene_review.validation.local_source_text``). Validation reports a listed
failure as a warning and any other failure as an error.

Usage:
    uv run python scripts/local_quote_baseline.py            # summary only
    uv run python scripts/local_quote_baseline.py --prune    # drop entries that now pass
    uv run python scripts/local_quote_baseline.py --report reports/local-quote-failures.yaml
    uv run python scripts/local_quote_baseline.py --write    # rebuild from scratch

``--prune`` only ever removes entries. ``--write`` lists every current failure,
including new ones, so use it only to (re)initialise the baseline, never to
make a new failure pass. If a regenerated source (``just fetch-gene``, a re-run
deep-research file) breaks quotes that used to pass, re-quote the new source;
if a review file is renamed, move its key in the baseline unchanged.
"""

from __future__ import annotations

import argparse
import collections
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path
from typing import Dict, List, Tuple

import yaml

from ai_gene_review.validation.local_source_text import (
    BASELINE_PATH,
    PROJECT_ROOT,
    baseline_key,
    find_local_quote_failures,
    quote_digest,
)

try:
    from yaml import CSafeLoader as Loader
except ImportError:  # pragma: no cover - libyaml missing
    from yaml import SafeLoader as Loader  # type: ignore[assignment]

HEADER = """\
# Known non-verbatim file:/Reactome: supporting_text quotes.
#
# Generated by scripts/local_quote_baseline.py; do not add entries by hand.
# Each entry is quote_digest(reference_id, supporting_text) for a quote in that
# review that was not found in its local source when the check was introduced.
# Validation reports a listed quote as a WARNING and any other failing quote as
# an ERROR. After fixing quotes, shrink this file with:
#   just local-quote-baseline --prune
"""


def scan(path: Path) -> Tuple[str, List[Tuple[str, str, str, str]]]:
    """Return the baseline key and local-quote failures for one review."""
    data = yaml.load(path.read_text(encoding="utf-8"), Loader=Loader)
    key = baseline_key(path)
    if key is None:
        raise ValueError(f"{path} is not under {PROJECT_ROOT}")
    return key, find_local_quote_failures(data)


def main() -> None:
    """Command-line entry point."""
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--prune", action="store_true", help="drop entries that now pass")
    mode.add_argument("--write", action="store_true", help="rebuild the baseline from all current failures")
    parser.add_argument("--report", type=Path, help="write every current failure to this YAML file")
    parser.add_argument("--jobs", type=int, default=None, help="worker processes")
    args = parser.parse_args()

    files = sorted(PROJECT_ROOT.glob("genes/*/*/*-ai-review.yaml"))
    with ProcessPoolExecutor(max_workers=args.jobs) as pool:
        results = dict(pool.map(scan, files, chunksize=16))

    current: Dict[str, set] = {
        key: {quote_digest(ref, quote) for _, ref, quote, _ in fails}
        for key, fails in results.items()
        if fails
    }
    loaded = yaml.safe_load(BASELINE_PATH.read_text()) if BASELINE_PATH.exists() else None
    baseline: Dict[str, set] = {
        k: set(v or []) for k, v in ((loaded or {}).get("entries") or {}).items()
    }

    reasons = collections.Counter(
        (ref.split(":", 1)[0], reason)
        for fails in results.values()
        for _, ref, _, reason in fails
    )
    unlisted = sum(len(d - baseline.get(k, set())) for k, d in current.items())
    stale = sum(len(d - current.get(k, set())) for k, d in baseline.items())
    print(f"Reviews scanned: {len(files)}; with failing local quotes: {len(current)}")
    for (prefix, reason), n in sorted(reasons.items()):
        print(f"  {prefix}: {reason}: {n}")
    print(f"Distinct failing quotes not in baseline: {unlisted}")
    print(f"Baseline entries that now pass: {stale}")

    if args.report:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        rows = [
            {"file": key, "path": p, "reference_id": ref, "reason": reason, "supporting_text": q}
            for key, fails in sorted(results.items())
            for p, ref, q, reason in fails
        ]
        args.report.write_text(yaml.safe_dump(rows, sort_keys=False, allow_unicode=True, width=100))
        print(f"Wrote {len(rows)} failures to {args.report}")

    if args.write:
        new = current
    elif args.prune:
        new = {k: d & current.get(k, set()) for k, d in baseline.items()}
        new = {k: d for k, d in new.items() if d}
    else:
        return
    body = yaml.safe_dump(
        {"entries": {k: sorted(new[k]) for k in sorted(new)}},
        sort_keys=False,
        width=100,
    )
    BASELINE_PATH.write_text(HEADER + body)
    print(f"Wrote {sum(len(d) for d in new.values())} entries for {len(new)} reviews to {BASELINE_PATH.relative_to(PROJECT_ROOT)}")


if __name__ == "__main__":
    main()
