"""Entry point: run both ACTR10 analyses and write RESULTS.md.

Usage:  uv run python analyze.py

Everything is fetched live from UniProt, QuickGO and RCSB; nothing is hard-coded,
and a fresh run must reproduce the committed RESULTS.md apart from the run date.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

import nuclear_arp_control
import nucleotide_gap_survey
import nucleotide_site
import paint_sources
import subunit_granule_survey

HEADER = """# ACTR10 (Q9NZ32) bioinformatics

Generated by `uv run python analyze.py` on {today}. Five questions are addressed.

1. **Where did ACTR10's phylogenetically-propagated (IBA) annotations come from, and
   what does each source actually know?** (`paint_sources.py`)
2. **Does ACTR10 still have a working actin nucleotide site, and has it lost the
   actin polymerisation interface?** (`nucleotide_site.py`)
3. **Do the nuclear and dynactin actin-related proteins localise differently in one
   human dataset?** (`nuclear_arp_control.py`)
4. **Is the missing nucleotide-binding annotation peculiar to ACTR10, and which term do
   GO curators actually use for the actin-fold nucleotide site?**
   (`nucleotide_gap_survey.py`)
5. **Do the other dynactin subunits share ACTR10's granule/extracellular annotations?**
   (`subunit_granule_survey.py`)

All input is fetched live from UniProt, QuickGO, RCSB and the Human Protein Atlas at
run time.

"""


def main() -> None:
    body = HEADER.format(today=date.today().isoformat())
    body += paint_sources.main()
    body += "\n"
    body += nucleotide_site.main()
    body += "\n"
    body += nuclear_arp_control.main()
    body += "\n"
    body += nucleotide_gap_survey.main()
    body += "\n"
    body += subunit_granule_survey.main()
    out = Path(__file__).resolve().parent / "RESULTS.md"
    out.write_text(body)
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
