default: compare control
compare:
    uv run --no-project --with biopython==1.85 python compare.py ../Gfat1-uniprot-source.json ../Gfat1-reference-Q7PLC7-uniprot.json results
control:
    uv run --no-project --with biopython==1.85 python compare.py ../Gfat1-reference-Q7PLC7-uniprot.json ../Gfat1-reference-Q7PLC7-uniprot.json control
