"""Pfam domain architecture of the proteins that inherit a PAINT IBD term from a PTN node.

Usage (from the repository root):

    uv run python interpro/panther/PTHR43599/ptn_domain_check.py PTHR43599 PTN009171110 GO:0004639 PF01259
    uv run python interpro/panther/PTHR43599/ptn_domain_check.py PTHR11609 PTN000549205 GO:0004638 PF02222
    uv run python interpro/panther/PTHR43599/ptn_domain_check.py --accessions PTHR43599 SF3-outliers X1WBH5 Q9W2G2

Arguments: family, PTN node, GO term asserted at that node, and a Pfam accession that marks
the catalytic domain expected for the asserted function. The script

1. reads the PAINT UniProt GAF cached by `just fetch-panther-paint`
   (.cache/panther/gene_association.paint_uniprot.gaf.gz) and lists every UniProtKB
   accession whose IBA for the GO term has the node in its WITH/FROM column;
2. fetches the Pfam matches of each accession from the InterPro REST API;
3. writes interpro/panther/<family>/<family>-<node>-domains.md, one line per protein, and
   flags proteins that lack the expected Pfam domain.

Nothing is hardcoded: the output is whatever the GAF and InterPro return at run time.
"""

import collections
import csv
import gzip
import json
import sys
import time
import urllib.request
from pathlib import Path

GAF = Path(".cache/panther/gene_association.paint_uniprot.gaf.gz")
MEMBERS = Path(".cache/panther/panther-members-19.0.tsv")


def receivers(node: str, go_id: str) -> list[tuple[str, str, str]]:
    out = []
    with gzip.open(GAF, "rt") as fh:
        for line in fh:
            if line.startswith("!"):
                continue
            c = line.rstrip("\n").split("\t")
            if c[4] != go_id:
                continue
            if c[7].split("|")[0].replace("PANTHER:", "") != node:
                continue
            out.append((c[1], c[2], c[12]))
    return sorted(set(out))


def panther_sf(family: str) -> dict[str, str]:
    """Subfamily assignments from the family's entries.csv, the PANTHER organism
    classification files and the member index (whichever lists the accession)."""
    sf = {}
    entries = Path(f"interpro/panther/{family}/{family}-entries.csv")
    if entries.exists():
        with entries.open() as fh:
            for row in csv.DictReader(fh):
                sf[row["id"]] = row["subfamily"]
    for org in Path(".cache/panther").glob("PTHR19.0_*"):
        with org.open() as fh:
            for line in fh:
                c = line.split("\t")
                if len(c) > 3 and c[3].startswith("PTHR"):
                    sf.setdefault(c[1], c[3])
    if MEMBERS.exists():
        with MEMBERS.open() as fh:
            for row in csv.DictReader(fh, delimiter="\t"):
                sf.setdefault(row["uniprot_accession"], row.get("panther_family_sf") or "")
    return sf


def pfam(acc: str) -> list[tuple[str, str, int, int]]:
    url = f"https://www.ebi.ac.uk/interpro/api/entry/pfam/protein/uniprot/{acc}?page_size=50"
    for attempt in range(4):
        try:
            with urllib.request.urlopen(url, timeout=60) as resp:
                if resp.status == 204:
                    return []
                data = json.loads(resp.read() or b"{}")
            break
        except Exception:  # noqa: BLE001 - retry transient network errors
            time.sleep(2 * (attempt + 1))
    else:
        return [("ERROR", "lookup failed", 0, 0)]
    hits = []
    for r in data.get("results", []):
        m = r["metadata"]
        for p in r["proteins"]:
            for loc in p["entry_protein_locations"]:
                for f in loc["fragments"]:
                    hits.append((m["accession"], m["name"], f["start"], f["end"]))
    return sorted(hits, key=lambda h: h[2])


def symbols() -> dict[str, str]:
    sym = {}
    for org in Path(".cache/panther").glob("PTHR19.0_*"):
        with org.open() as fh:
            for line in fh:
                c = line.split("\t")
                if len(c) > 2:
                    sym.setdefault(c[1], c[2])
    return sym


def accession_mode(family: str, label: str, accs: list[str]) -> None:
    """Pfam architecture for named accessions (members that do not inherit from a node)."""
    sf = panther_sf(family)
    sym = symbols()
    lines = [
        f"# Pfam architecture of selected {family} members ({label})",
        "",
        f"Generated by `interpro/panther/PTHR43599/ptn_domain_check.py --accessions {family} {label} "
        + " ".join(accs)
        + "`.",
        "Subfamily and symbol from the PANTHER 19.0 organism classification files; domains from the InterPro REST API.",
        "",
    ]
    for acc in accs:
        doms = pfam(acc)
        dom_txt = "; ".join(f"{d[0]} {d[1]} {d[2]}-{d[3]}" for d in doms) or "no Pfam match"
        lines.append(f"- {acc} {sym.get(acc, acc)} ({sf.get(acc) or 'subfamily not in local files'}): {dom_txt}.")
    out = Path(f"interpro/panther/{family}/{family}-domains-{label}.md")
    out.write_text("\n".join(lines) + "\n")
    print(out)


def main() -> None:
    if sys.argv[1] == "--accessions":
        accession_mode(sys.argv[2], sys.argv[3], sys.argv[4:])
        return
    family, node, go_id, marker = sys.argv[1:5]
    rec = receivers(node, go_id)
    sf = panther_sf(family)
    lines = [
        f"# Pfam architecture of {node} {go_id} IBA recipients ({family})",
        "",
        f"Generated by `interpro/panther/PTHR43599/ptn_domain_check.py {family} {node} {go_id} {marker}`.",
        "Recipients come from the cached PAINT UniProt GAF; domains from the InterPro REST API.",
        f"Proteins with Pfam matches but without {marker} are flagged LACKS_{marker};",
        "proteins with no Pfam data at all (often obsolete or fragmentary entries) are flagged NO_PFAM_DATA.",
        "",
    ]
    lacking = collections.Counter()
    nodata = collections.Counter()
    for acc, symbol, taxon in rec:
        doms = pfam(acc)
        has = any(d[0] == marker for d in doms)
        if not doms:
            flag = " NO_PFAM_DATA"
            nodata[acc] += 1
        elif not has:
            flag = f" LACKS_{marker}"
            lacking[acc] += 1
        else:
            flag = ""
        dom_txt = "; ".join(f"{d[0]} {d[1]} {d[2]}-{d[3]}" for d in doms) or "no Pfam match"
        lines.append(f"- {acc} {symbol} ({taxon}; {sf.get(acc) or 'subfamily not in local files'}): {dom_txt}.{flag}")
        time.sleep(0.2)
    lines += [
        "",
        f"Recipients: {len(rec)}; lacking {marker}: {len(lacking)}; no Pfam data: {len(nodata)}.",
        "",
    ]
    out = Path(f"interpro/panther/{family}/{family}-{node}-domains.md")
    out.write_text("\n".join(lines))
    print(out, len(rec), len(lacking), len(nodata))


if __name__ == "__main__":
    main()
