"""Report review and module coverage for the IMMUNE_SYSTEM_PATHWAYS areas.

Reads ``projects/IMMUNE_SYSTEM_PATHWAYS/areas.yaml`` and joins each area's
anchor genes against ``genes/human/<SYMBOL>/<SYMBOL>-ai-review.yaml`` (status),
each area's modules against their UniProtKB groundings, and each gene against
human GO-CAM activities in ``gocams/index.tsv``. Writes
``projects/IMMUNE_SYSTEM_PATHWAYS/coverage.md``.

GO-CAM counts only include activities whose ``gene_product`` is a UniProtKB
protein; activities enabled by a complex (a GO:0032991 descendant) are not
attributed to the complex's member genes, so counts are lower bounds.

Run from the repository root:
    uv run python projects/IMMUNE_SYSTEM_PATHWAYS/scripts/coverage.py
"""

from __future__ import annotations

import csv
import re
from collections import defaultdict
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[3]
PROJECT = ROOT / "projects" / "IMMUNE_SYSTEM_PATHWAYS"
UNIPROT_RE = re.compile(r"id: UniProtKB:(\w+)")


def review_status(symbol: str) -> str | None:
    """Return the review's top-level status, or None if there is no review."""
    path = ROOT / "genes" / "human" / symbol / f"{symbol}-ai-review.yaml"
    if not path.exists():
        return None
    for line in path.read_text().splitlines():
        if line.startswith("status:"):
            return line.split(":", 1)[1].strip() or "UNKNOWN"
    return "UNKNOWN"


def human_review_accessions() -> set[str]:
    """UniProt accessions that have a human review file."""
    accs = set()
    for path in (ROOT / "genes" / "human").glob("*/*-ai-review.yaml"):
        with path.open() as fh:
            for line in fh:
                if line.startswith("id:"):
                    accs.add(line.split(":", 1)[1].strip().removeprefix("UniProtKB:"))
                    break
    return accs


def human_gocam_models() -> dict[str, set[str]]:
    """Map human gene symbol -> set of GO-CAM model ids it has an activity in."""
    models: dict[str, set[str]] = defaultdict(set)
    with (ROOT / "gocams" / "index.tsv").open() as fh:
        for row in csv.DictReader(fh, delimiter="\t"):
            if row["taxon"] != "NCBITaxon:9606":
                continue
            symbol = row["gene_label"].rsplit(" ", 1)[0]
            models[symbol].add(row["model_id"])
    return models


def module_coverage(slug: str, reviewed: set[str]) -> tuple[int, int, str]:
    """Return (n grounded accessions, n reviewed, module status)."""
    text = (ROOT / "modules" / f"{slug}.yaml").read_text()
    accs = set(UNIPROT_RE.findall(text))
    status = (yaml.safe_load(text) or {}).get("status", "?")
    return len(accs), len(accs & reviewed), status


def main() -> None:
    areas = yaml.safe_load((PROJECT / "areas.yaml").read_text())["areas"]
    reviewed_accs = human_review_accessions()
    gocams = human_gocam_models()

    lines = [
        "---",
        'title: "Immune System Pathways: Coverage Tables"',
        "species: [human]",
        "---",
        "",
        "# Immune System Pathways: Coverage Tables",
        "",
        "Generated by `projects/IMMUNE_SYSTEM_PATHWAYS/scripts/coverage.py` from",
        "`areas.yaml`, `genes/human/*/*-ai-review.yaml`, `modules/*.yaml` and",
        "`gocams/index.tsv`. Do not edit by hand; re-run the script.",
        "Back to the [project page](../IMMUNE_SYSTEM_PATHWAYS.md).",
        "",
        "## Summary by area",
        "",
        "| Area | Anchor genes | Reviewed | COMPLETE | In a human GO-CAM | Modules |",
        "|---|---:|---:|---:|---:|---|",
    ]
    detail: list[str] = []
    module_rows: list[str] = []
    seen_modules: set[str] = set()
    totals = [0, 0, 0, 0]
    for area in areas:
        genes = area["genes"]
        statuses = {g: review_status(g) for g in genes}
        n_rev = sum(1 for s in statuses.values() if s)
        n_complete = sum(1 for s in statuses.values() if s == "COMPLETE")
        n_gocam = sum(1 for g in genes if gocams.get(g))
        for i, v in enumerate((len(genes), n_rev, n_complete, n_gocam)):
            totals[i] += v
        mods = ", ".join(f"`{m}`" for m in area.get("modules", [])) or "none"
        lines.append(
            f"| {area['label']} | {len(genes)} | {n_rev} | {n_complete} | {n_gocam} | {mods} |"
        )
        detail += [
            f"### {area['label']}",
            "",
            "Grounding terms: "
            + "; ".join(f"{t['id']} {t['label']}" for t in area["go"])
            + ".",
        ]
        if area.get("projects"):
            detail.append(
                "Related projects: "
                + ", ".join(f"[{p}](../{p}.md)" for p in area["projects"])
                + "."
            )
        detail += ["", "| Gene | Review status | Human GO-CAM models |", "|---|---|---:|"]
        for g in genes:
            # Reviewed genes auto-link to their human review; unreviewed ones go
            # in a code span so the renderer cannot link a same-named gene in
            # another species (e.g. poplar CASP1).
            label = f"human/{g}" if statuses[g] else f"`{g}`"
            detail.append(f"| {label} | {statuses[g] or 'no review'} | {len(gocams.get(g, ()))} |")
        detail.append("")
        for m in area.get("modules", []):
            if m in seen_modules:
                continue
            seen_modules.add(m)
            n, r, st = module_coverage(m, reviewed_accs)
            module_rows.append(f"| [`{m}`](../../modules/{m}.html) | {st} | {n} | {r} |")
    lines.append(
        f"| **Total** (genes may repeat across areas) | {totals[0]} | {totals[1]} | {totals[2]} | {totals[3]} | |"
    )
    lines += [
        "",
        "## Module grounding",
        "",
        "UniProtKB accessions grounded in each module and how many have a human review.",
        "",
        "| Module | Status | Grounded proteins | With review |",
        "|---|---|---:|---:|",
        *module_rows,
        "",
        "## Anchor genes by area",
        "",
        *detail,
    ]
    out = PROJECT / "coverage.md"
    out.write_text("\n".join(lines).rstrip() + "\n")
    print(f"wrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
