"""Per-protein manual decisions for the 418 settled vesicle-type rows (dossiers_settled.yaml).

Second pass of the vesicle review: the HDA/HTP vesicle-type rows that reviewers had already
set to KEEP_AS_NON_CORE, which pass 1 (decisions_draft.py) did not cover. Written after
reading each gene's dossier; nothing here is computed. Same MISEV2018 framework and the same
category constants as pass 1. Genes reviewed in both passes (APOE, PDCD6IP, ACTB, AHCY, ALPL,
ASS1, ATP6AP2) get the same call here as there.
"""

from decisions_draft import CAT1, CAT2, CAT3, CAT4, CAT5, note

G = {
    "A1BG": note(CAT5, "Secreted plasma glycoprotein."),
    "A2M": note(CAT5, "Secreted plasma protease inhibitor."),
    "A2ML1": note(CAT5, "Secreted protease inhibitor."),
    "AASDHPPT": note(CAT2, "Cytosolic phosphopantetheinyl transferase."),
    "ABHD8": note(CAT2, "Cytoplasmic hydrolase."),
    "ACAT1": note(CAT4, "Mitochondrial acetyl-CoA acetyltransferase."),
    "ACTA2": note(CAT2, "Smooth-muscle actin."),
    "ACTB": note(CAT2, "Cytoplasmic actin."),
    "ADAM10": note(CAT1, "Plasma-membrane metalloprotease."),
    "ADIRF": note(CAT4, "UniProt places ADIRF in the nucleus only."),
    "AGRN": note(CAT5, "Secreted extracellular-matrix proteoglycan."),
    "AHCY": note(CAT2, "Cytoplasmic adenosylhomocysteinase."),
    "AHNAK": note(CAT2, "Large scaffold protein that shuttles to the cytoplasmic face of the plasma membrane."),
    "AHSA1": note(CAT2, "Cytosolic HSP90 co-chaperone."),
    "AKR1C4": note(CAT2, "Cytosolic aldo-keto reductase."),
    "ALAD": note(CAT2, "Cytosolic porphobilinogen synthase."),
    "ALCAM": note(CAT1, "Plasma-membrane adhesion molecule."),
    "ALDOA": note(CAT2, "Cytosolic glycolytic aldolase."),
    "ALPL": note(CAT1, "GPI-anchored plasma-membrane phosphatase; UniProt also records an EV-membrane pool."),
    "AMN": note(CAT1, "Apical plasma-membrane cubilin partner."),
    "ANKFY1": note(CAT1, "Peripheral endosome-membrane protein."),
    "APLP2": note(CAT1, "Plasma-membrane amyloid precursor-like protein."),
    "APOE": note(CAT3, "Apolipoprotein E on lipoprotein particles, which co-isolate with EVs from body fluids."),
    "APOH": note(CAT5, "Secreted plasma beta-2-glycoprotein I."),
    "ARL15": note(CAT2, "Small GTPase of the cytoplasmic face of membranes."),
    "ARMC3": note(CAT2, "Cytoplasmic armadillo-repeat protein."),
    "ARPC4": note(CAT2, "Arp2/3 complex subunit (cytoskeleton)."),
    "ARPC5": note(CAT2, "Arp2/3 complex subunit (cytoskeleton)."),
    "ARSL": note(CAT4, "Golgi-resident arylsulfatase."),
    "ASAH1": note(CAT5, "Lysosomal lumenal acid ceramidase; UniProt notes secretion is extremely low."),
    "ASL": note(CAT2, "Cytosolic argininosuccinate lyase."),
    "ASS1": note(CAT2, "Cytosolic argininosuccinate synthase."),
    "ATP5F1A": note(CAT4, "Mitochondrial ATP synthase subunit."),
    "ATP5F1B": note(CAT4, "Mitochondrial ATP synthase subunit."),
    "ATP6AP2": note(CAT1, "Single-pass membrane protein of the endolysosomal V-ATPase assembly."),
    "ATP6V0A4": note(CAT1, "Plasma-membrane V-ATPase subunit."),
    "ATP6V0C": note(CAT1, "V-ATPase membrane subunit of endosomal/vesicle membranes."),
    "ATP6V0D1": note(CAT1, "V-ATPase subunit of endolysosomal membranes."),
    "ATP6V0D2": note(CAT1, "V-ATPase subunit of endolysosomal and plasma membranes."),
    "ATP6V1G1": note(CAT1, "V-ATPase subunit at the apical plasma membrane."),
    "ATRN": note(CAT1, "Plasma-membrane attractin isoform."),
    "AZGP1": note(CAT5, "Secreted zinc-alpha-2-glycoprotein."),
    "B4GALT1": note(CAT1, "Golgi galactosyltransferase whose long isoform has an evidenced cell-surface pool."),
    "BAIAP2": note(CAT2, "Cytoplasmic membrane-deforming adapter."),
    "BAIAP2L1": note(CAT2, "Cytoplasmic actin-bundling adapter."),
    "BLVRA": note(CAT2, "Cytosolic biliverdin reductase."),
    "C5orf46": note(CAT5, "Secreted protein."),
    "CA2": note(CAT2, "Cytosolic carbonic anhydrase."),
    "CALM1": note(CAT2, "Calmodulin."),
    "CALM2": note(CAT2, "Calmodulin."),
    "CALM3": note(CAT2, "Calmodulin."),
    "CALR": note(CAT4, "ER-lumen chaperone calreticulin."),
    "CAPG": note(CAT2, "Cytoplasmic actin-capping protein."),
    "CD14": note(CAT1, "GPI-anchored plasma-membrane receptor."),
    "CD19": note(CAT1, "B-cell plasma-membrane receptor."),
    "CD48": note(CAT1, "GPI-anchored plasma-membrane protein."),
    "CDH1": note(CAT1, "Plasma-membrane E-cadherin."),
    "CDK1": note(CAT2, "Cytoplasmic and nuclear cell-cycle kinase."),
    "CHMP1A": note(CAT2, "ESCRT-III subunit acting on the cytosolic face of endosomes (as CHMP3 in pass 1)."),
    "CHMP2A": note(CAT2, "ESCRT-III subunit acting on the cytosolic face of endosomes (as CHMP3 in pass 1)."),
    "CHMP2B": note(CAT2, "ESCRT-III subunit acting on the cytosolic face of endosomes (as CHMP3 in pass 1)."),
    "CHMP4B": note(CAT2, "ESCRT-III subunit acting on the cytosolic face of endosomes (as CHMP3 in pass 1)."),
    "CHMP5": note(CAT2, "ESCRT-III subunit acting on the cytosolic face of endosomes (as CHMP3 in pass 1)."),
    "CHMP6": note(CAT2, "ESCRT-III subunit acting on the cytosolic face of endosomes (as CHMP3 in pass 1)."),
    "CKB": note(CAT2, "Cytosolic creatine kinase."),
    "CLTC": note(CAT2, "Clathrin heavy chain on the cytoplasmic face of vesicle membranes."),
    "COASY": note(CAT2, "Mainly cytosolic CoA synthase."),
    "COMP": note(CAT5, "Secreted extracellular-matrix protein."),
    "COPS8": note(CAT2, "Cytoplasmic/nuclear COP9 signalosome subunit."),
    "CRISPLD1": note(CAT5, "Secreted protein."),
    "CSK": note(CAT2, "Cytoplasmic tyrosine kinase with a lipid-raft pool."),
    "CUBN": note(CAT1, "Apical plasma-membrane endocytic receptor."),
    "DDC": note(CAT2, "Cytosolic aromatic-L-amino-acid decarboxylase."),
    "DNAJA2": note(CAT2, "Cytosolic farnesylated HSP40 co-chaperone."),
    "DNAJB1": note(CAT2, "Cytoplasmic HSP40 co-chaperone."),
    "DNAJC13": note(CAT1, "Peripheral endosome-membrane protein."),
    "DNAJC3": note(CAT4, "ER-resident co-chaperone."),
    "DPEP1": note(CAT1, "GPI-anchored apical plasma-membrane dipeptidase."),
    "DPYS": note(CAT2, "Cytosolic dihydropyrimidinase."),
    "DPYSL2": note(CAT2, "Cytosolic microtubule-associated protein."),
    "EGF": note(CAT1, "Single-pass membrane pro-EGF precursor."),
    "EIF3E": note(CAT2, "Cytoplasmic translation initiation factor."),
    "FAH": note(CAT2, "Cytosolic fumarylacetoacetase."),
    "FAS": note(CAT1, "Plasma-membrane death receptor."),
    "FKBP4": note(CAT2, "Cytosolic HSP90 co-chaperone."),
    "FKBP5": note(CAT2, "Cytoplasmic HSP90 co-chaperone."),
    "FN1": note(CAT5, "Secreted extracellular-matrix fibronectin."),
    "FTH1": note(CAT2, "Cytoplasmic ferritin heavy chain."),
    "G6PD": note(CAT2, "Cytosolic glucose-6-phosphate dehydrogenase."),
    "GALK1": note(CAT2, "Cytosolic galactokinase."),
    "GALM": note(CAT2, "Cytoplasmic galactose mutarotase."),
    "GALNS": note(CAT5, "Lysosomal lumenal sulfatase."),
    "GAS6": note(CAT5, "Secreted TAM-receptor ligand."),
    "GBA": note(CAT5, "Lysosomal lumenal glucocerebrosidase."),
    "GBA1": note(CAT5, "Lysosomal lumenal glucocerebrosidase."),
    "GET3": note(CAT2, "Cytoplasmic tail-anchored-protein targeting ATPase."),
    "GFPT1": note(CAT2, "Cytosolic glutamine-fructose-6-phosphate transaminase."),
    "GGT1": note(CAT1, "Plasma-membrane gamma-glutamyltransferase."),
    "GLA": note(CAT5, "Lysosomal lumenal alpha-galactosidase."),
    "GLB1": note(CAT5, "Lysosomal lumenal beta-galactosidase."),
    "GLIPR2": note(CAT4, "Golgi-membrane protein."),
    "GLO1": note(CAT2, "Cytosolic glyoxalase."),
    "GLOD4": note(CAT4, "Mitochondrial glyoxalase-domain protein."),
    "GM2A": note(CAT5, "Lysosomal lumenal GM2 activator."),
    "GNS": note(CAT5, "Lysosomal lumenal sulfatase."),
    "GOT1": note(CAT2, "Cytoplasmic aspartate aminotransferase."),
    "GOT2": note(CAT1, "Mitochondrial aminotransferase with a documented plasma-membrane pool."),
    "GPI": note(CAT2, "Cytoplasmic glucose-6-phosphate isomerase."),
    "GRB2": note(CAT2, "Cytoplasmic signalling adapter."),
    "GSR": note(CAT2, "Glutathione reductase, cytoplasmic isoform."),
    "GSS": note(CAT2, "Cytosolic glutathione synthetase."),
    "GUSB": note(CAT5, "Lysosomal lumenal beta-glucuronidase."),
    "HEXA": note(CAT5, "Lysosomal lumenal hexosaminidase."),
    "HGD": note(CAT2, "Cytosolic homogentisate dioxygenase."),
    "HPD": note(CAT2, "Cytoplasmic 4-hydroxyphenylpyruvate dioxygenase."),
    "HPRT1": note(CAT2, "Cytoplasmic purine salvage enzyme."),
    "HPX": note(CAT5, "Secreted plasma hemopexin."),
    "HSPA12A": note(CAT2, "Cytoplasmic HSP70-family protein."),
    "HSPA13": note(CAT4, "ER/microsome HSP70-family protein."),
    "HSPA1B": note(CAT2, "Cytoplasmic HSP70."),
    "HSPA1L": note(CAT2, "Cytoplasmic HSP70."),
    "HSPA2": note(CAT2, "Cytoplasmic HSP70."),
    "HSPA4": note(CAT2, "Cytoplasmic HSP110-family chaperone."),
    "HSPA6": note(CAT2, "Cytoplasmic HSP70."),
    "HSPA8": note(CAT2, "Cytoplasmic HSC70, which also acts at endosomal membranes."),
    "HSPA9": note(CAT4, "Mitochondrial HSP70 (mortalin)."),
    "HSPD1": note(CAT4, "Mitochondrial matrix HSP60."),
    "HSPG2": note(CAT5, "Secreted basement-membrane perlecan."),
    "IDUA": note(CAT5, "Lysosomal lumenal iduronidase."),
    "ITGB1": note(CAT1, "Plasma-membrane integrin."),
    "ITIH1": note(CAT5, "Secreted plasma inter-alpha-trypsin inhibitor chain."),
    "ITIH2": note(CAT5, "Secreted plasma inter-alpha-trypsin inhibitor chain."),
    "ITIH3": note(CAT5, "Secreted plasma inter-alpha-trypsin inhibitor chain."),
    "ITIH4": note(CAT5, "Secreted plasma inter-alpha-trypsin inhibitor chain."),
    "KHK": note(CAT2, "Cytosolic ketohexokinase."),
    "KL": note(CAT1, "Plasma-membrane klotho isoform."),
    "LAMP1": note(CAT1, "Lysosome/endosome-membrane glycoprotein that also cycles to the plasma membrane."),
    "LCK": note(CAT1, "Lipid-anchored plasma-membrane kinase."),
    "LFNG": note(CAT4, "Golgi glycosyltransferase."),
    "LGALS3": note(CAT2, "Cytoplasmic galectin secreted by a non-classical route."),
    "LOXL4": note(CAT5, "Secreted lysyl oxidase-like enzyme."),
    "LPO": note(CAT5, "Secreted lactoperoxidase."),
    "LRG1": note(CAT5, "Secreted plasma glycoprotein."),
    "LRP2": note(CAT1, "Apical plasma-membrane endocytic receptor (megalin)."),
    "LRRK2": note(CAT2, "Cytoplasmic kinase associated with vesicle and Golgi membranes."),
    "LYN": note(CAT1, "Lipid-anchored plasma-membrane kinase."),
    "MAN1B1": note(CAT4, "ER-membrane mannosidase."),
    "MGP": note(CAT5, "Secreted matrix Gla protein."),
    "MTHFD1": note(CAT2, "Cytoplasmic C1-tetrahydrofolate synthase."),
    "MUC1": note(CAT1, "Apical plasma-membrane mucin."),
    "MVB12A": note(CAT2, "ESCRT-I subunit acting on the cytosolic face of endosomes."),
    "MVB12B": note(CAT2, "ESCRT-I subunit acting on the cytosolic face of endosomes."),
    "NAGLU": note(CAT5, "Lysosomal lumenal N-acetylglucosaminidase."),
    "NAMPT": note(CAT2, "Cytoplasmic/nuclear enzyme also released extracellularly."),
    "NAPRT": note(CAT2, "Cytosolic nicotinate phosphoribosyltransferase."),
    "NCSTN": note(CAT1, "Gamma-secretase membrane subunit of the plasma membrane and endosomes."),
    "NID1": note(CAT5, "Secreted basement-membrane nidogen."),
    "NME2": note(CAT2, "Cytoplasmic nucleoside-diphosphate kinase."),
    "NPHS2": note(CAT1, "Podocyte plasma-membrane podocin."),
    "NQO2": note(CAT2, "Cytoplasmic quinone reductase."),
    "NT5E": note(CAT1, "GPI-anchored plasma-membrane ecto-5'-nucleotidase (CD73)."),
    "P3H1": note(CAT4, "ER prolyl 3-hydroxylase."),
    "P4HB": note(CAT4, "ER-lumen protein disulfide isomerase."),
    "PAFAH1B1": note(CAT2, "Cytoplasmic dynein regulator LIS1."),
    "PARD6B": note(CAT2, "Cytoplasmic polarity adapter recruited to the plasma membrane."),
    "PCBD1": note(CAT2, "Cytoplasmic/nuclear pterin-4a-carbinolamine dehydratase."),
    "PDCD5": note(CAT2, "Cytoplasmic/nuclear apoptosis regulator."),
    "PDCD6IP": ("ACCEPT", "ALIX is named by MISEV2018 among proteins actively incorporated into EVs and is a standard EV "
                "marker; consistent with the pass-1 decision for the same protein."),
    "PGK1": note(CAT2, "Cytosolic phosphoglycerate kinase."),
    "PGM1": note(CAT2, "Cytoplasmic phosphoglucomutase."),
    "PHGDH": note(CAT2, "Cytosolic phosphoglycerate dehydrogenase."),
    "PI15": note(CAT5, "Secreted protease inhibitor."),
    "PKLR": note(CAT2, "Cytosolic pyruvate kinase."),
    "PKM": note(CAT2, "Cytoplasmic pyruvate kinase."),
    "PLD3": note(CAT1, "Single-pass membrane protein of ER and endolysosomes."),
    "PM20D1": note(CAT5, "Secreted N-fatty-acyl-amino-acid synthase/hydrolase."),
    "PNP": note(CAT2, "Cytosolic purine nucleoside phosphorylase."),
    "PPIB": note(CAT4, "ER-lumen cyclophilin B."),
    "PPP2CA": note(CAT2, "Cytoplasmic PP2A catalytic subunit."),
    "PPP2R1B": note(CAT2, "Cytoplasmic PP2A scaffold subunit."),
    "PRDX4": note(CAT4, "ER-lumen peroxiredoxin."),
    "PRSS23": note(CAT5, "Secreted serine protease."),
    "PSAP": note(CAT5, "Lysosomal lumenal prosaposin, also secreted."),
    "PSAT1": note(CAT2, "Cytosolic phosphoserine aminotransferase."),
    "PSMA1": note(CAT2, "Cytoplasmic/nuclear proteasome subunit."),
    "PSMB5": note(CAT2, "Cytoplasmic/nuclear proteasome subunit."),
    "PTPRC": note(CAT1, "Plasma-membrane phosphatase CD45."),
    "QDPR": note(CAT2, "Cytosolic dihydropteridine reductase."),
    "QPRT": note(CAT2, "Cytosolic quinolinate phosphoribosyltransferase."),
    "RAB15": note(CAT1, "Lipid-anchored small GTPase of the plasma membrane/endocytic system."),
    "RAB7A": note(CAT1, "Lipid-anchored late-endosome GTPase."),
    "RAB9A": note(CAT1, "Lipid-anchored late-endosome GTPase."),
    "SCAMP2": note(CAT1, "Multi-pass membrane carrier of post-Golgi and endosomal recycling membranes."),
    "SLC3A2": note(CAT1, "Plasma-membrane amino-acid transporter heavy chain (CD98)."),
    "SMO": note(CAT1, "Plasma-membrane GPCR."),
    "SMPD1": note(CAT5, "Lysosomal lumenal acid sphingomyelinase, also secreted."),
    "SOD1": note(CAT2, "Cytoplasmic superoxide dismutase."),
    "SORL1": note(CAT1, "Single-pass sorting receptor of Golgi, endosome and plasma membranes."),
    "SPR": note(CAT2, "Cytoplasmic sepiapterin reductase."),
    "SQSTM1": note(CAT2, "Cytoplasmic autophagy cargo adapter."),
    "SRC": note(CAT1, "Lipid-anchored plasma-membrane kinase."),
    "SYPL1": note(CAT1, "Multi-pass vesicle-membrane protein."),
    "TALDO1": note(CAT2, "Cytoplasmic transaldolase."),
    "TFRC": note(CAT1, "Plasma-membrane transferrin receptor, a classic exosome cargo."),
    "TLN1": note(CAT2, "Cytoskeletal talin."),
    "TNFAIP3": note(CAT2, "Cytoplasmic ubiquitin-editing enzyme."),
    "TNFSF10": note(CAT1, "Plasma-membrane TRAIL ligand."),
    "TPI1": note(CAT2, "Cytoplasmic triosephosphate isomerase."),
    "TPM3": note(CAT2, "Cytoskeletal tropomyosin."),
    "TSG101": note(CAT2, "ESCRT-I subunit acting on the cytosolic face of endosomes; an EV marker protein, but its "
                         "core location is the endosome."),
    "TXN": note(CAT2, "Cytoplasmic thioredoxin."),
    "TXNDC16": note(CAT4, "ER-lumen thioredoxin-domain protein."),
    "UPB1": note(CAT2, "Cytoplasmic beta-ureidopropionase."),
    "VCL": note(CAT2, "Cytoskeletal vinculin at the cytoplasmic face of the plasma membrane."),
    "VCP": note(CAT2, "Cytosolic AAA ATPase p97."),
    "VPS28": note(CAT2, "ESCRT-I subunit acting on the cytosolic face of endosomes."),
    "VPS37B": note(CAT2, "ESCRT-I subunit acting on the cytosolic face of endosomes."),
    "VPS37C": note(CAT2, "ESCRT-I subunit acting on the cytosolic face of endosomes."),
    "VPS37D": note(CAT2, "ESCRT-I subunit acting on the cytosolic face of endosomes."),
    "YWHAZ": note(CAT2, "Cytoplasmic 14-3-3 protein."),
}
