#!/usr/bin/env python3
"""Ingest the IMPReSS standardized phenotyping pipeline from the IMPC API.

IMPReSS (International Mouse Phenotyping Resource of Standardised Screens) is the
closest thing to a standardized, versioned *list of phenotyping assays*. This
script pulls one pipeline's full procedure set from the public API and writes:

- ``impc_procedures.tsv``    — every procedure (key, name, level, version,
                               mandatory/visible, #parameters, MP terms parsed
                               from the description), with a transparent
                               behavioural/neurological flag.
- ``behavioural_assays.yaml`` — the behavioural/neurological subset with detail.
- ``REPORT.md``              — counts + the behavioural-assay table.

Nothing about the results is hard-coded: the data is fetched live and the
behavioural classifier is the regex below (recorded here, not pre-baked). If the
API is unreachable the script errors rather than emitting stale data.

API base: https://api.mousephenotype.org/impress
Docs:     https://www.mousephenotype.org/phenodcc/impress-api-documentation/

Usage:
    uv run python projects/BEHAVIOR/impress/ingest_impress.py \
        --pipeline IMPC_001 --out-dir projects/BEHAVIOR/impress
"""
from __future__ import annotations

import argparse
import csv
import os
import re

import requests
import yaml

API = "https://api.mousephenotype.org/impress"

# Transparent behavioural / neurological classifier (matched against procedure
# name + description). The MP "behavior/neurological phenotype" branch
# (MP:0005386) is the conceptual scope.
BEHAVIOURAL = re.compile(
    r"behav|locomot|anxiety|startle|pre-?pulse|\bPPI\b|SHIRPA|grip strength|"
    r"rotarod|\bmotor\b|hole-?board|light.?dark|open field|nocicept|acoustic|"
    r"auditory|tremor|gait|exploratory|fear condition|learning|memory|maze|"
    r"sensorimotor|neurolog",
    re.I,
)
MP_RE = re.compile(r"MP:\d{7}")


def fetch_pipeline(pipeline: str) -> list[dict]:
    url = f"{API}/procedure/belongingtopipeline/full/{pipeline}"
    r = requests.get(url, timeout=60)
    r.raise_for_status()
    data = r.json()
    procs = list(data.values()) if isinstance(data, dict) else list(data)
    if not procs:
        raise SystemExit(f"No procedures returned for pipeline {pipeline}")
    return procs


def row_for(p: dict) -> dict:
    name = p.get("name", "")
    desc = p.get("description") or ""
    mp = sorted(set(MP_RE.findall(desc)))
    return {
        "procedure_key": p.get("procedureKey", ""),
        "name": name,
        "level": p.get("level", ""),
        "version": f"{p.get('majorVersion')}.{p.get('minorVersion')}",
        "mandatory": p.get("isMandatory", ""),
        "visible": p.get("isVisible", ""),
        "n_parameters": len(p.get("parameterCollection") or []),
        "behavioural_neurological": bool(BEHAVIOURAL.search(name) or BEHAVIOURAL.search(desc)),
        "mp_terms": "|".join(mp),
        "description": re.sub(r"\s+", " ", desc).strip(),
    }


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--pipeline", default="IMPC_001",
                    help="IMPReSS pipeline key or id (default: IMPC_001, the curated IMPC screen)")
    ap.add_argument("--out-dir", default="projects/BEHAVIOR/impress")
    args = ap.parse_args()
    os.makedirs(args.out_dir, exist_ok=True)

    procs = fetch_pipeline(args.pipeline)
    rows = sorted((row_for(p) for p in procs), key=lambda r: r["name"])
    beh = [r for r in rows if r["behavioural_neurological"]]

    cols = ["procedure_key", "name", "level", "version", "mandatory", "visible",
            "n_parameters", "behavioural_neurological", "mp_terms", "description"]
    with open(os.path.join(args.out_dir, "impc_procedures.tsv"), "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=cols, delimiter="\t")
        w.writeheader()
        for r in rows:
            w.writerow(r)

    with open(os.path.join(args.out_dir, "behavioural_assays.yaml"), "w") as fh:
        yaml.safe_dump(
            {"pipeline": args.pipeline, "source": f"{API}/procedure/belongingtopipeline/full/{args.pipeline}",
             "n_total_procedures": len(rows), "n_behavioural": len(beh),
             "assays": [{k: r[k] for k in ("procedure_key", "name", "level", "mp_terms", "description")}
                        for r in beh]},
            fh, sort_keys=False, allow_unicode=True, width=100)

    lines = [f"# IMPReSS ingest — pipeline `{args.pipeline}`\n",
             f"*Auto-generated by `ingest_impress.py` from {API}. Do not edit by hand.*\n",
             f"\n- Total procedures: **{len(rows)}**",
             f"- Behavioural / neurological procedures: **{len(beh)}**\n",
             "\n## Behavioural / neurological assays\n",
             "| Procedure key | Assay | Level | MP terms (from description) |",
             "|---|---|---|---|"]
    for r in beh:
        lines.append(f"| {r['procedure_key']} | {r['name']} | {r['level']} | {r['mp_terms'] or '—'} |")
    report = "\n".join(lines) + "\n"
    with open(os.path.join(args.out_dir, "REPORT.md"), "w") as fh:
        fh.write(report)
    print(report)


if __name__ == "__main__":
    main()
